project:
  type: website
  output-dir: docs

website:
  title: "\"Филеб\" Платона"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Текст
      - translation.qmd
      - comments.qmd
      - video.qmd
      - bib.qmd
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    fontsize: "14pt"
    fontcolor: "#555555"
    toc: true
    toc-location: left
    toc-title: Страницы
    page-layout: full
    grid:
      sidebar-width: 150px

bibliography: references.bib