project:
  type: website
  output-dir: docs

website:
  title: "«Филеб»‎ Платона"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Текст
      - href: translation.qmd
        text: Перевод
      - href: comments.qmd
        text: Комментарии
      - href: video.qmd
        text: Видео
      - bib.qmd
      - about.qmd

format:
  html:
    theme: 
     - lumen
     - custom.scss
    fontsize: "14pt"
    fontcolor: "#555555"
    toc: true
    toc-location: left
    toc-title: Страницы
    page-layout: full
    grid:
      sidebar-width: 250px

bibliography: references.bib