project:
  type: website
  output-dir: docs
  render:
    - "book/*.qmd"

website:
  title: "«Филеб»‎ Платона"
  navbar:
    background: light
    search: true
    left:
      - href: book/index.qmd
        text: Текст
      - href: book/translation.qmd
        text: Перевод
      - href: book/intro.qmd
        text: Введение
      - href: book/comments.qmd
        text: Комментарии
      - href: book/resources.qmd
        text: Ресурсы
      - href: book/codices.qmd
        text: Рукописи
      - href: book/about.qmd
        text: О проекте
      - book/bib.qmd

format:
  html:
    theme: [sandstone, custom.scss]
    crossref:
      fig-title: "Рис."  
      tbl-title: "Табл."
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,500;0,700;1,400;1,700&family=Noto+Sans:wght@400;500;600&subset=latin,latin-ext,cyrillic,greek,greek-ext&display=swap" rel="stylesheet">
    toc: true
    toc-location: left
    toc-title: Страницы
    page-layout: full
    grid:
      sidebar-width: 220px
      body-width: 780px
      margin-width: 280px
      gutter-width: 1.5rem
bibliography: references.bib