project:
  type: website
  output-dir: docs
  render: 
   - "book/*.qmd"
   
website:
  title: "«Филеб»‎ Платона"
  navbar:
    background: primary
    search: true
    left:
      - href: book/index.qmd
        text: Текст
      - href: book/translation.qmd
        text: Перевод
      - href: book/intro.qmd
        text: Введение
      - href: book/comments.qmd
        text: Комментарии 
      - href: book/resources.qmd
        text: Ресурсы
      - href: book/codices.qmd
        text: Рукописи 
      - href: book/about.qmd
        text: О проекте
      - book/bib.qmd
    

format:
  html:
    theme: 
     - sandstone
     - custom.scss
    fontsize: "14pt"
    fontcolor: "#555555"
    toc: true
    toc-location: left
    toc-title: Страницы
    page-layout: full
    grid:
      sidebar-width: 250px

bibliography: references.bib
