---
title: "Текст и переводы"
---


## I. 11a-11c

::: columns
::: {.column width="38%"}
</br>
</br>

::: output

**ΣΩ**. Ὅρα δή, Πρώταρχε, τίνα λόγον μέλλεις παρὰ Φιλήβου δέχεσθαι νυνὶ καὶ πρὸς τίνα τὸν παρ' ἡμῖν ἀμφισβητεῖν, ἐὰν μή σοι κατὰ νοῦν ᾖ λεγόμενος. βούλει συγκεφαλαιωσώμεθα ἑκάτερον; 

**ΠΡΩ.** Πάνυ μὲν οὖν. 

**ΣΩ.** Φίληβος μὲν τοίνυν ἀγαθὸν εἶναί φησι τὸ χαίρειν πᾶσι ζῴοις καὶ τὴν ἡδονὴν καὶ τέρψιν, καὶ ὅσα τοῦ γένους ἐστὶ τούτου σύμφωνα· τὸ δὲ παρ' ἡμῶν ἀμφισβήτημά ἐστι μὴ ταῦτα, ἀλλὰ τὸ φρονεῖν καὶ τὸ νοεῖν καὶ μεμνῆσθαι καὶ τὰ τούτων αὖ συγγενῆ, δόξαν τε ὀρθὴν καὶ ἀληθεῖς λογισμούς, τῆς γε ἡδονῆς ἀμείνω καὶ λῴω γίγνεσθαι σύμπασιν ὅσαπερ αὐτῶν δυνατὰ μεταλαβεῖν· δυνατοῖς δὲ μετασχεῖν ὠφελιμώτατον ἁπάντων εἶναι πᾶσι τοῖς οὖσί τε καὶ ἐσομένοις. μῶν οὐχ οὕτω πως λέγομεν, ὦ Φίληβε, ἑκάτεροι; 

**ΦΙ.** Πάντων μὲν οὖν μάλιστα, ὦ Σώκρατες. 

**ΣΩ.** Δέχῃ δὴ τοῦτον τὸν νῦν διδόμενον, ὦ Πρώταρχε, λόγον; 

**ΠΡΩ.** Ἀνάγκη δέχεσθαι· Φίληβος γὰρ ἡμῖν ὁ καλὸς ἀπείρηκεν.   

**ΣΩ.** Δεῖ δὴ περὶ αὐτῶν τρόπῳ παντὶ τἀληθές πῃ περανθῆναι; 

**ΠΡΩ.** Δεῖ γὰρ οὖν.

:::
 
:::

::: {.column width="2%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

**Сократ**. Посмотри-ка, Протарх, что за положение собираешься ты перенять от Филеба и какое наше положение ты намерен оспаривать, если оно придется тебе не по нраву. Хочешь, мы сжато выразим оба эти положения?

**Протарх**. Очень даже хочу.

**Сократ**. Филеб утверждает, что благом для всех живых существ является радость, наслаждение, удовольствие, и все прочее, принадлежащее к этому роду; мы же оспариваем его, считая, что благом является не это, но рассудительность, мышление, память и то, что сродно с ними: правильное мнение и верные умозаключения. Мы утверждаем, что эти качества лучше и предпочтительнее наслаждения для всех существ, способных приобщиться к ним, причем, для таких существ — и теперь живущих, и тех, которые будут жить впоследствии — ничто не может быть полезнее этого приобщения. Разве не таковы, приблизительно, Филеб, твое и мое положения?

**Филеб**. Совершенно правильно, Сократ.

**Сократ**. Значит, Протарх, ты принимаешь переданное [тебе] положение?

**Протарх**. Приходится принять, потому что красавец наш Филеб что-то притомился.

**Сократ**. Да, нам следует приложить все усилия, чтобы достигнуть окончательной истины относительно обоих положений.

**Протарх**. Разумеется, необходимо. 

### Самсонов 1994

Сократ. Посмотри-ка, Протарх, что за рассуждение собираешься ты перенять от Филеба и какое наше рассуждение намерен оспаривать, если оно придется тебе не по нраву. Хочешь, мы кратко изложим и то, и другое?

Протарх. Очень даже хочу.

Сократ. Филеб утверждает, что благо для всех живых существ – радость, удовольствие, наслаждение и все прочее, принадлежащее к этому роду; мы же оспариваем его, считая, что благо не это, но разумение, мышление, память и то, что сродно с ними: правильное мнение и истинные суждения. Все это лучше и предпочтительнее удовольствия для всех существ, способных приобщиться к этим вещам, и для таких существ – и ныне живущих, и тех, что будут жить впоследствии, – ничто не может быть полезнее этого приобщения. Разве не таковы примерно, Филеб, твоя и моя речи?

Филеб. Именно таковы, Сократ.

Сократ. Значит, Протарх, ты принимаешь данное рассуждение?

Протарх. Приходится принять, потому что красавец наш Филеб что-то примолк.

Сократ. Не следует ли нам приложить все усилия, чтобы достичь здесь истины?

Протарх. Разумеется, это необходимо.

### Алиева 2024

Сократ. Рассмотри, Протарх, какое положение ты сейчас примешь от Филеба и с чем тебе придется спорить, если мои слова придутся тебе не по душе. Давай кратко изложим оба положения?

Протарх. Давай. 

Сократ. Так вот, Филеб считает, что благо для всех живых существ заключается в том, чтобы радоваться, испытывать удовольствие и наслаждение и все то, что созвучно этому роду. Мы же утверждаем, что благо не в этом, а в том, чтобы разуметь, мыслить и помнить, а также во всем, что этому сродно, то есть в правильном мнении и в истинном рассуждении. Все это и лучше, и желаннее удовольствия для всех, кто способен к этому приобщиться, а для тех, кто к этому причастен, — и сейчас, и в будущем — и полезнее всего. Не так ли, Филеб, мы с тобой считаем?

Филеб. Именно так, Сократ. 

Сократ. Принимаешь ли ты, Протарх, положение, которое тебе сейчас предлагается?

Протарх. Делать нечего, надо принять — ведь красавец Филеб у нас отступился. 

Сократ. Значит, надо сделать все возможное, чтобы как-то добраться до истины в этом вопросе?

Протарх. Да, надо.

:::
:::
:::


_Тут какой-то комментарий к тексту._

## II. 11d-12b

::: columns
::: {.column width="35%"}
**ΣΩ.** Ἴθι δή, πρὸς τούτοις διομολογησώμεθα καὶ τόδε. 

**ΠΡΩ.** Τὸ ποῖον; 

**ΣΩ.** Ὡς νῦν ἡμῶν ἑκάτερος ἕξιν ψυχῆς καὶ διάθεσιν  ἀποφαίνειν τινὰ ἐπιχειρήσει τὴν δυναμένην ἀνθρώποις πᾶσι  τὸν βίον εὐδαίμονα παρέχειν. ἆρ' οὐχ οὕτως; 

**ΠΡΩ.** Οὕτω μὲν οὖν. 

**ΣΩ.** Οὐκοῦν ὑμεῖς μὲν τὴν τοῦ χαίρειν, ἡμεῖς δ' αὖ τὴν τοῦ φρονεῖν; 

**ΠΡΩ.** Ἔστι ταῦτα. 

**ΣΩ.** Τί δ' ἂν ἄλλη τις κρείττων τούτων φανῇ; μῶν οὐκ, ἂν μὲν ἡδονῇ μᾶλλον φαίνηται συγγενής, ἡττώμεθα μὲν ἀμφότεροι τοῦ ταῦτα ἔχοντος βεβαίως βίου, κρατεῖ δὲ ὁ τῆς ἡδονῆς τὸν τῆς φρονήσεως; 

**ΠΡΩ.** Ναί. 

**ΣΩ.** Ἂν δέ γε φρονήσει, νικᾷ μὲν φρόνησις τὴν ἡδονήν, ἡ δὲ ἡττᾶται; ταῦθ' οὕτως ὁμολογούμενά φατε, ἢ πῶς; 

**ΠΡΩ.** Ἐμοὶ γοῦν δοκεῖ. 

**ΣΩ.** Τί δὲ Φιλήβῳ; τί φῄς; 

**ΦΙ.** Ἐμοὶ μὲν πάντως νικᾶν ἡδονὴ δοκεῖ καὶ δόξει· σὺ δέ, Πρώταρχε, αὐτὸς γνώσῃ. 

**ΠΡΩ.** Παραδούς, ὦ Φίληβε, ἡμῖν τὸν λόγον οὐκ ἂν ἔτι κύριος εἴης τῆς πρὸς Σωκράτη ὁμολογίας ἢ καὶ τοὐναντίον. 

**ΦΙ.** Ἀληθῆ λέγεις· ἀλλὰ γὰρ ἀφοσιοῦμαι καὶ μαρτύρομαι νῦν αὐτὴν τὴν θεόν. 

**ΠΡΩ.** Καὶ ἡμεῖς σοι τούτων γε αὐτῶν συμμάρτυρες ἂν εἶμεν, ὡς ταῦτα ἔλεγες ἃ λέγεις. ἀλλὰ δὴ τὰ μετὰ ταῦτα ἑξῆς, ὦ Σώκρατες, ὅμως καὶ μετὰ Φιλήβου ἑκόντος ἢ ὅπως ἂν ἐθέλῃ πειρώμεθα περαίνειν.

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929


### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## III. 12c-13d

::: columns
::: {.column width="35%"}
**ΣΩ.** Πειρατέον, ἀπ' αὐτῆς δὴ τῆς θεοῦ, ἣν ὅδε Ἀφροδίτην μὲν λέγεσθαί φησι, τὸ δ' ἀληθέστατον αὐτῆς ὄνομα Ἡδονὴν εἶναι. 

**ΠΡΩ.** Ὀρθότατα. 

**ΣΩ.** Τὸ δ' ἐμὸν δέος, ὦ Πρώταρχε, ἀεὶ πρὸς τὰ τῶν θεῶν ὀνόματα οὐκ ἔστι κατ' ἄνθρωπον, ἀλλὰ πέρα τοῦ μεγίστου φόβου. καὶ νῦν τὴν μὲν Ἀφροδίτην, ὅπῃ ἐκείνῃ φίλον, ταύτῃ προσαγορεύω· τὴν δὲ ἡδονὴν οἶδα ὡς ἔστι ποικίλον, καὶ ὅπερ εἶπον, ἀπ' ἐκείνης ἡμᾶς ἀρχομένους ἐνθυμεῖσθαι δεῖ καὶ σκοπεῖν ἥντινα φύσιν ἔχει. ἔστι γάρ, ἀκούειν μὲν οὕτως ἁπλῶς, ἕν τι, μορφὰς δὲ δήπου παντοίας εἴληφε καί τινα τρόπον ἀνομοίους ἀλλήλαις. ἰδὲ γάρ· ἥδεσθαι μέν φαμεν τὸν ἀκολασταίνοντα ἄνθρωπον, ἥδεσθαι δὲ καὶ τὸν σωφρονοῦντα αὐτῷ τῷ σωφρονεῖν· ἥδεσθαι δ' αὖ καὶ τὸν ἀνοηταίνοντα καὶ ἀνοήτων δοξῶν καὶ ἐλπίδων μεστόν, ἥδεσθαι δ' αὖ τὸν φρονοῦντα αὐτῷ τῷ φρονεῖν· καὶ τούτων τῶν ἡδονῶν ἑκατέρας πῶς ἄν τις ὁμοίας ἀλλήλαις εἶναι λέγων οὐκ ἀνόητος φαίνοιτο ἐνδίκως; 

**ΠΡΩ.** Εἰσὶ μὲν γὰρ ἀπ' ἐναντίων, ὦ Σώκρατες, αὗται πραγμάτων, οὐ μὴν αὐταί γε ἀλλήλαις ἐναντίαι. πῶς γὰρ ἡδονῇ γε ἡδονὴ [μὴ] οὐχ ὁμοιότατον ἂν εἴη, τοῦτο αὐτὸ ἑαυτῷ, πάντων χρημάτων; 

**ΣΩ.** Καὶ γὰρ χρῶμα, ὦ δαιμόνιε, χρώματι· κατά γε αὐτὸ τοῦτο οὐδὲν διοίσει τὸ χρῶμα εἶναι πᾶν, τό γε μὴν μέλαν τῷ λευκῷ πάντες γιγνώσκομεν ὡς πρὸς τῷ διάφορον εἶναι καὶ ἐναντιώτατον ὂν τυγχάνει. καὶ δὴ καὶ σχῆμα σχήματι κατὰ ταὐτόν· γένει μέν ἐστι πᾶν ἕν, τὰ δὲ μέρη τοῖς μέρεσιν αὐτοῦ τὰ μὲν ἐναντιώτατα ἀλλήλοις, τὰ δὲ διαφορότητ' ἔχοντα μυρίαν που τυγχάνει, καὶ πολλὰ ἕτερα οὕτως ἔχονθ' εὑρήσομεν. ὥστε τούτῳ γε τῷ λόγῳ μὴ πίστευε, τῷ πάντα τὰ ἐναντιώτατα ἓν ποιοῦντι. φοβοῦμαι δὲ μή τινας ἡδονὰς ἡδοναῖς εὑρήσομεν ἐναντίας. 

 **ΠΡΩ.** Ἴσως· ἀλλὰ τί τοῦθ' ἡμῶν βλάψει τὸν λόγον; 

 **ΣΩ.** Ὅτι προσαγορεύεις αὐτὰ ἀνόμοια ὄντα ἑτέρῳ, φήσομεν, ὀνόματι· λέγεις γὰρ ἀγαθὰ πάντ' εἶναι τὰ ἡδέα. τὸ μὲν οὖν μὴ οὐχὶ ἡδέα εἶναι τὰ ἡδέα λόγος οὐδεὶς ἀμφισβητεῖ· κακὰ δ' ὄντα αὐτῶν τὰ πολλὰ καὶ ἀγαθὰ δέ, ὡς ἡμεῖς φαμέν, ὅμως πάντα σὺ προσαγορεύεις ἀγαθὰ αὐτά, ὁμολογῶν ἀνόμοια εἶναι, τῷ λόγῳ εἴ τίς σε προσαναγκάζοι. τί οὖν δὴ ταὐτὸν ἐν ταῖς κακαῖς ὁμοίως καὶ ἐν ἀγαθαῖς ἐνὸν πάσας ἡδονὰς ἀγαθὸν εἶναι προσαγορεύεις; 

**ΠΡΩ.** Πῶς λέγεις, ὦ Σώκρατες; οἴει γάρ τινα συγχωρήσεσθαι, θέμενον ἡδονὴν εἶναι τἀγαθόν, εἶτα ἀνέξεσθαί σου λέγοντος τὰς μὲν εἶναί τινας ἀγαθὰς ἡδονάς, τὰς δέ τινας ἑτέρας αὐτῶν κακάς; 

**ΣΩ.** Ἀλλ' οὖν ἀνομοίους γε φήσεις αὐτὰς ἀλλήλαις εἶναι καί τινας ἐναντίας. 

**ΠΡΩ.** Οὔτι καθ' ὅσον γε ἡδοναί. 

 **ΣΩ.** Πάλιν εἰς τὸν αὐτὸν φερόμεθα λόγον, ὦ Πρώταρχε, οὐδ' ἄρα ἡδονὴν ἡδονῆς διάφορον, ἀλλὰ πάσας ὁμοίας εἶναι φήσομεν, καὶ τὰ παραδείγματα ἡμᾶς τὰ νυνδὴ λεχθέντα οὐδὲν τιτρώσκει, πεισόμεθα δὲ καὶ ἐροῦμεν ἅπερ οἱ πάντων φαυλότατοί τε καὶ περὶ λόγους ἅμα νέοι. 

**ΠΡΩ.** Τὰ ποῖα δὴ λέγεις; 

**ΣΩ.** Ὅτι σε μιμούμενος ἐγὼ καὶ ἀμυνόμενος ἐὰν τολμῶ λέγειν ὡς τὸ ἀνομοιότατόν ἐστι τῷ ἀνομοιοτάτῳ πάντων ὁμοιότατον, ἕξω τὰ αὐτὰ σοὶ λέγειν, καὶ φανούμεθά γε νεώτεροι τοῦ δέοντος, καὶ ὁ λόγος ἡμῖν ἐκπεσὼν οἰχήσεται. πάλιν οὖν αὐτὸν ἀνακρουώμεθα, καὶ τάχ' ἂν ἰόντες εἰς τὰς ὁμοίας ἴσως ἄν πως ἀλλήλοις συγχωρήσαιμεν.

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## IV. 13e-14b

::: columns
::: {.column width="35%"}
**ΠΡΩ.** Λέγε πῶς; 

**ΣΩ.** Ἐμὲ θὲς ὑπὸ σοῦ πάλιν ἐρωτώμενον, ὦ Πρώταρχε. 

**ΠΡΩ.** Τὸ ποῖον δή; 

**ΣΩ.** Φρόνησίς τε καὶ ἐπιστήμη καὶ νοῦς καὶ πάνθ' ὁπόσα δὴ κατ' ἀρχὰς ἐγὼ θέμενος εἶπον ἀγαθά, διερωτώμενος ὅτι ποτ' ἐστὶν ἀγαθόν, ἆρ' οὐ ταὐτὸν πείσονται τοῦτο ὅπερ ὁ σὸς λόγος; 

**ΠΡΩ.** Πῶς; 

**ΣΩ.** Πολλαί τε αἱ συνάπασαι ἐπιστῆμαι δόξουσιν εἶναι καὶ ἀνόμοιοί τινες αὐτῶν ἀλλήλαις· εἰ δὲ καὶ ἐναντίαι πῃ γίγνονταί τινες, ἆρα ἄξιος ἂν εἴην τοῦ διαλέγεσθαι νῦν, εἰ φοβηθεὶς τοῦτο αὐτὸ μηδεμίαν ἀνόμοιον φαίην ἐπιστήμην ἐπιστήμῃ γίγνεσθαι, κἄπειθ' ἡμῖν οὕτως ὁ λόγος ὥσπερ μῦθος ἀπολόμενος οἴχοιτο, αὐτοὶ δὲ σῳζοίμεθα ἐπί τινος ἀλογίας; 

**ΠΡΩ.** Ἀλλ' οὐ μὴν δεῖ τοῦτο γενέσθαι, πλὴν τοῦ σωθῆναι. τό γε μήν μοι ἴσον τοῦ σοῦ τε καὶ ἐμοῦ λόγου ἀρέσκει· πολλαὶ μὲν ἡδοναὶ καὶ ἀνόμοιοι γιγνέσθων, πολλαὶ δὲ ἐπιστῆμαι καὶ διάφοροι. 

**ΣΩ.** Τὴν τοίνυν διαφορότητα, ὦ Πρώταρχε, [τοῦ ἀγαθοῦ] τοῦ τ' ἐμοῦ καὶ τοῦ σοῦ μὴ ἀποκρυπτόμενοι, κατατιθέντες δὲ εἰς τὸ μέσον, τολμῶμεν, ἄν πῃ ἐλεγχόμενοι μηνύσωσι πότερον ἡδονὴν τἀγαθὸν δεῖ λέγειν ἢ φρόνησιν ἤ τι τρίτον ἄλλο εἶναι. νῦν γὰρ οὐ δήπου πρός γε αὐτὸ τοῦτο φιλονικοῦμεν, ὅπως ἁγὼ τίθεμαι, ταῦτ' ἔσται τὰ νικῶντα, ἢ ταῦθ' ἃ σύ, τῷ δ' ἀληθεστάτῳ δεῖ που συμμαχεῖν ἡμᾶς ἄμφω.

**ΠΡΩ.** Δεῖ γὰρ οὖν.
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## V. 14c-15c

::: columns
::: {.column width="35%"}
**ΣΩ.** Τοῦτον τοίνυν τὸν λόγον ἔτι μᾶλλον δι' ὁμολογίας βεβαιωσώμεθα.

**ΠΡΩ.** Τὸν ποῖον δή; 

**ΣΩ.** Τὸν πᾶσι παρέχοντα ἀνθρώποις πράγματα ἑκοῦσί τε καὶ ἄκουσιν ἐνίοις καὶ ἐνίοτε. 

**ΠΡΩ.** Λέγε σαφέστερον. 

**ΣΩ.** Τὸν νυνδὴ παραπεσόντα λέγω, φύσει πως πεφυκότα θαυμαστόν. ἓν γὰρ δὴ τὰ πολλὰ εἶναι καὶ τὸ ἓν πολλὰ θαυμαστὸν λεχθέν, καὶ ῥᾴδιον ἀμφισβητῆσαι τῷ τούτων ὁποτερονοῦν τιθεμένῳ. 

**ΠΡΩ.** Ἆρ' οὖν λέγεις ὅταν τις ἐμὲ φῇ Πρώταρχον ἕνα γεγονότα φύσει πολλοὺς εἶναι πάλιν τοὺς ἐμὲ καὶ ἐναντίους ἀλλήλοις, μέγαν καὶ σμικρὸν τιθέμενος καὶ βαρὺν καὶ κοῦφον τὸν αὐτὸν καὶ ἄλλα μυρία; 

**ΣΩ.** Σὺ μέν, ὦ Πρώταρχε, εἴρηκας τὰ δεδημευμένα τῶν θαυμαστῶν περὶ τὸ ἓν καὶ πολλά, συγκεχωρημένα δὲ ὡς ἔπος εἰπεῖν ὑπὸ πάντων ἤδη μὴ δεῖν τῶν τοιούτων ἅπτεσθαι, παιδαριώδη καὶ ῥᾴδια καὶ σφόδρα τοῖς λόγοις ἐμπόδια ὑπολαμβανόντων γίγνεσθαι, ἐπεὶ μηδὲ τὰ τοιάδε, ὅταν τις ἑκάστου τὰ μέλη τε καὶ ἅμα μέρη διελὼν τῷ λόγῳ, πάντα ταῦτα τὸ ἓν ἐκεῖνο εἶναι διομολογησάμενος, ἐλέγχῃ καταγελῶν ὅτι τέρατα διηνάγκασται φάναι, τό τε ἓν ὡς πολλά ἐστι καὶ ἄπειρα, καὶ τὰ πολλὰ ὡς ἓν μόνον. 

**ΠΡΩ.** Σὺ δὲ δὴ ποῖα, ὦ Σώκρατες, ἕτερα λέγεις, ἃ μήπω συγκεχωρημένα δεδήμευται περὶ τὸν αὐτὸν τοῦτον λόγον; 

**ΣΩ.** Ὁπόταν, ὦ παῖ, τὸ ἓν μὴ τῶν γιγνομένων τε καὶ ἀπολλυμένων τις τιθῆται, καθάπερ ἀρτίως ἡμεῖς εἴπομεν. ἐνταυθοῖ μὲν γὰρ καὶ τὸ τοιοῦτον ἕν, ὅπερ εἴπομεν νυνδή, συγκεχώρηται τὸ μὴ δεῖν ἐλέγχειν· ὅταν δέ τις ἕνα ἄνθρωπον ἐπιχειρῇ τίθεσθαι καὶ βοῦν ἕνα καὶ τὸ καλὸν ἓν καὶ τὸ ἀγαθὸν ἕν, περὶ τούτων τῶν ἑνάδων καὶ τῶν τοιούτων ἡ πολλὴ σπουδὴ μετὰ διαιρέσεως ἀμφισβήτησις γίγνεται. 

**ΠΡΩ.** Πῶς; 

**ΣΩ.** Πρῶτον μὲν εἴ τινας δεῖ τοιαύτας εἶναι μονάδας ὑπολαμβάνειν ἀληθῶς οὔσας· εἶτα πῶς αὖ ταύτας, μίαν ἑκάστην οὖσαν ἀεὶ τὴν αὐτὴν καὶ μήτε γένεσιν μήτε ὄλεθρον προσδεχομένην, ὅμως εἶναι βεβαιότατα μίαν ταύτην; μετὰ δὲ τοῦτ' ἐν τοῖς γιγνομένοις αὖ καὶ ἀπείροις εἴτε διεσπασμένην καὶ πολλὰ γεγονυῖαν θετέον, εἴθ' ὅλην αὐτὴν αὑτῆς χωρίς, ὃ δὴ πάντων ἀδυνατώτατον φαίνοιτ' ἄν, ταὐτὸν καὶ ἓν ἅμα ἐν ἑνί τε καὶ πολλοῖς γίγνεσθαι. ταῦτ' ἔστι τὰ περὶ τὰ τοιαῦτα ἓν καὶ πολλά, ἀλλ' οὐκ ἐκεῖνα, ὦ Πρώταρχε, ἁπάσης ἀπορίας αἴτια μὴ καλῶς ὁμολογηθέντα καὶ εὐπορίας [ἂν] αὖ καλῶς. 

**ΠΡΩ.** Οὐκοῦν χρὴ τοῦθ' ἡμᾶς, ὦ Σώκρατες, ἐν τῷ νῦν πρῶτον διαπονήσασθαι; 

**ΣΩ.** Ὡς γοῦν ἐγὼ φαίην ἄν. 

**ΠΡΩ.** Καὶ πάντας τοίνυν ἡμᾶς ὑπόλαβε συγχωρεῖν σοι τούσδε τὰ τοιαῦτα· Φίληβον δ' ἴσως κράτιστον ἐν τῷ νῦν ἐπερωτῶντα μὴ κινεῖν εὖ κείμενον.

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## VI. 15d-17a

::: columns
::: {.column width="35%"}
**ΣΩ.** Εἶεν· πόθεν οὖν τις ταύτης ἄρξηται πολλῆς οὔσης καὶ παντοίας περὶ τὰ ἀμφισβητούμενα μάχης; ἆρ' ἐνθένδε; 

**ΠΡΩ.** Πόθεν; 

**ΣΩ.** Φαμέν που ταὐτὸν ἓν καὶ πολλὰ ὑπὸ λόγων γιγνόμενα περιτρέχειν πάντῃ καθ' ἕκαστον τῶν λεγομένων ἀεί, καὶ πάλαι καὶ νῦν. καὶ τοῦτο οὔτε μὴ παύσηταί ποτε οὔτε ἤρξατο νῦν, ἀλλ' ἔστι τὸ τοιοῦτον, ὡς ἐμοὶ φαίνεται, τῶν λόγων αὐτῶν ἀθάνατόν τι καὶ ἀγήρων πάθος ἐν ἡμῖν· ὁ δὲ πρῶτον αὐτοῦ γευσάμενος ἑκάστοτε τῶν νέων, ἡσθεὶς ὥς τινα σοφίας ηὑρηκὼς θησαυρόν, ὑφ' ἡδονῆς ἐνθουσιᾷ τε καὶ πάντα κινεῖ λόγον ἅσμενος, τοτὲ μὲν ἐπὶ θάτερα κυκλῶν καὶ συμφύρων εἰς ἕν, τοτὲ δὲ πάλιν ἀνειλίττων καὶ διαμερίζων, εἰς ἀπορίαν αὑτὸν μὲν πρῶτον καὶ μάλιστα καταβάλλων, δεύτερον δ' ἀεὶ τὸν ἐχόμενον, ἄντε νεώτερος ἄντε πρεσβύτερος ἄντε ἧλιξ ὢν τυγχάνῃ, φειδόμενος οὔτε πατρὸς οὔτε μητρὸς οὔτε ἄλλου τῶν ἀκουόντων οὐδενός, ὀλίγου δὲ καὶ τῶν ἄλλων ζῴων, οὐ μόνον τῶν ἀνθρώπων, ἐπεὶ βαρβάρων γε οὐδενὸς ἂν φείσαιτο, εἴπερ μόνον ἑρμηνέα ποθὲν ἔχοι. 

**ΠΡΩ.** Ἆρ', ὦ Σώκρατες, οὐχ ὁρᾷς ἡμῶν τὸ πλῆθος, ὅτι νέοι πάντες ἐσμέν, καὶ οὐ φοβῇ μή σοι μετὰ Φιλήβου συνεπιθώμεθα, ἐὰν ἡμᾶς λοιδορῇς; ὅμως δὲ μανθάνομεν γὰρ ὃ λέγεις, εἴ τις τρόπος ἔστι καὶ μηχανὴ τὴν μὲν τοιαύτην ταραχὴν ἡμῖν ἔξω τοῦ λόγου εὐμενῶς πως ἀπελθεῖν, ὁδὸν δέ τινα καλλίω ταύτης ἐπὶ τὸν λόγον ἀνευρεῖν, σύ τε προθυμοῦ τοῦτο καὶ ἡμεῖς συνακολουθήσομεν εἰς δύναμιν· οὐ γὰρ σμικρὸς ὁ παρὼν λόγος, ὦ Σώκρατες. 

**ΣΩ.** Οὐ γὰρ οὖν, ὦ παῖδες, ὥς φησιν ὑμᾶς προσαγορεύων Φίληβος. οὐ μὴν ἔστι καλλίων ὁδὸς οὐδ' ἂν γένοιτο ἧς ἐγὼ ἐραστὴς μέν εἰμι ἀεί, πολλάκις δέ με ἤδη διαφυγοῦσα ἔρημον καὶ ἄπορον κατέστησεν. 

**ΠΡΩ.** Τίς αὕτη; λεγέσθω μόνον. 

**ΣΩ.** Ἣν δηλῶσαι μὲν οὐ πάνυ χαλεπόν, χρῆσθαι δὲ παγχάλεπον· πάντα γὰρ ὅσα τέχνης ἐχόμενα ἀνηυρέθη πώποτε διὰ ταύτης φανερὰ γέγονε. σκόπει δὲ ἣν λέγω.  

**ΠΡΩ.** Λέγε μόνον. 

**ΣΩ.** Θεῶν μὲν εἰς ἀνθρώπους δόσις, ὥς γε καταφαίνεται ἐμοί, ποθὲν ἐκ θεῶν ἐρρίφη διά τινος Προμηθέως ἅμα φανοτάτῳ τινὶ πυρί· καὶ οἱ μὲν παλαιοί, κρείττονες ἡμῶν καὶ ἐγγυτέρω θεῶν οἰκοῦντες, ταύτην φήμην παρέδοσαν, ὡς ἐξ ἑνὸς μὲν καὶ πολλῶν ὄντων τῶν ἀεὶ λεγομένων εἶναι, πέρας δὲ καὶ ἀπειρίαν ἐν αὑτοῖς σύμφυτον ἐχόντων. δεῖν οὖν ἡμᾶς τούτων οὕτω διακεκοσμημένων ἀεὶ μίαν ἰδέαν περὶ παντὸς ἑκάστοτε θεμένους ζητεῖν – εὑρήσειν γὰρ ἐνοῦσαν –  ἐὰν οὖν μεταλάβωμεν, μετὰ μίαν δύο, εἴ πως εἰσί, σκοπεῖν, εἰ δὲ μή, τρεῖς ἤ τινα ἄλλον ἀριθμόν, καὶ τῶν ἓν ἐκείνων ἕκαστον πάλιν ὡσαύτως, μέχριπερ ἂν τὸ κατ' ἀρχὰς ἓν μὴ ὅτι ἓν καὶ πολλὰ καὶ ἄπειρά ἐστι μόνον ἴδῃ τις, ἀλλὰ καὶ ὁπόσα· τὴν δὲ τοῦ ἀπείρου ἰδέαν πρὸς τὸ πλῆθος μὴ προςφέρειν πρὶν ἄν τις τὸν ἀριθμὸν αὐτοῦ πάντα κατίδῃ τὸν μεταξὺ τοῦ ἀπείρου τε καὶ τοῦ ἑνός, τότε δ' ἤδη τὸ ἓν ἕκαστον τῶν πάντων εἰς τὸ ἄπειρον μεθέντα χαίρειν ἐᾶν. οἱ μὲν οὖν θεοί, ὅπερ εἶπον, οὕτως ἡμῖν παρέδοσαν σκοπεῖν καὶ μανθάνειν καὶ διδάσκειν ἀλλήλους· οἱ δὲ νῦν τῶν ἀνθρώπων σοφοὶ ἓν μέν, ὅπως ἂν τύχωσι, καὶ πολλὰ θᾶττον καὶ βραδύτερον ποιοῦσι τοῦ δέοντος, μετὰ δὲ τὸ ἓν ἄπειρα εὐθύς, τὰ δὲ μέσα αὐτοὺς ἐκφεύγει – οἷς διακεχώρισται τό τε διαλεκτικῶς πάλιν καὶ τὸ ἐριστικῶς ἡμᾶς ποιεῖσθαι πρὸς ἀλλήλους τοὺς λόγους.
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## VII. 17b-17e

::: columns
::: {.column width="35%"}
**ΠΡΩ.** Τὰ μέν πως, ὦ Σώκρατες, δοκῶ σου μανθάνειν, τὰ δὲ ἔτι σαφέστερον δέομαι ἃ λέγεις ἀκοῦσαι.

**ΣΩ.** Σαφὲς μήν, ὦ Πρώταρχε, ἐστὶν ἐν τοῖς γράμμασιν ὃ λέγω, καὶ λάμβαν' αὐτὸ ἐν τούτοις οἷσπερ καὶ πεπαίδευσαι.

**ΠΡΩ.** Πῶς;

**ΣΩ.** Φωνὴ μὲν ἡμῖν ἐστί που μία διὰ τοῦ στόματος ἰοῦσα, καὶ ἄπειρος αὖ πλήθει, πάντων τε καὶ ἑκάστου.

**ΠΡΩ.** Τί μήν;

**ΣΩ.** Καὶ οὐδὲν ἑτέρῳ γε τούτων ἐσμέν πω σοφοί, οὔτε ὅτι τὸ ἄπειρον αὐτῆς ἴσμεν οὔθ' ὅτι τὸ ἕν· ἀλλ' ὅτι πόσα τ' ἐστὶ καὶ ὁποῖα, τοῦτό ἐστι τὸ γραμματικὸν ἕκαστον ποιοῦν ἡμῶν.

**ΠΡΩ.** Ἀληθέστατα.

**ΣΩ.** Καὶ μὴν καὶ τὸ μουσικὸν ὃ τυγχάνει ποιοῦν, τοῦτ' ἔστι ταὐτόν.

**ΠΡΩ.** Πῶς;

**ΣΩ.** Φωνὴ μέν που καὶ τὸ κατ' ἐκείνην τὴν τέχνην ἐστὶ μία ἐν αὐτῇ.

**ΠΡΩ.** Πῶς δ' οὔ;

**ΣΩ.** Δύο δὲ θῶμεν βαρὺ καὶ ὀξύ, καὶ τρίτον ὁμότονον. ἢ πῶς;

**ΠΡΩ.** Οὕτως.

**ΣΩ.** Ἀλλ' οὔπω σοφὸς ἂν εἴης τὴν μουσικὴν εἰδὼς ταῦτα μόνα, μὴ δὲ εἰδὼς ὥς γ' ἔπος εἰπεῖν εἰς ταῦτα οὐδενὸς ἄξιος ἔσῃ. 

**ΠΡΩ.** Οὐ γὰρ οὖν.

**ΣΩ.** Ἀλλ', ὦ φίλε, ἐπειδὰν λάβῃς τὰ διαστήματα ὁπόσα ἐστὶ τὸν ἀριθμὸν τῆς φωνῆς ὀξύτητός τε πέρι καὶ βαρύτητος, καὶ ὁποῖα, καὶ τοὺς ὅρους τῶν διαστημάτων, καὶ τὰ ἐκ τούτων ὅσα συστήματα γέγονεν – ἃ κατιδόντες οἱ πρόσθεν παρέδοσαν ἡμῖν τοῖς ἑπομένοις ἐκείνοις καλεῖν αὐτὰ ἁρμονίας, ἔν τε ταῖς κινήσεσιν αὖ τοῦ σώματος ἕτερα τοιαῦτα ἐνόντα  πάθη γιγνόμενα, ἃ δὴ δι' ἀριθμῶν μετρηθέντα δεῖν αὖ φασι ῥυθμοὺς καὶ μέτρα ἐπονομάζειν, καὶ ἅμα ἐννοεῖν ὡς οὕτω δεῖ περὶ παντὸς ἑνὸς καὶ πολλῶν σκοπεῖν – ὅταν γὰρ αὐτά τε λάβῃς οὕτω, τότε ἐγένου σοφός, ὅταν τε ἄλλο τῶν ἓν ὁτιοῦν ταύτῃ σκοπούμενος ἕλῃς, οὕτως ἔμφρων περὶ τοῦτο γέγονας· τὸ δ' ἄπειρόν σε ἑκάστων καὶ ἐν ἑκάστοις πλῆθος ἄπειρον ἑκάστοτε ποιεῖ τοῦ φρονεῖν καὶ οὐκ ἐλλόγιμον οὐδ' ἐνάριθμον, ἅτ' οὐκ εἰς ἀριθμὸν οὐδένα ἐν οὐδενὶ πώποτε ἀπιδόντα.

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## VIII. 18a-18d

::: columns
::: {.column width="35%"}
**ΠΡΩ.** Κάλλιστα, ὦ Φίληβε, ἔμοιγε τὰ νῦν λεγόμενα εἰρηκέναι φαίνεται Σωκράτης. 

**ΦΙ.** Κἀμοὶ ταῦτά γε αὐτά· ἀλλὰ τί δή ποτε πρὸς ἡμᾶς ὁ λόγος οὗτος νῦν εἴρηται καὶ τί ποτε βουλόμενος; 

**ΣΩ.** Ὀρθῶς μέντοι τοῦθ' ἡμᾶς, ὦ Πρώταρχε, ἠρώτηκε Φίληβος. 

**ΠΡΩ.** Πάνυ μὲν οὖν, καὶ ἀποκρίνου γε αὐτῷ. 

**ΣΩ.** Δράσω ταῦτα διελθὼν σμικρὸν ἔτι περὶ αὐτῶν τούτων. ὥσπερ γὰρ ἓν ὁτιοῦν εἴ τίς ποτε λάβοι, τοῦτον, ὥς φαμεν, οὐκ ἐπ' ἀπείρου φύσιν δεῖ βλέπειν εὐθὺς ἀλλ' ἐπί τινα ἀριθμόν, οὕτω καὶ τὸ ἐναντίον ὅταν τις τὸ ἄπειρον ἀναγκασθῇ πρῶτον λαμβάνειν, μὴ ἐπὶ τὸ ἓν εὐθύς, ἀλλ' [ἐπ'] ἀριθμὸν αὖ τινα πλῆθος ἕκαστον ἔχοντά τι κατανοεῖν, τελευτᾶν τε ἐκ πάντων εἰς ἕν. πάλιν δὲ ἐν τοῖς γράμμασι τὸ νῦν λεγόμενον λάβωμεν. 

**ΠΡΩ.** Πῶς;

**ΣΩ.** Ἐπειδὴ φωνὴν ἄπειρον κατενόησεν εἴτε τις θεὸς εἴτε καὶ θεῖος ἄνθρωπος – ὡς λόγος ἐν Αἰγύπτῳ Θεῦθ τινα τοῦτον γενέσθαι λέγων, ὃς πρῶτος τὰ φωνήεντα ἐν τῷ ἀπείρῳ κατενόησεν οὐχ ἓν ὄντα ἀλλὰ πλείω, καὶ πάλιν ἕτερα φωνῆς μὲν οὔ, φθόγγου δὲ μετέχοντά τινος, ἀριθμὸν δέ τινα καὶ τούτων εἶναι, τρίτον δὲ εἶδος γραμμάτων διεστήσατο τὰ νῦν λεγόμενα ἄφωνα ἡμῖν· τὸ μετὰ τοῦτο διῄρει τά τε ἄφθογγα καὶ ἄφωνα μέχρι ἑνὸς ἑκάστου, καὶ τὰ φωνήεντα καὶ τὰ μέσα κατὰ τὸν αὐτὸν τρόπον, ἕως ἀριθμὸν αὐτῶν λαβὼν ἑνί τε ἑκάστῳ καὶ σύμπασι <στοιχεῖον> ἐπωνόμασε· καθορῶν δὲ ὡς οὐδεὶς ἡμῶν οὐδ' ἂν ἓν αὐτὸ καθ' αὑτὸ ἄνευ πάντων αὐτῶν μάθοι, τοῦτον τὸν δεσμὸν αὖ λογισάμενος ὡς ὄντα ἕνα καὶ πάντα ταῦτα ἕν πως ποιοῦντα μίαν ἐπ' αὐτοῖς ὡς οὖσαν γραμματικὴν τέχνην ἐπεφθέγξατο προσειπών. 

**ΦΙ.** Ταῦτ' ἔτι σαφέστερον ἐκείνων αὐτά γε πρὸς ἄλληλα, ὦ Πρώταρχε, ἔμαθον· τὸ δ' αὐτό μοι τοῦ λόγου νῦν τε καὶ σμικρὸν ἔμπροσθεν ἐλλείπεται. 

**ΣΩ.** Μῶν, ὦ Φίληβε, τὸ τί πρὸς ἔπος αὖ ταῦτ' ἐστίν; 

**ΦΙ.** Ναί, τοῦτ' ἔστιν ὃ πάλαι ζητοῦμεν ἐγώ τε καὶ Πρώταρχος.

**ΣΩ.** Ἦ μὴν ἐπ' αὐτῷ γε ἤδη γεγονότες ζητεῖτε, ὡς φῄς, πάλαι.

**ΦΙ.** Πῶς;
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## IX. 18e-20b

::: columns
::: {.column width="35%"}
**ΣΩ.** Ἆρ' οὐ περὶ φρονήσεως ἦν καὶ ἡδονῆς ἡμῖν ἐξ ἀρχῆς ὁ λόγος, ὁπότερον αὐτοῖν αἱρετέον; 

**ΦΙ.** Πῶς γὰρ οὔ;

**ΣΩ.** Καὶ μὴν ἕν γε ἑκάτερον αὐτοῖν εἶναί φαμεν.

**ΦΙ.** Πάνυ μὲν οὖν.

**ΣΩ.** Τοῦτ' αὐτὸ τοίνυν ἡμᾶς ὁ πρόσθεν λόγος ἀπαιτεῖ, πῶς ἔστιν ἓν καὶ πολλὰ αὐτῶν ἑκάτερον, καὶ πῶς μὴ ἄπειρα εὐθύς, ἀλλά τινά ποτε ἀριθμὸν ἑκάτερον ἔμπροσθεν κέκτηται τοῦ ἄπειρα αὐτῶν ἕκαστα γεγονέναι;

**ΠΡΩ.** Οὐκ εἰς φαῦλόν γε ἐρώτημα, ὦ Φίληβε, οὐκ οἶδ' ὅντινα τρόπον κύκλῳ πως περιαγαγὼν ἡμᾶς ἐμβέβληκε Σωκράτης. καὶ σκόπει δὴ πότερος ἡμῶν ἀποκρινεῖται τὸ νῦν ἐρωτώμενον. ἴσως δὴ γελοῖον τὸ ἐμὲ τοῦ λόγου διάδοχον παντελῶς ὑποστάντα διὰ τὸ μὴ δύνασθαι τὸ νῦν ἐρωτηθὲν ἀποκρίνασθαι σοὶ πάλιν τοῦτο προστάττειν· γελοιότερον δ' οἶμαι πολὺ τὸ μηδέτερον ἡμῶν δύνασθαι. σκόπει δὴ τί δράσομεν. εἴδη γάρ μοι δοκεῖ νῦν ἐρωτᾶν ἡδονῆς ἡμᾶς Σωκράτης εἴτε ἔστιν εἴτε μή, καὶ ὁπόσα ἐστὶ καὶ ὁποῖα· τῆς τ' αὖ φρονήσεως πέρι κατὰ ταὐτὰ ὡσαύτως.

**ΣΩ.** Ἀληθέστατα λέγεις, ὦ παῖ Καλλίου· μὴ γὰρ δυνάμενοι τοῦτο κατὰ παντὸς ἑνὸς καὶ ὁμοίου καὶ ταὐτοῦ δρᾶν καὶ τοῦ ἐναντίου, ὡς ὁ παρελθὼν λόγος ἐμήνυσεν, οὐδεὶς εἰς οὐδὲν οὐδενὸς ἂν ἡμῶν οὐδέποτε γένοιτο ἄξιος.

**ΠΡΩ.** Σχεδὸν ἔοικεν οὕτως, ὦ Σώκρατες, ἔχειν. ἀλλὰ καλὸν μὲν τὸ σύμπαντα γιγνώσκειν τῷ σώφρονι, δεύτερος δ' εἶναι πλοῦς δοκεῖ μὴ λανθάνειν αὐτὸν αὑτόν. τί δή μοι τοῦτο εἴρηται τὰ νῦν; ἐγώ σοι φράσω. σὺ τήνδε ἡμῖν τὴν συνουσίαν, ὦ Σώκρατες, ἐπέδωκας πᾶσι καὶ σεαυτὸν πρὸς τὸ διελέσθαι τί τῶν ἀνθρωπίνων κτημάτων ἄριστον. Φιλήβου γὰρ εἰπόντος ἡδονὴν καὶ τέρψιν καὶ χαρὰν καὶ πάνθ' ὁπόσα τοιαῦτ' ἐστί, σὺ πρὸς αὐτὰ ἀντεῖπες ὡς οὐ ταῦτα ἀλλ' ἐκεῖνά ἐστιν ἃ πολλάκις ἡμᾶς αὐτοὺς ἀναμιμνῄσκομεν ἑκόντες, ὀρθῶς δρῶντες, ἵν' ἐν μνήμῃ παρακείμενα ἑκάτερα βασανίζηται. φῂς δ', ὡς ἔοικε, σὺ τὸ προσρηθησόμενον ὀρθῶς ἄμεινον ἡδονῆς γε ἀγαθὸν εἶναι νοῦν, ἐπιστήμην, σύνεσιν, τέχνην καὶ πάντα αὖ τὰ τούτων συγγενῆ, <ἃ> κτᾶσθαι δεῖν ἀλλ' οὐχὶ ἐκεῖνα. τούτων δὴ μετ' ἀμφισβητήσεως ἑκατέρων λεχθέντων ἡμεῖς σοι μετὰ παιδιᾶς ἠπειλήσαμεν ὡς οὐκ ἀφήσομεν οἴκαδέ σε πρὶν ἂν τούτων τῶν λόγων πέρας ἱκανὸν γένηταί τι διορισθέντων, σὺ δὲ συνεχώρησας καὶ ἔδωκας εἰς ταῦθ' ἡμῖν σαυτόν, ἡμεῖς δὲ δὴ λέγομεν, καθάπερ οἱ παῖδες, ὅτι τῶν ὀρθῶς δοθέντων ἀφαίρεσις οὐκ ἔστι· παῦσαι δὴ τὸν τρόπον ἡμῖν ἀπαντῶν τοῦτον ἐπὶ τὰ νῦν λεγόμενα.

**ΣΩ.** Τίνα λέγεις;

**ΠΡΩ.** Εἰς ἀπορίαν ἐμβάλλων καὶ ἀνερωτῶν ὧν μὴ δυναίμεθ' ἂν ἱκανὴν ἀπόκρισιν ἐν τῷ παρόντι διδόναι σοι. μὴ γὰρ οἰώμεθα τέλος ἡμῖν εἶναι τῶν νῦν τὴν πάντων ἡμῶν ἀπορίαν, ἀλλ' εἰ δρᾶν τοῦθ' ἡμεῖς ἀδυνατοῦμεν, σοὶ δραστέον· ὑπέσχου γάρ. βουλεύου δὴ πρὸς ταῦτα αὐτὸς πότερον ἡδονῆς εἴδη σοι καὶ ἐπιστήμης διαιρετέον ἢ καὶ ἐατέον, εἴ πῃ καθ' ἕτερόν τινα τρόπον οἷός τ' εἶ καὶ βούλει δηλῶσαί πως ἄλλως τὰ νῦν ἀμφισβητούμενα παρ' ἡμῖν. 

**ΣΩ.** Δεινὸν μὲν τοίνυν ἔτι προσδοκᾶν οὐδὲν δεῖ τὸν ἐμέ, ἐπειδὴ τοῦθ' οὕτως εἶπες· τὸ γὰρ εἰ βούλει ῥηθὲν λύει πάντα φόβον ἑκάστων πέρι. πρὸς δὲ αὖ τοῖς μνήμην τινὰ δοκεῖ 
τίς μοι δεδωκέναι θεῶν ἡμῖν. 

**ΠΡΩ.** Πῶς δὴ καὶ τίνων;

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## X. 20c-21d

::: columns
::: {.column width="35%"}
**ΣΩ.** Λόγων ποτέ τινων πάλαι ἀκούσας ὄναρ ἢ καὶ ἐγρηγορὼς νῦν ἐννοῶ περί τε ἡδονῆς καὶ φρονήσεως, ὡς οὐδέτερον αὐτοῖν ἐστι τἀγαθόν, ἀλλὰ ἄλλο τι τρίτον, ἕτερον μὲν τούτων, ἄμεινον δὲ ἀμφοῖν. καίτοι τοῦτό γε ἂν ἐναργῶς ἡμῖν φανῇ νῦν, ἀπήλλακται μὲν ἡδονὴ τοῦ νικᾶν· τὸ γὰρ ἀγαθὸν οὐκ ἂν ἔτι ταὐτὸν αὐτῇ γίγνοιτο. ἢ πῶς; 

**ΠΡΩ.** Οὕτως. 

**ΣΩ.** Τῶν δέ γε εἰς τὴν διαίρεσιν εἰδῶν ἡδονῆς οὐδὲν ἔτι προσδεησόμεθα κατ' ἐμὴν δόξαν. προϊὸν δ' ἔτι σαφέστερον δείξει.

**ΠΡΩ.** Κάλλιστ' εἰπὼν οὕτω καὶ διαπέραινε. 

**ΣΩ.** Μίκρ' ἄττα τοίνυν ἔμπροσθεν ἔτι διομολογησώμεθα. 

**ΠΡΩ.** Τὰ ποῖα; 

**ΣΩ.** Τὴν τἀγαθοῦ μοῖραν πότερον ἀνάγκη τέλεον ἢ μὴ τέλεον εἶναι; 

**ΠΡΩ.** Πάντων δήπου τελεώτατον, ὦ Σώκρατες. 

**ΣΩ.** Τί δέ; ἱκανὸν τἀγαθόν; 

**ΠΡΩ.** Πῶς γὰρ οὔ; καὶ πάντων γε εἰς τοῦτο διαφέρειν τῶν ὄντων. 

**ΣΩ.** Τόδε γε μήν, ὡς οἶμαι, περὶ αὐτοῦ ἀναγκαιότατον εἶναι λέγειν, ὡς πᾶν τὸ γιγνῶσκον αὐτὸ θηρεύει καὶ ἐφίεται βουλόμενον ἑλεῖν καὶ περὶ αὑτὸ κτήσασθαι, καὶ τῶν ἄλλων οὐδὲν φροντίζει πλὴν τῶν ἀποτελουμένων ἅμα ἀγαθοῖς. 

**ΠΡΩ.** Οὐκ ἔστι τούτοις ἀντειπεῖν.

**ΣΩ.** Σκοπῶμεν δὴ καὶ κρίνωμεν τόν τε ἡδονῆς καὶ τὸν φρονήσεως βίον ἰδόντες χωρίς. 

**ΠΡΩ.** Πῶς εἶπες; 

**ΣΩ.** Μήτε ἐν τῷ τῆς ἡδονῆς ἐνέστω φρόνησις μήτ' ἐν τῷ τῆς φρονήσεως ἡδονή. δεῖ γάρ, εἴπερ πότερον αὐτῶν ἔστ' ἀγαθόν, μηδὲν μηδενὸς ἔτι προσδεῖσθαι· δεόμενον δ' ἂν φανῇ πότερον, οὐκ ἔστι που τοῦτ' ἔτι τὸ ὄντως ἡμῖν ἀγαθόν. 

**ΠΡΩ.** Πῶς γὰρ ἄν;

**ΣΩ.** Οὐκοῦν ἐν σοὶ πειρώμεθα βασανίζοντες ταῦτα; 

**ΠΡΩ.** Πάνυ μὲν οὖν. 

**ΣΩ.** Ἀποκρίνου δή. 

**ΠΡΩ.** Λέγε. 
**ΣΩ.** Δέξαι' ἄν, Πρώταρχε, σὺ ζῆν τὸν βίον ἅπαντα ἡδόμενος ἡδονὰς τὰς μεγίστας;

**ΠΡΩ.** Τί δ' οὔ; 

**ΣΩ.** Ἆρ' οὖν ἔτι τινὸς ἄν σοι προσδεῖν ἡγοῖο, εἰ τοῦτ' ἔχεις παντελῶς; 

**ΠΡΩ.** Οὐδαμῶς. 

**ΣΩ.** Ὅρα δή, τοῦ φρονεῖν καὶ τοῦ νοεῖν καὶ λογίζεσθαι τὰ δέοντα καὶ ὅσα τούτων ἀδελφά, μῶν μὴ δέοι' ἄν τι; 

**ΠΡΩ.** Καὶ τί; πάντα γὰρ ἔχοιμ' ἄν που τὸ χαίρειν ἔχων. 

**ΣΩ.** Οὐκοῦν οὕτω ζῶν ἀεὶ μὲν διὰ βίου ταῖς μεγίσταις ἡδοναῖς χαίροις ἄν; 

**ΠΡΩ.** Τί δ' οὔ; 

**ΣΩ.** Νοῦν δέ γε καὶ μνήμην καὶ ἐπιστήμην καὶ δόξαν μὴ κεκτημένος ἀληθῆ, πρῶτον μὲν τοῦτο αὐτό, εἰ χαίρεις ἢ μὴ χαίρεις, ἀνάγκη δήπου σε ἀγνοεῖν, κενόν γε ὄντα πάσης φρονήσεως; 

**ΠΡΩ.** Ἀνάγκη. 

**ΣΩ.** Καὶ μὴν ὡσαύτως μνήμην μὴ κεκτημένον ἀνάγκη δήπου μηδ' ὅτι ποτὲ ἔχαιρες μεμνῆσθαι, τῆς τ' ἐν τῷ παραχρῆμα ἡδονῆς προσπιπτούσης μηδ' ἡντινοῦν μνήμην ὑπομένειν· δόξαν δ' αὖ μὴ κεκτημένον ἀληθῆ μὴ δοξάζειν χαίρειν χαίροντα, λογισμοῦ δὲ στερόμενον μηδ' εἰς τὸν ἔπειτα χρόνον ὡς χαιρήσεις δυνατὸν εἶναι λογίζεσθαι, ζῆν δὲ οὐκ ἀνθρώπου βίον, ἀλλά τινος πλεύμονος ἢ τῶν ὅσα θαλάττια μετ' ὀστρεΐνων ἔμψυχά ἐστι σωμάτων. ἔστι ταῦτα, ἢ παρὰ ταῦτα ἔχομεν ἄλλα διανοηθῆναι; 

**ΠΡΩ.** Καὶ πῶς; 

**ΣΩ.** Ἆρ' οὖν αἱρετὸς ἡμῖν βίος ὁ τοιοῦτος; 

**ΠΡΩ.** Εἰς ἀφασίαν παντάπασί με, ὦ Σώκρατες, οὗτος ὁ λόγος ἐμβέβληκε τὰ νῦν.

**ΣΩ.** Μήπω τοίνυν μαλθακιζώμεθα, τὸν δὲ τοῦ νοῦ μεταλαβόντες αὖ βίον ἴδωμεν.

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XI. 21e-23b

::: columns
::: {.column width="35%"}
**ΠΡΩ.** Τὸν ποῖον δὴ λέγεις; 

**ΣΩ.** Εἴ τις δέξαιτ' ἂν αὖ ζῆν ἡμῶν φρόνησιν μὲν καὶ νοῦν καὶ ἐπιστήμην καὶ μνήμην πᾶσαν πάντων κεκτημένος, ἡδονῆς δὲ μετέχων μήτε μέγα μήτε σμικρόν, μηδ' αὖ λύπης, ἀλλὰ τὸ παράπαν ἀπαθὴς πάντων τῶν τοιούτων. 

**ΠΡΩ.** Οὐδέτερος ὁ βίος, ὦ Σώκρατες, ἔμοιγε τούτων αἱρετός, οὐδ' ἄλλῳ μή ποτε, ὡς ἐγᾦμαι, φανῇ. 

**ΣΩ.** Τί δ' ὁ συναμφότερος, ὦ Πρώταρχε, ἐξ ἀμφοῖν συμμειχθεὶς κοινὸς γενόμενος; 

**ΠΡΩ.** Ἡδονῆς λέγεις καὶ νοῦ καὶ φρονήσεως;

**ΣΩ.** Οὕτω καὶ τῶν τοιούτων [λέγω] ἔγωγε. 

**ΠΡΩ.** Πᾶς δήπου τοῦτόν γε αἱρήσεται πρότερον ἢ 'κείνων ὁποτερονοῦν, καὶ πρὸς τούτοις [γε] οὐχ ὁ μέν, ὁ δ' οὔ.

**ΣΩ.** Μανθάνομεν οὖν ὅτι νῦν ἡμῖν ἐστι τὸ συμβαῖνον ἐν τοῖς παροῦσι λόγοις; 

**ΠΡΩ.** Πάνυ μὲν οὖν, ὅτι γε τρεῖς μὲν βίοι προυτέθησαν, τοῖν δυοῖν δ' οὐδέτερος ἱκανὸς οὐδὲ αἱρετὸς οὔτε ἀνθρώπων οὔτε ζῴων οὐδενί. 

**ΣΩ.** Μῶν οὖν οὐκ ἤδη τούτων γε πέρι δῆλον ὡς οὐδέτερος αὐτοῖν εἶχε τἀγαθόν; ἦν γὰρ ἂν ἱκανὸς καὶ τέλεος καὶ πᾶσι φυτοῖς καὶ ζῴοις αἱρετός, οἷσπερ δυνατὸν ἦν οὕτως ἀεὶ διὰ βίου ζῆν· εἰ δέ τις ἄλλα ᾑρεῖθ' ἡμῶν, παρὰ φύσιν ἂν τὴν τοῦ ἀληθῶς αἱρετοῦ ἐλάμβανεν ἄκων ἐξ ἀγνοίας ἤ τινος ἀνάγκης οὐκ εὐδαίμονος. 

**ΠΡΩ.** Ἔοικε γοῦν ταῦθ' οὕτως ἔχειν. 

**ΣΩ.** Ὡς μὲν τοίνυν τήν γε Φιλήβου θεὸν οὐ δεῖ διανοεῖσθαι ταὐτὸν καὶ τἀγαθόν, ἱκανῶς εἰρῆσθαί μοι δοκεῖ. 

**ΦΙ.** Οὐδὲ γὰρ ὁ σὸς νοῦς, ὦ Σώκρατες, ἔστι τἀγαθόν, ἀλλ' ἕξει που ταὐτὰ ἐγκλήματα. 

**ΣΩ.** Τάχ' ἄν, ὦ Φίληβε, ὅ γ' ἐμός· οὐ μέντοι τόν γε ἀληθινὸν ἅμα καὶ θεῖον οἶμαι νοῦν, ἀλλ' ἄλλως πως ἔχειν. τῶν μὲν οὖν νικητηρίων πρὸς τὸν κοινὸν βίον οὐκ ἀμφισβητῶ πω ὑπὲρ νοῦ, τῶν δὲ δὴ δευτερείων ὁρᾶν καὶ σκοπεῖν χρὴ πέρι τί δράσομεν· τάχα γὰρ ἂν τοῦ κοινοῦ τούτου βίου αἰτιῴμεθ' ἂν ἑκάτερος ὁ μὲν τὸν νοῦν αἴτιον, ὁ δ' ἡδονὴν εἶναι, καὶ οὕτω τὸ μὲν ἀγαθὸν τούτων ἀμφοτέρων οὐδέτερον ἂν εἴη, τάχα δ' ἂν αἴτιόν τις ὑπολάβοι πότερον αὐτῶν εἶναι. τούτου δὴ πέρι καὶ μᾶλλον ἔτι πρὸς Φίληβον διαμαχοίμην ἂν ὡς ἐν τῷ μεικτῷ τούτῳ βίῳ, ὅτι ποτ' ἔστι τοῦτο ὃ λαβὼν ὁ βίος οὗτος γέγονεν αἱρετὸς ἅμα καὶ ἀγαθός, οὐχ ἡδονὴ ἀλλὰ νοῦς τούτῳ συγγενέστερον καὶ ὁμοιότερόν ἐστι, καὶ κατὰ τοῦτον τὸν λόγον οὔτ' ἂν τῶν πρωτείων οὐδ' αὖ τῶν δευτερείων ἡδονῇ μετὸν ἀληθῶς ἄν ποτε λέγοιτο· πορρωτέρω δ' ἐστὶ τῶν τριτείων, εἴ τι τῷ ἐμῷ νῷ δεῖ πιστεύειν ἡμᾶς τὰ νῦν. 

**ΠΡΩ.** Ἀλλὰ μήν, ὦ Σώκρατες, ἔμοιγε δοκεῖ νῦν μὲν ἡδονή σοι πεπτωκέναι καθαπερεὶ πληγεῖσα ὑπὸ τῶν νυνδὴ λόγων· τῶν γὰρ νικητηρίων πέρι μαχομένη κεῖται. τὸν δὲ νοῦν, ὡς ἔοικε, λεκτέον ὡς ἐμφρόνως οὐκ ἀντεποιεῖτο τῶν νικητηρίων· τὰ γὰρ αὔτ' ἔπαθεν ἄν. τῶν δὲ δὴ δευτερείων στερηθεῖσα ἡδονὴ παντάπασιν ἄν τινα καὶ ἀτιμίαν σχοίη πρὸς τῶν αὑτῆς ἐραστῶν· οὐδὲ γὰρ ἐκείνοις ἔτ' ἂν ὁμοίως φαίνοιτο καλή. 

**ΣΩ.** Τί οὖν; οὐκ ἄμεινον αὐτὴν ἐᾶν ἤδη καὶ μὴ τὴν ἀκριβεστάτην αὐτῇ προσφέροντα βάσανον καὶ ἐξελέγχοντα λυπεῖν; 

**ΠΡΩ.** Οὐδὲν λέγεις, ὦ Σώκρατες. 

**ΣΩ.** Ἆρ' ὅτι τὸ ἀδύνατον εἶπον, λυπεῖν ἡδονήν; 

**ΠΡΩ.** Οὐ μόνον γε ἀλλ' ὅτι καὶ ἀγνοεῖς ὡς οὐδείς πώ σε ἡμῶν μεθήσει πρὶν ἂν εἰς τέλος ἐπεξέλθῃς τούτων τῷ λόγῳ. 

**ΣΩ.** Βαβαῖ ἄρα, ὦ Πρώταρχε, συχνοῦ μὲν λόγου τοῦ λοιποῦ, σχεδὸν δὲ οὐδὲ ῥᾳδίου πάνυ τι νῦν. καὶ γὰρ δὴ φαίνεται δεῖν ἄλλης μηχανῆς, ἐπὶ τὰ δευτερεῖα ὑπὲρ νοῦ πορευόμενον οἷον βέλη ἔχειν ἕτερα τῶν ἔμπροσθεν λόγων· ἔστι δὲ ἴσως ἔνια καὶ ταὐτά. οὐκοῦν χρή; 

**ΠΡΩ.** Πῶς γὰρ οὔ;

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XII.23c-25a

::: columns
::: {.column width="35%"}
**ΣΩ.** Τὴν δέ γε ἀρχὴν αὐτοῦ διευλαβεῖσθαι πειρώμεθα τιθέμενοι. 

**ΠΡΩ.** Ποίαν δὴ λέγεις; 

**ΣΩ.** Πάντα τὰ νῦν ὄντα ἐν τῷ παντὶ διχῇ διαλάβωμεν, μᾶλλον δ', εἰ βούλει, τριχῇ. 

**ΠΡΩ.** Καθ' ὅτι, φράζοις ἄν; 

**ΣΩ.** Λάβωμεν ἄττα τῶν νυνδὴ λόγων.

**ΠΡΩ.** Ποῖα; 

**ΣΩ.** Τὸν θεὸν ἐλέγομέν που τὸ μὲν ἄπειρον δεῖξαι τῶν ὄντων, τὸ δὲ πέρας; 

**ΠΡΩ.** Πάνυ μὲν οὖν.

**ΣΩ.** Τούτω δὴ τῶν εἰδῶν τὰ δύο τιθώμεθα, τὸ δὲ τρίτον ἐξ ἀμφοῖν τούτοιν ἕν τι συμμισγόμενον. εἰμὶ δ', ὡς ἔοικεν, ἐγὼ γελοῖός τις ἄνθρωπος κατ' εἴδη διιστὰς καὶ συναριθμούμενος.

**ΠΡΩ.** Τί φῄς, ὠγαθέ; 

**ΣΩ.** Τετάρτου μοι γένους αὖ προσδεῖν φαίνεται.

**ΠΡΩ.** Λέγε τίνος. 

**ΣΩ.** Τῆς συμμείξεως τούτων πρὸς ἄλληλα τὴν αἰτίαν ὅρα,  καὶ τίθει μοι πρὸς τρισὶν ἐκείνοις τέταρτον τοῦτο.

**ΠΡΩ.** Μῶν οὖν σοι καὶ πέμπτου προσδεήσει διάκρισίν τινος δυναμένου; 

**ΣΩ.** Τάχ' ἄν· οὐ μὴν οἶμαί γε ἐν τῷ νῦν· ἂν δέ τι δέῃ, συγγνώσῃ πού μοι σὺ μεταδιώκοντι πέμπτον [βίον]. 

**ΠΡΩ.** Τί μήν; 

**ΣΩ.** Πρῶτον μὲν δὴ τῶν τεττάρων τὰ τρία διελόμενοι, τὰ δύο τούτων πειρώμεθα, πολλὰ ἑκάτερον ἐσχισμένον καὶ διεσπασμένον ἰδόντες, εἰς ἓν πάλιν ἑκάτερον συναγαγόντες, νοῆσαι πῇ ποτε ἦν αὐτῶν ἓν καὶ πολλὰ ἑκάτερον. 

**ΠΡΩ.** Εἴ μοι σαφέστερον ἔτι περὶ αὐτῶν εἴποις, τάχ' ἂν ἑποίμην. 

**ΣΩ.** Λέγω τοίνυν τὰ δύο ἃ προτίθεμαι ταὔτ' εἶναι ἅπερ νυνδή, τὸ μὲν ἄπειρον, τὸ δὲ πέρας ἔχον· ὅτι δὲ τρόπον τινὰ τὸ ἄπειρον πόλλ' ἐστί, πειράσομαι φράζειν. τὸ δὲ πέρας ἔχον ἡμᾶς περιμενέτω. 

**ΠΡΩ.** Μένει. 
**ΣΩ.** Σκέψαι δή. χαλεπὸν μὲν γὰρ καὶ ἀμφισβητήσιμον ὃ κελεύω σε σκοπεῖν, ὅμως δὲ σκόπει. θερμοτέρου καὶ ψυχροτέρου πέρι πρῶτον ὅρα πέρας εἴ ποτέ τι νοήσαις ἄν, ἢ τὸ μᾶλλόν τε καὶ ἧττον ἐν αὐτοῖς οἰκοῦν<τε> τοῖς γένεσιν, ἕωσπερ ἂν ἐνοικῆτον, τέλος οὐκ ἂν ἐπιτρεψαίτην γίγνεσθαι· γενομένης γὰρ τελευτῆς καὶ αὐτὼ τετελευτήκατον. 

**ΠΡΩ.** Ἀληθέστατα λέγεις. 

**ΣΩ.** Ἀεὶ δέ γε, φαμέν, ἔν τε τῷ θερμοτέρῳ καὶ ψυχροτέρῳ τὸ μᾶλλόν τε καὶ ἧττον ἔνι. 

**ΠΡΩ.** Καὶ μάλα. 

**ΣΩ.** Ἀεὶ τοίνυν ὁ λόγος ἡμῖν σημαίνει τούτω μὴ τέλος ἔχειν· ἀτελῆ δ' ὄντε δήπου παντάπασιν ἀπείρω γίγνεσθον. 

**ΠΡΩ.** Καὶ σφόδρα γε, ὦ Σώκρατες. 

**ΣΩ.** Ἀλλ' εὖ γε, ὦ φίλε Πρώταρχε, ὑπέλαβες καὶ ἀνέμνησας ὅτι καὶ τὸ σφόδρα τοῦτο, ὃ σὺ νῦν ἐφθέγξω, καὶ τό γε ἠρέμα τὴν αὐτὴν δύναμιν ἔχετον τῷ μᾶλλόν τε καὶ ἧττον· ὅπου γὰρ ἂν ἐνῆτον, οὐκ ἐᾶτον εἶναι ποσὸν ἕκαστον, ἀλλ' ἀεὶ σφοδρότερον ἡσυχαιτέρου καὶ τοὐναντίον ἑκάσταις πράξεσιν ἐμποιοῦντε τὸ πλέον καὶ τὸ ἔλαττον ἀπεργάζεσθον, τὸ δὲ ποσὸν ἀφανίζετον. ὃ γὰρ ἐλέχθη νυνδή, μὴ ἀφανίσαντε τὸ ποσόν, ἀλλ' ἐάσαντε αὐτό τε καὶ τὸ μέτριον ἐν τῇ τοῦ μᾶλλον καὶ ἧττον καὶ σφόδρα καὶ ἠρέμα ἕδρᾳ ἐγγενέσθαι, αὐτὰ ἔρρει ταῦτα ἐκ τῆς αὑτῶν χώρας ἐν ᾗ ἐνῆν. οὐ γὰρ ἔτι θερμότερον οὐδὲ ψυχρότερον εἴτην ἂν λαβόντε τὸ ποσόν· προχωρεῖ γὰρ καὶ οὐ μένει τό τε θερμότερον ἀεὶ καὶ τὸ ψυχρότερον ὡσαύτως, τὸ δὲ ποσὸν ἔστη καὶ προϊὸν ἐπαύσατο. κατὰ δὴ τοῦτον τὸν λόγον ἄπειρον γίγνοιτ' ἂν τὸ θερμότερον καὶ τοὐναντίον ἅμα. 

**ΠΡΩ.** Φαίνεται γοῦν, ὦ Σώκρατες· ἔστι δ', ὅπερ εἶπες, οὐ ῥᾴδια ταῦτα συνέπεσθαι. τὸ δὲ εἰς αὖθίς τε καὶ αὖθις ἴσως λεχθέντα τόν τε ἐρωτῶντα καὶ τὸν ἐρωτώμενον ἱκανῶς ἂν συμφωνοῦντας ἀποφήναιεν.

**ΣΩ.** Ἀλλ' εὖ μὲν λέγεις καὶ πειρατέον οὕτω ποιεῖν. νῦν μέντοι ἄθρει τῆς τοῦ ἀπείρου φύσεως εἰ τοῦτο δεξόμεθα σημεῖον, ἵνα μὴ πάντ' ἐπεξιόντες μηκύνωμεν.

**ΠΡΩ.** Τὸ ποῖον δὴ λέγεις;

**ΣΩ.** Ὁπόσ' ἂν ἡμῖν φαίνηται μᾶλλόν τε καὶ ἧττον γιγνόμενα καὶ τὸ σφόδρα καὶ ἠρέμα δεχόμενα καὶ τὸ λίαν καὶ ὅσα τοιαῦτα πάντα, εἰς τὸ τοῦ ἀπείρου γένος ὡς εἰς ἓν δεῖ πάντα ταῦτα τιθέναι, κατὰ τὸν ἔμπροσθεν λόγον ὃν ἔφαμεν ὅσα διέσπασται καὶ διέσχισται συναγαγόντας χρῆναι κατὰ δύναμιν μίαν ἐπισημαίνεσθαί τινα φύσιν, εἰ μέμνησαι. 

**ΠΡΩ.** Μέμνημαι.

**ΣΩ.** Οὐκοῦν τὰ μὴ δεχόμενα ταῦτα, τούτων δὲ τὰ ἐναντία πάντα δεχόμενα, πρῶτον μὲν τὸ ἴσον καὶ ἰσότητα, μετὰ δὲ τὸ ἴσον τὸ διπλάσιον καὶ πᾶν ὅτιπερ ἂν πρὸς ἀριθμὸν ἀριθμὸς ἢ μέτρον ᾖ πρὸς μέτρον, ταῦτα σύμπαντα εἰς τὸ πέρας ἀπολογιζόμενοι καλῶς ἂν δοκοῖμεν δρᾶν τοῦτο. ἢ πῶς σὺ φῄς; 

**ΠΡΩ.** Κάλλιστά γε, ὦ Σώκρατες.

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XIII. 25b-26d

::: columns
::: {.column width="35%"}
**ΣΩ.** Εἶεν· τὸ δὲ τρίτον τὸ μεικτὸν ἐκ τούτοιν ἀμφοῖν τίνα ἰδέαν φήσομεν ἔχειν; 

**ΠΡΩ.** Σὺ καὶ ἐμοὶ φράσεις, ὡς οἶμαι. 

**ΣΩ.** Θεὸς μὲν οὖν, ἄνπερ γε ἐμαῖς εὐχαῖς ἐπήκοος γίγνηταί τις θεῶν. 

**ΠΡΩ.** Εὔχου δὴ καὶ σκόπει. 

**ΣΩ.** Σκοπῶ· καί μοι δοκεῖ τις, ὦ Πρώταρχε, αὐτῶν φίλος ἡμῖν νυνδὴ γεγονέναι. 

**ΠΡΩ.** Πῶς λέγεις τοῦτο καὶ τίνι τεκμηρίῳ χρῇ;

**ΣΩ.** Φράσω δῆλον ὅτι· σὺ δέ μοι συνακολούθησον τῷ λόγῳ. 

**ΠΡΩ.** Λέγε μόνον. 

**ΣΩ.** Θερμότερον ἐφθεγγόμεθα νυνδή πού τι καὶ ψυχρότερον. ἦ γάρ; 

**ΠΡΩ.** Ναί.

**ΣΩ.** Πρόσθες δὴ ξηρότερον καὶ ὑγρότερον αὐτοῖς καὶ πλέον καὶ ἔλαττον καὶ θᾶττον καὶ βραδύτερον καὶ μεῖζον καὶ σμικρότερον καὶ ὁπόσα ἐν τῷ πρόσθεν τῆς τὸ μᾶλλόν τε καὶ ἧττον δεχομένης ἐτίθεμεν εἰς ἓν φύσεως. 

**ΠΡΩ.** Τῆς τοῦ ἀπείρου λέγεις;

**ΣΩ.** Ναί. συμμείγνυ δέ γε εἰς αὐτὴν τὸ μετὰ ταῦτα τὴν αὖ τοῦ πέρατος γένναν. 

**ΠΡΩ.** Ποίαν; 

**ΣΩ.** Ἣν καὶ νυνδή, δέον ἡμᾶς καθάπερ τὴν τοῦ ἀπείρου συνηγάγομεν εἰς ἕν, οὕτω καὶ τὴν τοῦ περατοειδοῦς συναγαγεῖν, οὐ συνηγάγομεν. ἀλλ' ἴσως καὶ νῦν ταὐτὸν δράσει, <εἰ> τούτων ἀμφοτέρων συναγομένων καταφανὴς κἀκείνη γενήσεται. 

**ΠΡΩ.** Ποίαν καὶ πῶς λέγεις; 

**ΣΩ.** Τὴν τοῦ ἴσου καὶ διπλασίου, καὶ ὁπόση παύει πρὸς ἄλληλα τἀναντία διαφόρως ἔχοντα, σύμμετρα δὲ καὶ σύμφωνα ἐνθεῖσα ἀριθμὸν ἀπεργάζεται. 

**ΠΡΩ.** Μανθάνω· φαίνῃ γάρ μοι λέγειν μειγνὺς ταῦτα γενέσεις τινὰς ἐφ' ἑκάστων αὐτῶν συμβαίνειν.

**ΣΩ.** Ὀρθῶς γὰρ φαίνομαι. 

**ΠΡΩ.** Λέγε τοίνυν. 

**ΣΩ.** Ἆρα οὐκ ἐν μὲν νόσοις ἡ τούτων ὀρθὴ κοινωνία τὴν ὑγιείας φύσιν ἐγέννησεν; 

**ΠΡΩ.** Παντάπασι μὲν οὖν.

**ΣΩ.** Ἐν δὲ ὀξεῖ καὶ βαρεῖ καὶ ταχεῖ καὶ βραδεῖ, ἀπείροις οὖσιν, ἆρ' οὐ ταὐτὰ [ἐγγιγνόμενα] ταῦτα· ἅμα πέρας τε ἀπηργάσατο καὶ μουσικὴν σύμπασαν τελεώτατα συνεστήσατο;

**ΠΡΩ.** Κάλλιστά γε.

**ΣΩ.** Καὶ μὴν ἔν γε χειμῶσιν καὶ πνίγεσιν ἐγγενομένη τὸ μὲν πολὺ λίαν καὶ ἄπειρον ἀφείλετο, τὸ δὲ ἔμμετρον καὶ ἅμα σύμμετρον ἀπηργάσατο.

**ΠΡΩ.** Τί μήν; 

**ΣΩ.** Οὐκοῦν ἐκ τούτων ὧραί τε καὶ ὅσα καλὰ πάντα ἡμῖν γέγονε, τῶν τε ἀπείρων καὶ τῶν πέρας ἐχόντων συμμειχθέντων; 

**ΠΡΩ.** Πῶς δ' οὔ; 

**ΣΩ.** Καὶ ἄλλα γε δὴ μυρία ἐπιλείπω λέγων, οἷον μεθ' ὑγιείας κάλλος καὶ ἰσχύν, καὶ ἐν ψυχαῖς αὖ πάμπολλα ἕτερα καὶ πάγκαλα. ὕβριν γάρ που καὶ σύμπασαν πάντων πονηρίαν αὕτη κατιδοῦσα ἡ θεός, ὦ καλὲ Φίληβε, πέρας οὔτε ἡδονῶν οὐδὲν οὔτε πλησμονῶν ἐνὸν ἐν αὐτοῖς, νόμον καὶ τάξιν πέρας ἔχοντ' ἔθετο· καὶ σὺ μὲν ἀποκναῖσαι φῂς αὐτήν, ἐγὼ δὲ τοὐναντίον ἀποσῶσαι λέγω. σοὶ δέ, ὦ Πρώταρχε, πῶς φαίνεται; 

**ΠΡΩ.** Καὶ μάλα, ὦ Σώκρατες, ἔμοιγε κατὰ νοῦν. 

**ΣΩ.** Οὐκοῦν τὰ μὲν δὴ τρία ταῦτα εἴρηκα, εἰ συννοεῖς.

**ΠΡΩ.** Ἀλλ' οἶμαι κατανοεῖν· ἓν μὲν γάρ μοι δοκεῖς τὸ ἄπειρον λέγειν, ἓν δὲ καὶ δεύτερον τὸ πέρας ἐν τοῖς οὖσι· τρίτον δὲ οὐ σφόδρα κατέχω τί βούλει φράζειν. 

**ΣΩ.** Τὸ γὰρ πλῆθός σε, ὦ θαυμάσιε, ἐξέπληξε τῆς τοῦ τρίτου γενέσεως· καίτοι πολλά γε καὶ τὸ ἄπειρον παρέσχετο γένη, ὅμως δ' ἐπισφραγισθέντα τῷ τοῦ μᾶλλον καὶ ἐναντίου γένει ἓν ἐφάνη.

**ΠΡΩ.** Ἀληθῆ. 

**ΣΩ.** Καὶ μὴν τό γε πέρας οὔτε πολλὰ εἶχεν, οὔτ' ἐδυσκολαίνομεν ὡς οὐκ ἦν ἓν φύσει. 

**ΠΡΩ.** Πῶς γὰρ ἄν; 

**ΣΩ.** Οὐδαμῶς. ἀλλὰ τρίτον φάθι με λέγειν, ἓν τοῦτο τιθέντα τὸ τούτων ἔκγονον ἅπαν, γένεσιν εἰς οὐσίαν ἐκ τῶν μετὰ τοῦ πέρατος ἀπειργασμένων μέτρων. 

**ΠΡΩ.** Ἔμαθον.

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XIV. 26e-27d

::: columns
::: {.column width="35%"}
**ΣΩ.** Ἀλλὰ δὴ πρὸς τρισὶ τέταρτόν τι τότε ἔφαμεν εἶναι γένος σκεπτέον· κοινὴ δ' ἡ σκέψις. ὅρα γὰρ εἴ σοι δοκεῖ ἀναγκαῖον εἶναι πάντα τὰ γιγνόμενα διά τινα αἰτίαν γίγνεσθαι.   

**ΠΡΩ.** Ἔμοιγε· πῶς γὰρ ἂν χωρὶς τούτου γίγνοιτο; 

**ΣΩ.** Οὐκοῦν ἡ τοῦ ποιοῦντος φύσις οὐδὲν πλὴν ὀνόματι τῆς αἰτίας διαφέρει, τὸ δὲ ποιοῦν καὶ τὸ αἴτιον ὀρθῶς ἂν εἴη λεγόμενον ἕν; 

**ΠΡΩ.** Ὀρθῶς. 

**ΣΩ.** Καὶ μὴν τό γε ποιούμενον αὖ καὶ τὸ γιγνόμενον οὐδὲν πλὴν ὀνόματι, καθάπερ τὸ νυνδή, διαφέρον εὑρήσομεν. ἢ πῶς; 

**ΠΡΩ.** Οὕτως. 

**ΣΩ.** Ἆρ' οὖν ἡγεῖται μὲν τὸ ποιοῦν ἀεὶ κατὰ φύσιν, τὸ δὲ ποιούμενον ἐπακολουθεῖ γιγνόμενον ἐκείνῳ;

**ΠΡΩ.** Πάνυ γε. 

**ΣΩ.** Ἄλλο ἄρα καὶ οὐ ταὐτὸν αἰτία τ' ἐστὶ καὶ τὸ δουλεῦον εἰς γένεσιν αἰτίᾳ. 

**ΠΡΩ.** Τί μήν;

**ΣΩ.** Οὐκοῦν τὰ μὲν γιγνόμενα καὶ ἐξ ὧν γίγνεται πάντα τὰ τρία παρέσχετο ἡμῖν γένη; 

**ΠΡΩ.** Καὶ μάλα. 

**ΣΩ.** Τὸ δὲ δὴ πάντα ταῦτα δημιουργοῦν λέγομεν τέταρτον, τὴν αἰτίαν, ὡς ἱκανῶς ἕτερον ἐκείνων δεδηλωμένον; 

**ΠΡΩ.** Ἕτερον γὰρ οὖν. 

**ΣΩ.** Ὀρθῶς μὴν ἔχει, διωρισμένων τῶν τεττάρων, ἑνὸς ἑκάστου μνήμης ἕνεκα ἐφεξῆς αὐτὰ καταριθμήσασθαι. 

**ΠΡΩ.** Τί μήν; 

**ΣΩ.** Πρῶτον μὲν τοίνυν ἄπειρον λέγω, δεύτερον δὲ πέρας, ἔπειτ' ἐκ τούτων τρίτον μεικτὴν καὶ γεγενημένην οὐσίαν· τὴν δὲ τῆς μείξεως αἰτίαν καὶ γενέσεως τετάρτην λέγων ἆρα μὴ πλημμελοίην ἄν τι; 

**ΠΡΩ.** Καὶ πῶς; 

**ΣΩ.** Φέρε δή, τὸ μετὰ τοῦθ' ἡμῖν τίς ὁ λόγος, καὶ τί ποτε βουληθέντες εἰς ταῦτα ἀφικόμεθα; ἆρ' οὐ τόδε ἦν; δευτερεῖα ἐζητοῦμεν πότερον ἡδονῆς γίγνοιτ' ἂν ἢ φρονήσεως. 
οὐχ οὕτως ἦν; 
**ΠΡΩ.** Οὕτω μὲν οὖν.

**ΣΩ.** Ἆρ' οὖν ἴσως νῦν, ἐπειδὴ ταῦτα οὕτω διειλόμεθα, κάλλιον ἂν καὶ τὴν κρίσιν ἐπιτελεσαίμεθα πρώτου πέρι καὶ δευτέρου, περὶ ὧν δὴ τὸ πρῶτον ἠμφεσβητήσαμεν; 

**ΠΡΩ.** Ἴσως. 

**ΣΩ.** Ἴθι δή· νικῶντα μὲν ἔθεμέν που τὸν μεικτὸν βίον ἡδονῆς τε καὶ φρονήσεως. ἦν οὕτως; 

**ΠΡΩ.** Ἦν.

**ΣΩ.** Οὐκοῦν τοῦτον μὲν τὸν βίον ὁρῶμέν που τίς τέ ἐστι καὶ ὁποίου γένους; 

**ΠΡΩ.** Πῶς γὰρ οὔ; 

**ΣΩ.** Καὶ μέρος γ' αὐτὸν φήσομεν εἶναι τοῦ τρίτου οἶμαι γένους· οὐ γὰρ [ὁ] δυοῖν τινοῖν ἐστι [μικτὸς ἐκεῖνος] ἀλλὰ συμπάντων τῶν ἀπείρων ὑπὸ τοῦ πέρατος δεδεμένων, ὥστε ὀρθῶς ὁ νικηφόρος οὗτος βίος μέρος ἐκείνου γίγνοιτ' ἄν.

**ΠΡΩ.** Ὀρθότατα μὲν οὖν.

:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XV. 27e-28c

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XVI.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XVII.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XVIII.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XIX.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XX.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XXI.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XX.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XXIII.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XXIV.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XXV.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XXVI

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XXVII.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XXVIII.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## XXIX.

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

## Capitulum

::: columns
::: {.column width="35%"}
Greek
:::

::: {.column width="5%"}
:::

::: {.column width="60%"}
::: panel-tabset
### Самсонов 1929

### Самсонов 1994

### Алиева 2024

:::
:::
:::


_Тут какой-то комментарий к тексту._

