### Вопросы к разделам I-V

(@) В споре между _гедонистами_ и _интеллектуалистами_, как он сформулирован в самом начале, чья позиция вам кажется сильнее и почему? Как поведение самого Филеба характеризует крайний гедонизм в сравнении с позицией его преемника Протарха? 

(@) Сократ почти сразу допускает победу «третьего состояния», если оно окажется ближе к одному из кандидатов. Как вы думаете, в чем диалектический смысл такого хода? 

(@) Протарх утверждает, что "удовольствие всегда подобно удовольствию". Почему для Протарха важен этот тезис в контексте спора? Почему Сократ видит в этом препятствие для дальнейшей дискуссии?

(@) Позицию Протарха иногда понимают как _эпифеноменализм_: удовольствие сопутствует различным состояниям, не имея собственного когнитивного содержания и ничего не "сообщая" о реальности. Согласны ли вы с такой трактовкой?

(@) Протарх выражает явное удовлетворение тем, что Сократ поставил разум в такое же «уязвимое положение», как и удовольствие. В чем выражается эта уязвимость?

(@) Сократ разделяет «детские» загадки об одном и многом и «серьезные» проблемы. В чем заключается эта разница?

(@) В чем суть диалектического метода как он описан в «даре богов»? 


