### Перевод Самсонова

Перевод диалога "Филеб", выполненный Н.В. Самсоновым, вошел в четырехтомник под редакцией А.Ф. Лосева. Однако этот перевод был опубликован не в 1924 г., как утверждают редакторы четырехтомника в примечаниях, а в 1929 г. Он вошел в четвертый том пятнадцатитомника Платона под ред. С.А. Жебелева, Л.Э. Радлова и др.

Сам Николай Васильевич скончался в 1921 г., т.е. его перевод был опубликован посмертно и, судя по примечаниям, был исправлен С.А. Жебелевым и А.А. Франковским. Рукопись Н.В. Самсонова не сохранилась, так что судить о том, что именно было исправлено, нельзя.

В издании 1994 г. перевод Самсонова был заново сверен и исправлен И.И. Маханьковым. Мы решили сравнить две версии, чтобы понять, насколько они различаются.

Результат автоматического сравнения двух версий можно найти по [ссылке](https://locusclassicus.github.io/samsonov_translation/). По обилию исправлений видно, что перевод «Филеба» в издании Лосева было бы правильнее называть не переводом Самсонова, а переводом Самсонова-Маханькова, потому что текст был решительно переработан — не только стилистически, но и по существу.

### Лонгриды

- [Парадоксы удовольствия у Платона](https://antibarbari.ru/2022/04/25/paradox_pleasure_1/) 1 (2020)
- [Покой - замена счастью? Парадоксы удовольствия 2](https://antibarbari.ru/2022/04/25/paradox_pleasure_2/)
- [Краткий путеводитель по основным героям диалогов Платона](https://gorky.media/context/kratkij-putevoditel-po-osnovnym-geroyam-dialogov-platona-chast-1/). Часть 1
- [Краткий путеводитель по основным героям диалогов Платона](https://gorky.media/context/kratkij-putevoditel-po-osnovnym-geroyam-dialogov-platona-chast-2/) Часть 2 

