### 11а–12b Протарх принимает тезис, а Филеб умывает руки 

_Сократ_. Рассмотри, Протарх, какое положение ты сейчас примешь от Филеба и с чем тебе придется спорить, если мой тезис придется тебе не по душе. Давай кратко изложим оба положения?

_Протарх_. Давай. 

_Сократ_. Так вот, Филеб считает, что благо для всех живых существ заключается в том, чтобы радоваться, испытывать удовольствие и наслаждение и все то, что созвучно этому роду. Мы же утверждаем, что благо не в этом, а в том, чтобы разуметь, мыслить и помнить, а также во всем, что этому сродно, то есть в правильном мнении и в истинном рассуждении. Все это и лучше, и желаннее удовольствия для всех, кто способен к этому приобщиться, а для тех, кто к этому причастен, — и сейчас, и в будущем — и полезнее всего. Не так ли, Филеб, мы с тобой считаем?

_Филеб_. Именно так, Сократ. 

_Сократ_. Принимаешь ли ты, Протарх, положение, которое тебе сейчас предлагается?

_Протарх_. Делать нечего, надо принять — ведь красавец Филеб у нас сдался. 

_Сократ_. Значит, надо сделать все возможное, чтобы как-то добраться до истины в этом вопросе?

_Протарх_. Да, надо.

_Сократ_. Тогда давай вдобавок к сказанному условимся и вот еще о чем.

_Протарх_. О чем же?

_Сократ_. О том, что каждый из нас постарается указать некий уклад и расположение души, которые могли бы сделать жизнь всякого человека счастливой. Согласен?

_Протарх_. Вполне. 

_Сократ_. Стало быть, вы укажете на радостное [расположение и уклад], а мы — на разумное?

_Протарх_. Все верно. 

_Сократ_. А что, если выяснится, что другое [расположение или уклад] одолеет эти два? Разве в том случае, если оно окажется родственно удовольствию, не придется нам обоим уступить той жизни, в которой оно неизменно присутствует, в то же время признав победу удовольствия над разумением?

_Протарх_. Да. 

_Сократ_. Если же оно окажется ближе к разумению, то в этом случае разумение одерживает верх, а удовольствие проигрывает. Можно ли считать, что мы об этом договорились?

_Протарх_. Я, во всяком случае, не против. 

_Сократ_. А Филеб? Ты что скажешь?

_Филеб_. Что касается меня, то мое мнение есть и будет неизменно: удовольствие в любом случае побеждает. А ты, Протарх, суди сам. 

_Протарх_. После того, как ты, Филеб, передал нам свой тезис, ты уже, пожалуй, не волен ни соглашаться с Сократом, ни наоборот. 

_Филеб_. Ты прав и довольно об этом: я умываю руки и призываю теперь в свидетели саму богиню. 

_Протарх_. Мы тоже могли бы быть тебе свидетелями в том, что ты сказал именно это. Что же касается остального, Сократ, попытаемся довести дело до конца — с согласия Филеба или как ему будет угодно.

### 12b–13d Не все удовольствия друг другу подобны

_Сократ_. Стоит попытаться, причем начав с самой богини, которая, по словам Филеба, зовется Афродитой, хотя подлинное ей имя — Удовольствие. 

_Протарх_. Правильно.

_Сократ_. Имена богов, Протарх, всегда вызывают у меня нечеловеческий трепет; ни один страх с этим не сравнится. Вот и теперь Афродиту я называю так, как ей угодно. Но про удовольствие я знаю, что оно разнообразно и, как я сказал, нам следует, начав с него, обдумать и исследовать, какова его природа. Говорят о нем просто, как о чем-то едином, — но формы оно принимает, конечно, разные, причем каким-то образом непохожие друг на друга. В самом деле, смотри: мы говорим, что радуется человек распущенный, — и что радуется воздержанный, в силу самой своей воздержанности. И, опять-таки, радуется глупец, полный безумных мнений и надежд, — и разумный, в силу самого своего разумения. Так как же, называя и те и другие удовольствия подобными друг другу, самому по праву не прослыть безумцем?

_Протарх_. Дело в том, Сократ, что, хотя эти удовольствия вызваны противоположными вещами, сами они, разумеется, друг другу не противоположны. Как это возможно, чтобы удовольствие из всех вещей в наибольшей степени не было подобно удовольствию, то есть себе самому?

_Сократ_. Так ведь и цвет, Протарх, подобен цвету — по крайней мере в том, что это цвет. Однако черный, как мы все знаем, не только отличен от белого, но и представляет собой его противоположность. Точно также и с фигурами: все они относятся к одному роду, но некоторые части этого рода друг другу противоположны, а другие обнаруживают, пожалуй, бесконечное число различий. И со многим другим дело обстоит так же. Так что не доверяй тому рассуждению, которое все противоположности сводит воедино: как бы некоторые удовольствия не оказались у нас противоположны друг другу. 

_Протарх_. Возможно. Но чем это может повредить моему рассуждению?

_Сократ_. Тем, что ты непохожие вещи называешь вторым именем, утверждая, что все приятное — благо. С тем, что приятное приятно, никто не спорит. Однако, хотя большинство удовольствий — зло, а некоторые — благо (как я утверждаю), ты все называешь благом, в то же время признавая, если тебя к этому вынудить, что они непохожи друг на друга. Что же в равной степени присуще и благим и дурным удовольствиям, что ты все удовольствия называешь благом? 

_Протарх_. Что ты такое говоришь, Сократ! Неужели ты думаешь, что кто-то, назвав удовольствие благом, согласится с тобой и потерпит твои рассуждения о том, что одни удовольствия — благо, а какие-то другие — зло?

_Сократ_. Но ты все же признаешь, что они отличаются друг от друга, а некоторые даже противоположны.

_Протарх_. Вовсе нет, во всяком случае не как удовольствия.

_Сократ_. Опять мы возвращаемся к тому, с чего начали, Протарх. Значит, одно удовольствие не отличается от другого удовольствия, и все они подобны друг другу? Неужели мы, несмотря на только что приведенные примеры, станем вторить самым несведущим в речах новичкам? 

_Протарх_. О чем это ты?

_Сократ_. О том, что если я, подражая тебе и защищаясь, не постесняюсь сказать, что непохожее более всего похоже на непохожее, то я стану утверждать то же, что и ты; мы оба обнаружим свою неопытность, и рассуждение наше провалится. Так что давай его снова подтолкнем и, совершая похожие захваты, попробуем друг с другом согласиться. 

_Протарх_. Скажи, как.

### 13e–14b Знания тоже бывают разные

_Сократ_. Давай ты, в свою очередь, будешь меня спрашивать.

_Протарх_. О чем?

_Сократ_. Разумение, знание, ум и все то, что в начале я перечислил, отвечая на вопрос о том, что же такое благо, — разве все это не окажется в той же мере уязвимо?

_Протарх_. Как это?

_Сократ_. Знания, взятые все вместе, окажутся многочисленными, а некоторые из них и непохожими друг на друга. Если, кроме того, какие-то будут в чем-то противоположными, то достойным ли я окажусь собеседником, сказав от испуга, что ни одно знание не отличается от другого? Вслед за этим наше рассуждение погибло бы, подобно сказанию, а сами мы бы спаслись бы с помощью какой-то бессмыслицы.

_Протарх_. Спастись надо, а остальное совершенно недопустимо. Впрочем, меня вполне устраивает то, что наши с тобой рассуждения окажутся в равном положении: пусть и удовольствия будут многочисленны и несхожи между собой, и знаний пусть тоже будет много, причем разных.

_Сократ_. В таком случае, Протарх, не станем скрывать различий между твоим и моим благом! Поместим их посредине и мужественно примем то, что они  ответят на наши расспросы: считать ли благом удовольствие, разумение или что-то третье. Ибо наше состязание затеяно не для того, чтобы победило мое или твое рассуждение, но оба мы должны сражаться на стороне наиболее истинного.

_Протарх_. Ты прав. 

### 14с–15с Но как одно может быть многим? 

_Сократ_. Усилим же нашу мысль (λόγον) единомыслием (ὁμολογία). 

_Протарх_. О чем ты?

_Сократ_. О том, что всем доставляет трудности — хотят они того или нет (случается порой и такое с некоторыми). 

_Протарх_. Говори яснее. 

_Сократ_. Я говорю о том, о чем только что зашла речь. Пожалуй, это поистине нечто удивительное! В самом деле, удивительно утверждать, что одно — это многое, а многое — одно. Легко опровергнуть того, кто будет защищать любой из этих двух тезисов. 

_Протарх_.Ты имеешь в виду, когда кто-то станет утверждать, что хотя я, Протарх, по природе один, в то же время меня — много, причем эти разные "я" противоположны друг другу, поскольку один и тот же человек оказывается большим и маленьким, тяжелым и легким — и множество подобных вещей?

_Сократ_. Ты, Протарх, говоришь об одной из тех общеизвестных загадок об одном и многом, относительно которых, можно сказать, все уже согласились, что ими заниматься не следует. Это детские и легкие загадки оказываются большой помехой для рассуждений. Впрочем, не следует также принимать во внимание и те случаи, когда кто-нибудь, разделив в своем рассуждении человека на составные части и заставив [собеседника] признать, что все это есть одно, станет затем с насмешкой обличать того, кто вынужден говорить нелепости: будто одно есть многое и даже бесконечно многое, а многое есть только одно.

_Протарх_. Ну а ты, Сократ, какие загадки об одном и многом имеешь в виду, которые еще не общеизвестны и по поводу которых нет согласия?

_Сократ_. Я говорю о тех случаях, когда кто-то постулирует одно не в области возникающего и гибнущего, как в последних примерах. В самом деле, как мы только что сказали, по поводу такого одного нет смысла спорить. Но когда некто пытается допустить одного Человека, одного Быка, одно Прекрасное или одно Благое, — усердие в разделении таких и такого рода единств (ἑνάδων)  оборачивается разногласиями. 

_Протарх_. О чем же?

_Сократ_. Во-первых, следует ли допустить, что единицы — какие-то такие же, то есть истинно сущие. Далее, как [можно допустить, что] каждая [монада] — одно, вечно тождественное, не подверженное ни возникновению, ни гибели, и тем не менее неизменно является тем одним [генадой]? Затем, следует ли полагать, что в возникающем и беспредельном она или рассеялась и стала многим, или же она, целая, обособленно от самой себя (как раз это и может показаться решительно невозможным), оказывается чем-то тождественным и одним сразу как в одном, так и во многом. Именно то, что относится к таким одному и многому (а не к тому, что ты упомянул), и есть, Протарх, причина всяческих затруднений, когда об этом нет должного согласия, — и причина их разрешения, когда такое согласие есть.

_Протарх_. Стало быть, Сократ, над этим нам следует сейчас потрудиться в первую очередь?

_Сократ_. Я бы сказал, что да. 

_Протарх_. Тогда, считай, что все мы здесь присутствующие согласны с тобой в этом. Что же до Филеба, то это лихо лучше не будить вопросами. 

### 15d–17а Единое и многое есть во всем

_Сократ_. Хорошо. Но с чего же начать? В этом вопросе спор идет о многих разнообразных вещах. Разве что с этого?

_Протарх_. С чего же?

_Сократ_. Мы, пожалуй, скажем, что смешение одного и многого в рассуждениях происходит повсюду и есть во всем, о чем бы мы ни говорили, всегда — и раньше, и сейчас. Это никогда не закончится и началось не сегодня, но присуще нам, как мне кажется, как некое бессмертное и нестареющее свойство самих рассуждений. И всякий раз, когда кто-то из юношей впервые его изведает, он радуется, словно нашел некий кладезь мудрости. Вне себя от удовольствия, он с наслаждением переделывает всякое рассуждение, то как бы вращая его в одну сторону и сворачивая воедино, то снова разворачивая и разделяя на части. И прежде и более всего он заводит в тупик себя самого, а затем и всякого, кто окажется рядом — будь он младше, старше или того же возраста. Он не щадит ни отца, ни матери, ни кого другого из слушателей и чуть ли не из всех живых существ, не только из людей. Он и варваров никого бы не пощадил, если бы только смог найти переводчика.

_Протарх_. Сократ, ты разве не видишь, что тут нас целая толпа юношей? Не боишься, что мы вместе с Филебом на тебя нападем, если ты будешь нас оскорблять? Впрочем, — поскольку мы понимаем, что ты имеешь в виду — если есть какой-то способ и средство, чтобы такого рода путаница по-доброму исчезла у нас из рассуждений и чтобы мы нашли к ним некий подход получше, то не жалей усилий, а мы по мере сил за тобой последуем. Вопрос-то перед нами серьезный!

_Сократ_. Действительно, серьезный, мальчики (как к вам обращается Филеб). Нет, уверяю вас, и не может быть пути лучше, чем тот, который я всегда предпочитал , хотя довольно часто, сбившись с него, я оставался один в безвыходной ситуации. 

_Протарх_. Что же это за путь? Пусть он будет назван. 

_Сократ_. Показать его не очень трудно, а вот ступать по нему — крайне трудно. Все, что когда-либо было открыто из имеющего отношение к искусству, становилось очевидно благодаря ему. Смотри же, о каком пути я говорю. 

_Протарх_. Ты только говори.

_Сократ_. Дар богов людям — как мне, во всяком случае, кажется — откуда-то от богов через некоего Прометея  был брошен вместе с ярчайшим огнем. И древние, будучи лучше нас и живя ближе к богам, передали такую молву, что то, о чем всегда говорится как о сущем, состоит из одного и многого и при этом соединяет в своей природе предел и беспредельность. Поскольку так это упорядочено, нам следует всегда, предположив одну идею для всякой вещи, всякий раз во всем ее разыскивать (и поскольку она там есть, находить). И вот, когда мы к ней приобщимся, после одной следует рассмотреть, нет ли там двух, трех или какого-то другого числа [идей ]. И каждое [последующее] одно мы должны, в свою очередь, рассматривать таким же образом, пока мы не увидим изначальное одно не только как одно, многое и беспредельное, но и как количественно определенное. А идею беспредельного к множеству не следует прилагать, пока мы не усмотрим число, которое расположено между беспредельным и одним. Только тогда каждое одно можно отпустить в беспредельное и попрощаться с ним. И вот боги, как я сказал, так заповедали нам исследовать, учиться и учить друг друга. А современные мудрецы одно  образуют как попало, то есть намного поспешнее и медленнее, чем следует, а после одного сразу беспредельное. При этом все то, что посредине, от них ускользает, а именно в этом и есть вся разница между тем, чтобы рассуждать диалектически или эристически.

_Протарх_. Что-то из твоих слов, Сократ, я, как мне кажется, понимаю, а другое еще требует большей ясности. 

### 17a–e Примеры: грамматика и музыка

_Сократ_. Что я имею в виду, Протарх, видно на примере букв  (рассмотрим то, чему ты обучен). 

_Протарх_. Каким же образом?

_Сократ_. Звук, который мы произносим, — это, пожалуй, что-то одно, но, с другой стороны, всякий и каждый из нас издает бесконечно много звуков.

_Протарх_. Да, и что же? 

_Сократ_. И ничто из этого еще не делает нас мудрыми: ни знание того, что звуков бесконечно много, ни что звук один. Но когда мы знаем, сколько бывает звуков и каковы они, — именно это делает каждого из нас сведущим в грамматике. 

_Протарх_. Совершенно верно. 

_Сократ_. Далее, сведущими в музыке нас делает то же самое. 

_Протарх_. Что ты имеешь в виду?

_Сократ_. Звук в этом искусстве, полагаю, один, как и в том [грамматическом]. 

_Протарх_. Как же иначе?

_Сократ_. При этом мы выделяем два звучания: низкое и высокое, а также третье, среднее, не так ли?

_Протарх_. Так. 

_Сократ_. Зная только это, ты, однако, еще не был бы сведущ в музыке; но не зная и этого, ты, так сказать, был бы совсем ни на что не годен.

_Протарх_. Так и есть.

_Сократ_. Но, Протарх, когда ты усвоишь звуковые интервалы, сколько их и каких в высоком и низком [регистре], когда будешь знать границы интервалов и сколько они образуют созвучий… Открыв все это, наши предки завещали нам, своим последователям, называть такие созвучия гармониями, в то время как другие подобные свойства, присущие движениям тела , следует, по их словам, называть ритмом и размером, поскольку они измеряются числом. И подобным образом необходимо исследовать всякое единое и многие. Так вот, когда ты эти предметы таким образом усвоишь, тогда ты уже мудрец. Когда же и любое другое одно ты постигаешь в подобном рассмотрении, тогда и в нем стал рассудителен. А беспредельное множество чего бы то ни было во всяком деле и всякий раз делает тебя неспособным к разумению, так что с тобой никто не считается и не учитывает твое мнение, поскольку ты сам никогда и ни в чем не взираешь ни на какое число. 

_Протарх_. По-моему, Филеб, Сократ сейчас выразился просто восхитительно.

### 18a–20а Удовольствия следует разделить так же, как буквы, но собеседники Сократа на это не способны

_Филеб_. Да и мне так кажется. Но какое отношение эти слова имеют к нам? К чему он клонит?

_Сократ_. В самом деле, Протарх, Филеб правильно спрашивает. 

_Протарх_. Согласен. Отвечай же ему. 

_Сократ_. Отвечу, но сначала чуть подробнее рассмотрю начатое. Итак, как мы сказали, если кто берет любое одно, то он должен сразу же взирать не на природу беспредельного, а на некое число. И наоборот: если кто вынужден сначала взять беспредельное, то не сразу пусть обращается к одному, но прежде помыслит некое число, присущее всякому множеству, а от этого всего пусть переходит к одному. Усвоим это опять-таки на примере букв. 

_Протарх_. Как же?

_Сократ_. Когда-то беспредельность звука заметил некий то ли бог, то ли божественный человек (сказание гласит, будто в Египте это был некий Тевт). Так вот, он первым заметил в беспредельном не одну, а несколько гласных, а также другие [буквы] — причастные звуку, но не голосу, которых тоже определенное число. Наконец, был выделен третий вид букв, которые мы теперь называем безгласными. После этого он начал делить  те, которые беззвучные и безгласные, вплоть до одного, и точно также — гласные и средние. Тогда, узнав их число, каждое и всякое [одно] он назвал буквой. Видя же, что никто из нас не мог бы узнать никакое одно само по себе, без всех остальных, он назвал эту связь (рассудив, что она одна и словно неким образом объединяет их все воедино) грамматикой, потому что она для них едина.

_Филеб_. Это, Протарх, я понял лучше, во всяком случае, если сравнивать с тем, что было сказано ранее. Но от меня и сейчас, как и чуть ранее, занимает тот же вопрос.

_Сократ_. Не о том ли, Филеб, какое это имеет отношение к делу?

_Филеб_. Да, именно этого и я, и Протарх уже давно доискиваемся. 

_Сократ_. Вы давно, как ты говоришь, доискиваетесь того, что у вас перед глазами. 

_Филеб_. Как это?

_Сократ_. Разве мы с самого начала вели разговор не о разумении и удовольствии, что из них следует предпочесть?

_Филеб_. Не иначе.

_Сократ_. И мы утверждаем, что каждое из них — одно. 

_Филеб_. Да.

_Сократ_. Значит, предыдущее рассуждение требует от нас [выяснить], как каждое из них — и одно, и многое; почему они не сразу становятся беспредельными, а приобретают, перед тем как стать беспредельными, некоторое число.

_Протарх_. Хороший вопрос, Филеб, перед нами поставил Сократ! Каким-то образом, ходя по кругу, он сумел завести нас [в тупик]. Давай же решим, кто из нас будет отвечать на поставленный вопрос. Было бы, пожалуй, нелепо, если я, полностью унаследовав твой тезис, вновь поручил бы тебе отвечать, сам не справившись с этой задачей. Впрочем, намного смешнее, если никто из нас не сможет ответить. Так что смотри, что нам делать. По-моему, Сократ сейчас спрашивает о видах удовольствия: существуют ли они, сколько их и что это за виды? И, с другой стороны, все то же самое [спрашивается] и о разумении.

_Сократ_. Совершенно справедливо, сын Каллия!  В самом деле, как показало предшествующее рассуждение, если мы не сможем проделать это в отношении любого одного, подобного и тождественного, а также их противоположностей, то все мы окажемся во всяком деле ни на что не годными.

_Протарх._ Пожалуй, так оно и есть, Сократ. Однако, хотя для человека здравомысленного прекрасно знать вообще все, но второе плавание заключается, видно, в том, чтобы не быть в неведении о себе самом. К чему это я? Сейчас объясню. Ты, Сократ, затеял эту беседу, согласившись вместе со всеми нами выделить наилучшее из человеческих приобретений. И когда Филеб заявил, что это удовольствие, наслаждение, радость и все в этом роде, ты на это возразил, что лучшее — не это, а то, о чем мы часто и охотно сами себе напоминаем (и правильно делаем), чтобы и то, и другое, соседствуя в нашей памяти, подверглось испытанию. Так вот, ты, похоже, утверждаешь, что благо — это то, что кто-то с полным правом сочтет лучше удовольствия: ум, знание, понимание, искусство и все в этом роде. Именно это, а не то, следует приобретать. Поскольку это стало предметом спора, мы тебе в шутку пригрозили, что не отпустим тебя домой, пока не наметится достаточный предел в рассуждении об этих вещах. Ты согласился и обязался с нами это исследовать. Так что теперь мы, как дети, скажем: что подарено — назад не требуют. Перестань, как ты это делаешь, на все нам возражать.

_Сократ_. О чем это ты?

_Протарх_. Я имею в виду твою привычку ставить всех в тупик и расспрашивать о том, на что я не мог бы теперь дать тебе сносный ответ. В самом деле, не следует думать, что цель нашего нынешнего рассуждения — поставить всех в тупик. Но если мы сами не можем сделать то, [что ты от нас хочешь,] то тебе следует за это взяться. Ты ведь обещал. Итак, реши сам, следует ли тебе разделить на виды  удовольствие и знание — или же бросить это дело, если ты можешь и хочешь каким-то иным способом прояснить то, о чем у нас теперь спор. 

### 20b–23b Ни удовольствие, ни знание не являются благом: доказательство без деления на виды

_Сократ_. Что ж, если ты так говоришь, то мне уже можно ничего не опасаться. Потому что твое "если хочешь" избавляет меня от всякого страха. Кроме того, кажется, что кто-то из богов напомнил мне кое о чем. 
_Протарх_. Как это? О чем напомнил? 

_Сократ_. Когда-то давно я слышал — во сне или наяву — некие речи, и теперь они мне пришли на ум. Речи эти о том, что ни удовольствие, ни разумение не являются благом, но благо — это что-то третье, что, с одной стороны, отличается от обоих, а с другой — лучше и того, и другого. И если это сейчас станет для нас очевидно, то тогда удовольствие лишается победы, потому что благо было бы уже не тождественным удовольствию. Так?

_Протарх_. Да.

_Сократ_. А то, что необходимо для разделения на виды нам больше не понадобится — так мне кажется. Впрочем, в дальнейшем станет яснее. 

_Протарх_. Прекрасно сказано! Так и продолжи. 

_Сократ_. Тогда давай прежде договоримся еще об одной малости. 

_Протарх_. Какой же?

_Сократ_. Должен ли удел блага быть совершенным или несовершенным?

_Протарх_. Разумеется, в высшей степени совершенным, Сократ.

_Сократ_. А самодостаточно ли благо? 

_Протарх_. А как же! Именно этим оно отличается от всех сущих.

_Сократ_. И вот еще что, по-моему, необходимо сказать о благе: все познающее охотится за ним и стремится к нему, желая захватить его и иметь при себе, не заботясь ни о чем, что не сопровождалось бы благами. 

_Сократ_. С этим не поспоришь.

_Протарх_. Давай же рассмотрим и оценим по отдельности и жизнь удовольствия, и жизнь разумения. 

_Протарх_. Что ты имеешь в виду?

_Сократ_. Пусть ни в приятной жизни не будет разумения, ни в разумной — удовольствия. В самом деле, если что-то из этого является благом, то оно ничуть ни в чем больше не нуждается. А если окажется, что нуждается, то это, пожалуй, не будет у нас подлинным благом. 

_Протарх_. Как же иначе! 

_Сократ_. Проверим это, испытав на тебе? 

_Протарх_. Хорошо.

_Сократ_. Тогда отвечай. 

_Протарх_. Спрашивай.

_Сократ_. Согласился бы ты, Протарх, прожить всю жизнь, наслаждаясь величайшими удовольствиями?

_Протарх_. Еще бы!

_Сократ_. Не думал бы ты, что тебе чего-то недостает, если бы удовольствия у тебя было предостаточно?

_Протарх_. Нет, ничуть.

_Сократ_. Подумай, неужели ты не испытывал бы никакого недостатка в разумении, в мысли, в рассуждении или в чем-то подобном? 

_Протарх_. С чего бы? Ведь если бы я мог радоваться, я бы ни в чем не нуждался. 

_Сократ_. Значит, проводя так жизнь, ты бы всегда радовался величайшим удовольствиям?

_Протарх_. Конечно. 

_Сократ_. В то же время неизбежно, чтобы ты, не обладая умом, памятью, знанием и правильным мнением, во-первых, никак не мог знать того, радуешься ты или не радуешься, потому что ты был бы лишен всякого разумения?

_Протарх_. Да, это неизбежно.

_Сократ_. Далее, не обладая памятью, ты бы неизбежно, я так полагаю, не помнил, радовался ли ты когда-либо, а если б случилось тебе наслаждаться в какой-то момент, то об этом не сохранилось бы никакого воспоминания. Опять-таки, не обладая правильным мнением, ты бы, радуясь, не мнил, что радуешься. А будучи неспособным рассуждать, ты бы не смог рассудить, что тебе предстоит радоваться в будущем. И жил бы ты жизнью не человека, а какой-то медузы или одного из тех морских существ, чьи тела заключены в раковины. Все так или, несмотря на сказанное, мы можем думать как-то иначе?

_Протарх_. Как же иначе?

_Сократ_. Предпочтем ли мы такую жизнь?

_Протарх_. Нет слов. На это рассуждение, Сократ, мне нечего ответить.

_Сократ_. И все-таки не будем раскисать, и, взявшись за ум, рассмотрим в свой черед и его жизнь. 

_Протарх_. Что ты имеешь в виду?

_Сократ_. Согласился бы кто-нибудь из нас на то, чтобы жить, обладая и разумением, и умом, и знанием, и памятью о чем угодно, но при этом ни в коей мере не испытывать ни удовольствий, ни огорчений, но вести жизнь совершенно бесстрастную и далекую от таких переживаний. 

_Протарх_. Ни одна из описанных жизней, Сократ, не кажется мне предпочтительной. И никому, я так думаю, не покажется. 

_Сократ_. А что ты скажешь о жизни, в которой смешаны удовольствие и разумение, и которая стала общей для них обоих?

_Протарх_. Ты говоришь о жизни удовольствия и разумения?

_Сократ_. Да, именно об этом.

_Протарх_. Я полагаю, что всякий скорее предпочтет такую жизнь, чем одну из упомянутых ранее. Не только мы, но и любой без исключения. 

_Сократ_. Что ж, понимаем ли мы, что из этого рассуждения следует?

_Протарх_. Вполне. Было предложено три жизни, и из них две оказались недостойны предпочтения для людей или кого-либо из живых существ. 

_Сократ_. Разве уже не очевидно, что эти две, во всяком случае, не обладали благом? В противном случае они были бы самодостаточны, совершенны и желанны для всего, что растет и дышит  и может так провести всю жизнь. И если кто-то из нас выбрал бы что-то иное, то он сделал бы это вопреки природе подлинно желанного, против своей воли, либо по невежеству, либо в силу какой-то злополучной необходимости.

_Протарх_. Похоже, что это действительно так. 

_Сократ_. Следовательно, Филебову богину не следует считать тождественной благу, о чем, кажется, сказано уже достаточно.

_Филеб_. Но ведь и твой ум, Сократ, — это не благо, и его можно будет упрекнуть в том же. 

_Сократ_. Пожалуй, Филеб, если говорить о моем уме, но во всяком случае в этом не упрекнешь подлинный и в то же время божественный ум. С ним дело обстоит иначе. Я пока не оспариваю победу у смешанной жизни в пользу ума, но что делать со второй наградой, об этом еще надо подумать. Возможно, что причиной этой смешанной жизни один из нас назовет ум, а другой удовольствие. В таком случае ни то, ни другое не будет, пожалуй, благом, но одно из них может оказаться своего рода причиной. И вот об этом я бы еще поспорил с Филебом: в этой смешанной жизни, чем бы ни было то, благодаря чему эта жизнь становится и желанной, и благой, — к этому ближе и подобнее ему не удовольствие, а ум. И согласно этому рассуждению про удовольствие можно было бы справедливо утверждать, что удовольствие не имеет отношения ни к первому, ни к второму месту. Да и от третьего оно оказывается довольно далеко, если только нам стоит теперь доверять моему уму.

_Протарх_. И правда, Сократ, мне кажется, что удовольствие у тебя повергнуто, словно сраженное недавними доводами. Оно пало, сражаясь за победу. А вот про ум, похоже, можно сказать, что он благоразумно не стремился к победе, а не то с ним случилось бы то же самое. Лишившись наград, удовольствие должно быть в совершенном пренебрежении у своих поклонников, ведь даже им оно уже не может казаться таким же прекрасным. 
_Сократ_. Что ж! Не лучше ли нам оставить его в покое и не огорчать, подвергая опровержениям и тщательнейшим испытаниям?

_Протарх_. Какая нелепость, Сократ!

_Сократ_. Не потому ли, что невозможно "огорчить удовольствие"?

_Протарх_. Не только это! Ты как будто не понимаешь, что никто из нас тебя не отпустит, пока ты не разберешь этот вопрос до конца.

### 23b–27c Новое средство: четырехчастная онтология

_Сократ_. Ох, Протарх, тогда нам предстоит долгая беседа, да и нелегкое мы теперь затеяли дело. К тому же, похоже, что нам потребуется какое-то новое средство, чтобы, отправляясь в поход за второй наградой для ума, мы были бы вооружены не прежними речами, а как-то иначе. Впрочем, что-то из прежнего тоже может пригодиться. Попробуем?

_Протарх_. Непременно.

_Сократ_. Давай будем осмотрительны, выбирая начало для нового рассуждения.

_Протарх_. О каком начале ты говоришь?

_Сократ_. Все ныне сущее во вселенной давай разделим надвое или, если угодно, скорее натрое. 

_Протарх_. На каком же основании? 

_Сократ_. Возьмем кое-что из того, о чем мы только что говорили. 

_Протарх_. Что?

_Сократ_. Мы вроде упоминали, что бог указывает то на беспредельное в сущих, то на предел?

_Протарх_. Да. 

_Сократ_. Пусть это будет у нас двумя видами, а третьим станет тот, который смешан воедино из того и другого. Но я, вероятно, совсем смешон со своими делениями на виды и перечислениями. 

_Протарх_. Что ты имеешь в виду?

_Сократ_. Видно, мне понадобится еще и четвертый род!

_Протарх_. Скажи, какой.

_Сократ_. Взгляни на причину этого взаимного смешения, и давай добавим к тем трем еще ее. 

_Протарх_. Не понадобится ли тебе вдобавок и пятый род, способный производить разделение? 

_Сократ_. Не исключено, что понадобится, но во всяком случае не сейчас. Но если окажется, что он мне нужен, ты, я надеюсь, простишь, если я пущусь и на поиски пятого. 

_Протарх_. Разумеется. 

_Сократ_. Сначала из этих четырех выделим три и испытаем два из них. Увидев, что оба они сильно раздроблены и рассеяны, и собрав их вновь воедино, обдумаем, как каждый их является одним и в то же время многим.

_Протарх_. Если бы ты мне это объяснил подробнее, я бы сразу за тобой последовал.

_Сократ_. Ну так я все о тех же двух [видах], которые мы только упомянули: о беспредельном и о том, что имеет предел. А как беспредельное некоторым образом является многим, это я сейчас попробую объяснить. А имеющее предел пусть у нас подождет.

_Протарх_. Ждет.

_Сократ_. Смотри же (конечно, то, что я прошу рассмотреть трудно и спорно, но ты все-таки смотри). Что касается более теплого и более холодного, во-первых, взгляни, можно ли в них помыслить какой-то предел или же, пока в этих родах присутствуют «более и менее», они не допускают окончательности, потому что любой конец стал бы для них кончиной.

_Протарх_. Ты прав. 

_Сократ_. Но мы утверждаем, что в более теплом и более холодном всегда есть это «более и менее».

_Протарх_. Еще бы.

_Сократ_. Таким образом, рассуждение наше указывает на то, что эти два никогда не имеют конца, а, будучи бесконечными, они, конечно, становятся совсем беспредельными.

_Протарх_. И даже очень, Сократ.

_Сократ_. А ведь это прекрасный ответ, Протарх! Как кстати ты напомнил, что это «очень», упомянутое тобой, и «едва» имеют то же свойство, что и «более и менее». В чем бы они ни обретались, они не позволяют этому быть количественно определенным. Делая каждое действие сильнее по сравнению со слабым и наоборот, они порождают «больше и меньше», а определенное количество истребляют. Ведь, как только что было сказано, если они не истребят количество, но позволят числу и мере возникнуть на месте «более и менее» и «сильно и слабо», то мера и число вытеснят их из той области, где они обитали. Как только появляется количественная определенность, исчезает более теплое и более холодное. Потому что более теплое всегда движется и не стоит на месте — и более холодное точно так же. А количественная определенность неподвижна и уже никуда не идет. Согласно с этим, и более теплое, и его противоположность оказываются, видно, беспредельным.

_Протарх_. Именно так, Сократ. Но за этим, как ты сказал, нелегко угнаться. Впрочем, если повторить это вновь и вновь, то и спрашивающий, и отвечающий могут достичь достаточного согласия. 

_Сократ_. Прекрасная мысль, давай так и поступим. Взгляни теперь на природу беспредельного, будем ли мы считать ее признаком, чтобы не затягивать рассуждение это все долгими перечислениями…

_Протарх_. Что же?

_Сократ_. Все то, что очевидно становится «более и менее», «сильно и слабо», «слишком» и так далее, — все это необходимо поместить, как бы сведя воедино, в род беспредельного, согласно с предшествующим нашим рассуждением. Мы говорили, если помнишь, о том, что, сведя вместе все рассеянное и раздробленное, необходимо по мере сил обозначить это как одну природу. 

_Протарх_. Помню. 

_Сократ_. Стало быть, все то, что не принимает этого, а принимает то, что этому противоположно (во-первых, равное и равенство, после равенства — двойное и все, что представляет собой число по отношению к числу и меру по отношению к мере) — все это причисляя к пределу, мы, пожалуй, поступим прекрасно. А ты как считаешь?

_Протарх_. Прекраснее некуда, Сократ.

_Сократ_. Ладно. А про третий, смешанный из этих двух, мы скажем, что он имеет какой вид?

_Протарх_. Это, я думаю, ты мне скажешь. 

_Сократ_. Скорее какой-нибудь бог, если только кто-то из богов прислушается к моим мольбам. 

_Протарх_. Тогда молись и исследуй. 

_Сократ_. Исследую! И мне кажется, Протарх, что кто-то из богов к нам теперь благосклонен. 

_Протарх_. Что это значит? Что тебе об этом сказало?

_Сократ_. Я, разумеется, поясню. А ты у меня следи внимательно. 

_Протарх_. Ты только говори.

_Сократ_. Мы с тобой только что назвали нечто более теплым и более холодным, так?

_Протарх_. Да. 

_Сократ_. Добавь к этому более сухое и более влажное, более многочисленное и менее многочисленное, более быстрое и более медленное, и большее и меньшее, и все то, что мы прежде поместили в единство природы, допускающей «более и менее». 

_Протарх_. Ты говоришь о природе беспредельного?

_Сократ_. Да. После этого соедини с ней потомство предела. 

_Протарх_. Какое же?

_Сократ_. Которое недавно мы так и не свели воедино, хотя необходимо было его свести, потомство пределовидного — так же, как мы свели  потомство беспредельного. Но, возможно, результат будет тот же, если, сведя воедино предел и беспредельное, мы увидим и его, [потомство].

_Протарх_. Какое же? И как мы его увидим?

_Сократ_. Потомство равного и двойного и всего того, что прекращает взаимный разлад в противоположностях и, вложив в них число, делает их согласными и соразмерными. 

_Протарх_. Понимаю: ты, смешав это, кажется, говоришь о том, от каждого из них получаются некие становления?

_Сократ_. Тебе правильно кажется.

_Протарх_. В таком случае, говори.

_Сократ_. Разве в болезнях правильное общение [предела и беспредельного] не порождает природу здоровья?

_Протарх_. Именно так. 

_Сократ_. А в области высокого и низкого, быстрого и медленного (каждая из которых беспредельна), разве происходит не то же самое? Оно одновременно и налагает предел, и в совершенстве устраивает все мусическое?

_Протарх_. Прекрасно сказано. 

_Сократ_. Кроме того, привходя в стужу и зной, оно отнимает у них избыточность и беспредельность и привносит, напротив, умеренность и соразмерность. 

_Протарх_. Как же иначе?

_Сократ_. Значит, от этого, от смешения беспредельного и имеющего предел, возникают и времена года, и все то прекрасное, что у нас есть?

_Протарх_. Верно. 

_Сократ_. Я не говорю о множестве других вещей, как, например, о красоте и силе, которые сопровождают здоровье, да и в душах [это порождает] много всего прекрасного. Эта богиня, прекраснейший Филеб, видя дерзость и всяческий порок и понимая, что в них нет предела ни удовольствиям, ни насыщению, наложила в качестве предела закон и порядок. По-твоему, это губит [удовольствие], а по-моему, спасает. А ты, Протарах, со мной согласен?

_Протарх_. Мне это, Сократ, весьма по душе.

_Сократ_. Итак, если ты заметил, я сказал о трех [родах].

_Протарх_. Я вроде бы понимаю. Первый — это, вероятно, беспредельное. Еще один род — это предел в сущих. Но что ты имеешь в виду по третьим, это мне не очень ясно. 

_Сократ_. Тебя, удивительный человек, смутило обилие потомства того третьего. Хотя и беспредельное представило множество родов, но они показались нам единым, так как были отмечены родом «более» и его противоположностью.

_Протарх_. Верно. 

_Сократ_. А в пределе не было множества и на то, что оно не едино по природе, нам не пришлось досадовать.

_Протарх_. Как уж тут досадовать?

_Сократ_. Никак! Теперь считай, что я говорю о третьем роде, считая одним [родом] всякое порождение тех двух, то есть возникновение к бытию, [происходящее] из меры, произведенной пределом. 

_Протарх_. Уяснил. 

_Сократ_. Но теперь необходимо исследовать нечто четвертое, как мы сказали ранее. Ведь это все одно исследование. Смотри же. Необходимо ли, чтобы все возникающее возникало в силу некоей причины? 

_Протарх_. Думаю, да. Иначе как бы оно без нее возникало?

_Сократ_. Значит, природа производящего не отличается от причины ничем, кроме имени? И производящее и причину мы могли бы правильно назвать одним?

_Протарх_. Правильно.

_Сократ_. Но ведь мы обнаружим, что и производимое и возникающее ничем, кроме имени, не отличаются, как и то, о чем мы только что сказали. Так это или нет?

_Протарх_. Так. 

_Сократ_. И для производящего естественно всегда направлять, а для производимого — следовать за ним в своем возникновении?

_Протарх_. Да.

_Сократ_. Следовательно, причина и то, что подчиняется причине в возникновении, — не одно и то же. 

_Протарх_. А как же!

_Сократ_. Таким образом, возникающее и то, из чего все возникает, дали нам три рода?

_Протарх_. Именно так. 

_Сократ_. А того, кто все это устраивает, мы называем четвертым, и это причина, отличающаяся, как было достаточно показано, от тех. 

_Протарх_. Да, это что-то другое. 

_Сократ_. Хорошо бы после того, как мы разграничили четыре рода, перечислить их, чтобы запомнить каждый в отдельности.

_Протарх_. Почему бы и нет?

_Сократ_. Во-первых, я говорю о беспредельном, во-вторых, о пределе, затем о третьей, смешанной и возникшей сущности. Наконец, назвав четвертым причину смешения и возникновения, я бы, пожалуй, не ошибся?

_Протарх_. В чем же?

### 27c–28b Удовольствие как беспредельное

_Сократ_. Давай же подумаем, о чем у нас пойдет речь дальше. Зачем мы к этому пришли? Разве не о том шла речь, кому достанется вторая награда — удовольствию или разумению? Так?

_Протарх_. Да.

_Сократ_. Возможно, теперь, когда мы мы так это разделили, мы бы могли бы прекраснее судить о первой и второй награде, о чем с самого начала и шел спор?

_Протарх_. Возможно. 

_Сократ_. Тогда смотри. Мы постановили, что смешанная жизнь одерживает победу над удовольствием и разумением? Верно?

_Протарх_. Да. 

_Сократ_. В таком случае рассмотрим, быть может, эту жизнь — что это за жизнь и какого она рода?

_Протарх_. Почему бы и не рассмотреть?

_Сократ_. Одну ее часть, я так думаю, мы отнесем к третьему роду, потому что он представляет собой смешение не одной какой-то пары, а вообще всего беспредельного, связанного пределом. Так что по праву такая победоносная жизнь оказалась бы частью этого рода.

_Протарх_. Совершенно верно.

_Сократ_. Ладно. Ну а твоя, Филеб, жизнь, приятная и несмешанная? К какому из перечисленных родов ее было бы правильно отнести? Но сначала ответь мне вот на какой вопрос, прежде чем ответить.

_Филеб_. Говори.

_Сократ_. Удовольствие и огорчение имеют ли предел или же они относятся к роду допускающего «более и менее»?

_Филеб_. Да, к тому, что допускает «более», Сократ. Потому что удовольствие не было бы совершенным благом, если бы количество и интенсивность его по природе не были бы беспредельными.

_Сократ_. Да и огорчение не было бы совершенным злом, Филеб!  Так что нам надо исследовать нечто другое, кроме природы беспредельного, благодаря чему удовольствия приобретают меру блага. Итак, пусть удовольствие относится к роду беспредельного. А теперь, Протарх и Филеб, скажите, к чему из перечисленного выше мы должны отнести разумение, знание и ум, чтобы не совершить кощунства нечестие? Мне кажется, что многое зависит от того, дадим ли мы правильный ответ на этот вопрос, или нет.

_Филеб_. Что-то ты, Сократ, превозносишь своего бога!

_Сократ_. Да и ты, друг, свою богиню! И все же следует ответить на вопрос. 

_Протарх_. И правда, Филеб, Сократ прав, давай прислушаемся к нему.

_Филеб_. А не ты ли, Протарх, взялся говорить вместо меня?

_Протарх_. Да, но теперь я в почти полном недоумении, так что прошу тебя, Сократ, чтобы ты стал для нас истолкователем [воли этого бога, т.е. Ума], чтобы мы не допустили ошибки насчет твоего кандидата и не сказали бы что-нибудь не в лад. 

### 28c–30e Ум как причина в микро- и макрокосме

_Сократ_. Как скажешь, Протарх. Да и нет ничего трудного в том, что ты велишь. Но неужели я, в шутку «превознося», как выразился Филеб, [своего кандидата], в самом деле смутил тебя вопросом о том, к какому роду отнести ум и знание?

_Протарх_. Очень смутил, Сократ.

_Сократ_. Но ведь в этом нет ничего трудного! В самом деле, все мудрецы согласны, что Ум у нас царь неба и земли (и тем самым они поистине превозносят сами себя). Пожалуй, в этом они правы. Но если угодно, рассмотрим подробнее тот род, к которому он относится.

_Протарх_. Говори, сколько считаешь нужным, Сократ, не обращая внимания на время, нас это никак не обидит.

_Сократ_. Прекрасно. Начнем, пожалуй, вот с какого вопроса.

_Протарх_. С какого же?

_Сократ_. Скажем ли мы, Плутарх, что всем и вот этим так называемым мирозданием заведует какая-то неразумная и беспорядочная сила, простая случайность? Или же наоборот, как утверждали наши предшественники, всем руководит, упорядочивая, Ум и какое-то удивительное разумение? 

_Протарх_. Тут и сравнивать нечего, Сократ! Первое предположение кажется мне даже нечестивым. Утверждение, что все это упорядочивает Ум, единственно достойно космического зрелища: солнца, луны, светил и всего небесного свода. И лично я никогда не изменил бы мнения на этот счет и не стал бы утверждать иначе. 

_Сократ_. Что ж, если хочешь, то согласимся с прежними [философами], что все обстоит именно так, и не только будем считать, что можно не только без опаски повторять чужие слова, но и вместе с ними подвергнемся опасности и порицанию вместе с ними, всякий раз, когда какой-нибудь умник заявит, что кругом царит беспорядок, а вовсе не порядок. 

_Протарх_. Как же не пойти на это?

_Сократ_. Ладно, тогда взгляни, что из этого следует.

_Протарх_. Выкладывай. 

_Сократ_. То, что относится к телесной природе всех живых существ (огонь, вода, дыхание , и, как говорят мореплаватели в бурю: «земля!»), — все это мы, пожалуй, можем заметить и в составе [вселенной]?

_Протарх_. Еще бы! Мы ведь и сами как такие мореплаватели, совсем заплутали.

_Сократ_. Тогда допусти относительно каждого присущего нам [элемента] вот что.

_Протарх_. Что же?

_Сократ_. Что в нас это что-то малое и негодное, совершенно лишенное как чистоты, так и подобающей его природе силы. Рассмотрев что-то одно, мы можем так же мыслить обо всем прочем. Например, огонь присутствует, пожалуй, и в нас, и во вселенной. 

_Протарх_. Да.

_Сократ_. И тот огонь, что в нас, — малый, слабый и негодный, а тот, что во вселенной, — удивителен по своим размерам, красоте и всяческой присущей огню силе. 

_Протарх_. Сущая правда.

_Сократ_. Что же? Скажем ли мы, что огонь вселенной питается от нашего огня, возникает и возрастает благодаря ему, или же, напротив, и мой, и твой, и других живых существ огонь обладает всем этим от того огня?

_Протарх_. Этот вопрос даже не нуждается в ответе.

_Сократ_. Верно. Я полагаю, то же самое ты скажешь по поводу земли, — здешней, которая в живых существах, и той, что во вселенной, а также по поводу всего другого, о чем я немного ранее спрашивал. Не так ли?

_Протарх_. Кто же, будучи в здравом уме, ответил бы иначе?

_Сократ_. Думаю, что никто. Но следи за тем, что из этого следует. Рассмотрев все то, о чем мы только что сказали, как единый состав, разве мы не назвали его телом?

_Протарх_. Конечно. 

_Сократ_. То же самое допустим и относительно того, что мы называем космосом: точно так же он, пожалуй, является телом, сложенным из тех же [элементов]. 

_Протарх_. Ты совершенно прав. 

_Сократ_. Скажем ли мы, что от этого тела питается все наше тело, получая от него и сохраняя все то, о чем мы только что сказали? Или тело космоса питается от нашего?

_Протарх_. И об этом, Сократ, не стоит и спрашивать.

_Сократ_. А как по-твоему, стоит ли спросить вот о чем?

_Протарх_. О чем же?

_Сократ_. Разве мы не скажем, что наше тело имеет душу?

_Протарх_. Конечно, скажем.

_Сократ_. А откуда взялась бы у тела душа, если бы тело вселенной, обладая теми же свойствами (элементами) и даже во всех отношениях прекраснее, не было бы одушевлено?

_Протарх_. Ясно, Сократ, что большей ей взяться неоткуда.

_Сократ_. В самом деле, Протарх, нельзя же допустить, что эти четыре [рода] (предел, беспредельное, общее и, в-четвертых, присущий всему род причины), из которых последний привносит душу в наши [элементы] , и заботится о телесных упражнениях или, если тело повреждено, о его лечении, и в других [элементах] как-то иначе их и составляет, и исцеляет, и потому зовется разнообразной мудростью — нельзя же допустить, что в тех же самых [элементах]  целого неба, хотя это те же самые элементы, только в большем масштабе, и притом чистые и прекрасные, что в них, оказывается, не действует природы прекраснейшего и ценнейшего? 

_Протарх_. В этом не было бы никакого смысла. 

_Сократ_. Но если это не так, то, последовав за другим рассуждением, мы бы лучше сказали, что существует, как мы часто повторяем, во вселенной много беспредельного, есть и достаточный предел, и есть наряду с ними некая не захудалая причина, которая устраивает и упорядочивает времена годы, сезоны и месяцы, справедливо называемая мудростью и умом. 

_Протарх_. И правда справедливо.

_Сократ_. Но мудрость и ум без души, наверно, не могли бы никогда возникнуть.

_Протарх_. Нет, конечно, не могли.

_Сократ_. Значит, ты скажешь, что в природе Зевса под воздействием причины возникает царственная душа и царственный ум, и другим богам точно так же присуще то, о чем им наиболее приятно слышать. 

_Протарх_. Да.

_Сократ_. Не подумай, Протарх, что этот речь эту мы ведем впустую, но она служит поддержкой тем древним мудрецам, которые утверждают, что ум надо всем властвует. 

_Протарх_. Действительно.

_Сократ_. А для моего исследование оно доставляет ответ, а именно что ум относится к роду, называемому родом причины. Теперь ты знаешь мой ответ.

_Протарх_. Знаю, вполне, хотя я и не заметил, как ты отвечал. 

_Сократ_. Иногда, Протарх, забава служит передышкой от серьезного дела. 

_Протарх_. Верно подмечено. 

### 31a–32b Удовольствие как восстановление телесной гармонии

_Сократ_. Итак, друг, какого он рода и какой обладает силой, почти все это мы теперь продемонстрировали достаточно.  

_Протарх_. Да. 

_Сократ_. И точно так же давно проявился и род удовольствия. 

_Протарх_. И даже очень. 

_Сократ_. Будем же помнить о них обоих и то, что ум родствен причине и почти того же рода, а удовольствие и само беспредельно, и относится к такому роду, который не имеет и никогда не получит ни начала, ни середины, ни конца в себе и от себя самого.

_Протарх_. Не забудем. Как же иначе?

_Сократ_. Далее, нам необходимо рассмотреть, в чем каждое из них заключается и при каких условиях они возникают, всякий раз, когда возникают. Во-первых, удовольствие. Как род его мы сначала испытывали, так и тут пусть оно будет первым. Что касается огорчения, то без него удовольствие мы бы никогда не могли испытать.

_Протарх_. Ну, если тебе нравится такой порядок, давай придерживаться его. 

_Сократ_. А ты, Протарх, не того же мнения, что и я, насчет их возникновения?

_Протарх_. А какого ты мнения?

_Сократ_. По-моему, огорчение и удовольствие по природе возникают в смешанном роде.

_Протарх_. А напомни нам, Сократ, что из упомянутого ты называешь смешанным. 

_Сократ_. Ну и ну, Протарх! Постараюсь.

_Протарх_. Хорошо.

_Сократ_. Под общим будем понимать то, что из четырех родов было у нас третьим.

_Протарх_. Ты имеешь в виду то, что после предела и беспредельного, в который ты поместил здоровье и, если не ошибаюсь, гармонию?

_Сократ_. Прекрасно! Ну а теперь будь очень внимателен. 

_Протарх_. Я весь внимание.

_Сократ_. Итак, я утверждаю, что когда у нас разрушается гармония в живых существах, то одновременно с этим разрушением в то же время возникает и боль. 

_Протарх_. Это похоже на правду. 

_Сократ_. А когда гармония вновь восстанавливается и возвращается к своей природе, тогда, скажем мы, возникает удовольствие, если необходимо как можно короче сказать о сложных вещах.

_Протарх_. Думаю, ты правильно говоришь, Сократ. Но давай попробуем быть яснее на этот счет. 

_Сократ_. Полагаю, проще всего рассмотреть примеры, которые известны и понятны каждому. 

_Протарх_. Какие?

_Сократ_. Голод — это в некотором смысле распад и страдание?

_Протарх_. Да. 

_Сократ_. А питание, возвращающая чувство насыщения, — удовольствие?

_Протарх_. Да.

_Сократ_. Жажда, в свою очередь, — это разрушение и страдание, а сила, наполняющая иссушенное влагой, — удовольствие. И, опять-таки, противоестественные разложение и распад, вызванные зноем, болезненны, а возвращение к естественной прохладе — приятно.

_Протарх_. Все так.

_Сократ_. Противное природе живых существ замерзание влаги, вызванное стужей, — страдание, а сообразный с природой путь, ведущий к прежнему состоянию и разделению [элементов] — удовольствие. Одним словом, смотри, покажется ли тебе достаточным такое рассуждение, которое утверждает, что одушевленный вид, возникший согласно природе из предела и беспредельного, как мы сказали вначале, когда он портится, то эта порча и есть страдание, а путь к собственной сущности, вот это возвращение и есть для всего наслаждение. 

_Протарх_. Пусть будет так. Это, по крайней мере, дает некое представление. 

_Сократ_. Пусть удовольствие и страдание, связанные с этими процессами, будут у нас одним видом удовольствия.

_Протарх_. Хорошо.

### 32b–33c Удовольствия предвосхищения

_Сократ_. Теперь возьмем случай, когда сама душа предвосхищает что-то из этого. Это будет либо приятное и уверенное предвкушение удовольствия, либо пугающее и болезненное ожидание огорчений. 

_Протарх_. Да, это другой вид удовольствия и страдания, возникающий в душе помимо тела в силу ожидания. 

_Сократ_. Ты правильно понял. Я полагаю, что на примере этих двух [видов] удовольствия, — а на мой взгляд, каждое из них возникает в чистом виде, то есть без смешения удовольствия и страдания,  — станет ясно по поводу удовольствия, весь ли его род желанен, или же это нам следует отнести к какому-то другому из перечисленных родов, а удовольствие и страдание, как теплое и холодное и все в таком роде, следует считать иногда желанным, а иногда нежеланным, потому что это не блага, хотя они и способны иногда принимать природу блага. 

_Протарх_. Ты прав, что каким-то таким образом следует исследовать то, что мы сейчас ищем.

_Сократ_. Прежде всего, давай вместе заметим вот что. Если и вправду разрушению сопутствует страдание, а восстановлению — удовольствие, то подумаем о том, что не подвергается ни разрушению, ни восстановлению, в каком состоянии должно тогда находиться каждое живое существо, когда оно таково. Будь очень внимателен, отвечая: разве не необходимо, чтобы в это время всякое живое существо не испытывало ни малого, ни большого удовольствия или страдания? 

_Протарх_. Необходимо. 

_Сократ_. Значит, есть у нас какое-то третье состояние, помимо радости и огорчения? 

_Протарх_. А как же?

_Сократ_. Итак, постарайся его запомнить. Для суждения об удовольствии важно, чтобы мы помнили, существует такое состояние или нет. Если хочешь, кратко рассмотрим это (третье) состояние. 

_Протарх_. Да, говори.

_Сократ_. Ты знаешь, что такое расположение ничуть не мешает прожить разумную жизнь.

_Протарх_. Ты имеешь в виду жизнь, в которой нет ни радости, ни печали?

_Сократ_. Сравнивая жизни, мы договорились, что это одно из условий для того, кто выбрал жизнь разумения и ума, чтобы он не знал никаких удовольствий, ни больших, ни малых.

_Протарх_. Именно так. 

_Сократ_. Возможно, это и есть та жизнь, которую он избрал, и, пожалуй, нет ничего странного в том, чтобы эта жизнь была наиболее божественной.

_Протарх_. Во всяком случае неправдоподобно, чтобы боги наслаждались или наоборот.

_Сократ_. Да, в это сложно поверить! По крайней мере, возникновение любого из этих переживаний им бы не подобало. Впрочем, в случае необходимости мы вернемся к этому вопросу позже: даже если ум не займет первое место, то это поможет ему в борьбе за второе.

_Протарх_. Ты прав. 

### 33с–34d Ощущение, память и воспоминание

_Сократ_. Далее, есть и другой вид удовольствий, принадлежащих, как мы сказали, самой душе. Этот вид целиком возникает благодаря памяти. 

_Протарх_. Как же?

_Сократ_. Придется, видимо, сначала рассмотреть, что же такое память. И, боюсь, еще прежде памяти надо будет сказать о чувственном восприятии, если мы хотим должным образом прояснить этот вопрос. 

_Протарх_. Что ты имеешь в виду?

_Сократ_. Допусти, что из всего того, что происходит с телом, одно угасает, не дойдя до души и не вызвав никакого ощущения. Другое, проходя и через тело, и через душу, вызывает в них своего рода колебание, которое будет общим, но при этом для каждого из них своим. 

_Протарх_. Хорошо.

_Сократ_. Верно ли мы скажем, что то, что не проходит через и то, и другое, остается незаметным для души, а то, что проходит — заметно?

_Протарх_. Как же иначе?

_Сократ_. Однако не подумай, что под этой незаметностью я имею в виду процесс забывания. Дело в том, что забывание — это утрата памяти, а она-то в данном случае еще не возникла. А ведь невозможно утратить то, чего нет и что еще не возникало, верно?

_Протарх_. Разумеется. 

_Сократ_. Значит, надо только поменять имя. 

_Протарх_. Как?

_Сократ_. Вместо того, чтобы называть забыванием такие случаи, когда душа остается безучастной к волнениям тела, назови это бесчувственностью.

_Протарх_. Понятно. 

_Сократ_. А совместное движение, которое совместно возникает в едином переживании тела и души, — назвав это движение ощущением, мы бы, пожалуй, не ошиблись.

_Протарх_. Именно так. 

_Сократ_. Итак, нам понятно, как мы намерены называть ощущение?

_Протарх_. Разумеется.

_Сократ_. Значит, не ошибся бы, я так думаю, тот, кто назвал бы сохранение ощущения памятью.

_Протарх_. Да, это было бы верно.

_Сократ_. А разве мы не скажем, что память отличается от воспоминания?

_Протарх_. Возможно.

_Сократ_. Не в этом ли ее отличие?

_Протарх_. В чем?

_Сократ_. Всякий раз, когда душа сама собой, без тела, как можно лучше воспроизводит то, что она некогда переживала вместе с телом, — это мы, пожалуй, назовем воспоминанием? Как скажешь?

_Протарх_. Назовем. 

_Сократ_. Кроме того, всякий раз, когда душа, утратив память либо об ощущении, либо о знании, припоминает это сама собою, все это мы, пожалуй, тоже назовем воспоминаниями. 

_Протарх_. Ты прав. 

_Сократ_. А говорю я это все вот ради чего. 

_Протарх_. Чего же?

_Сократ_. Ради того, чтобы мы как можно лучше и яснее поняли удовольствия души без тела, а также вожделение. Сказанное, похоже, как-то проясняет для нас и то, и другое.

_Протарх_. Тогда, Сократ, давай уже посмотрим, что из этого следует.

_Сократ_. Многое еще необходимо сказать, похоже, и о возникновении удовольствия и о каждом его виде. В самом деле, и сейчас , похоже, надо сначала рассмотреть вожделение и понять, что это такое и как оно возникает. 

_Протарх_. Тогда давай рассмотрим, терять нам нечего. 

_Сократ_. Кое-что мы все-таки потеряем, Протарх, если будем искать то, что сейчас ищем, а именно свое затруднение. 

_Протарх_. Остроумно! Но все-таки постараемся сказать, что из этого следует. 

### 34d–35d Природа вожделения

_Сократ_.  Мы только что назвали голод, жажду и многое другое в том же роде некими вожделениями?

_Протарх_. Именно так. 

_Сократ_.  А взирая на какое общее [для них свойство], мы называем их единым именем, хотя они так сильно различаются?

_Протарх_. Клянусь, Сократ, это нелегко сказать! Но все-таки сказать надо.

_Сократ_. Тогда начнем с того же, с тех же [примеров]. 

_Протарх_. С каких же?

_Сократ_. Говоря «он испытывает жажду», мы, пожалуй, всякий раз имеем что-то в виду?

_Протарх_. Конечно. 

_Сократ_. А именно то, что он становится пустым.

_Протарх_. Да. 

_Сократ_. Но жажда — это разве не вожделение?

_Протарх_. Да, вожделение к питью. 

_Сократ_. К питью или к наполнению питьем?

_Протарх_. Думаю, что к наполнению.

_Сократ_. Тогда тот, кто становится пустым, вожделеет противоположного тому, чему он подвергается? Ведь он, становясь пустым, желает наполниться. 

_Протарх_. Очевидно.

_Сократ_. Так что же? Тот, кто впервые опустошается, есть откуда в нем взяться ощущению или памяти о наполнении, если он ни сейчас, ни раньше его не испытывал?

_Протарх_. Разумеется, нет.

_Сократ_. Но, конечно, мы бы сказали, что, испытывая вожделение, он вожделеет чего-то. 

_Протарх_. Как же иначе? 

_Сократ_. Значит, от вожделеет не того, что испытывает. Ведь он жаждет, а это опустошение. А вожделеет он наполнения.

_Протарх_. Да. 

_Сократ_. Так значит, что то в жаждущем каким-то образом, вероятно, соприкасается с наполнением?

_Протарх_. Неизбежно. 

_Сократ_. Но это, конечно, не тело: оно-то опустошается. 

_Протарх_. Да.

_Сократ_. Значит остается [допустить], что это душа соприкасается с наполнением, очевидно, при помощи памяти. Ведь чем еще другим она могла бы прикоснуться?

_Протарх_. Полагаю, что ничем. 

_Сократ_. Итак, мы понимаем, какой вывод следует из этих рассуждений?

_Протарх_. Какой же?

_Сократ_. Это рассуждение говорит нам, что у тела не возникает вожделений.

_Протарх_. Как же так?

_Сократ_. Потому что оно показывает, что всякое живое существо всегда покушается на то, что противоположно его состоянию. 

_Протарх_. Верно. 

_Сократ_. А стремление, направленное на то, что противоположно [его] состоянию, показывает, пожалуй, что существует память о том, что противоположно состояниям. 

_Протарх_. Именно так. 

_Сократ_. Таким образом, наше рассуждение, указав на память, которая наводит на предмет вожделения, показало, что всякое стремление и вожделение и власть над живым существом принадлежат душе. 

_Протарх_. Правильно. 

_Сократ_. А чтобы тело могло жаждать, голодать или испытывать что-то из этого, этого наше рассуждение не допускает. 

_Протарх_. Верно. 

### 35d–36d Удовольствия от предвосхищения

_Сократ_. Кроме того, примем во внимание еще вот что. А именно, как мне кажется, рассуждение у нас в этом стремится обнаружить некий образ жизни. 

_Протарх_. В чем и о какой жизни ты говоришь?

_Сократ_. О такой, которая заключается в наполнениях и опустошениях и во всем том, что относится к выживанию и гибели живых существ, если кто-то, оказавшись в одном из таких состояний то испытывает боль, то радуется согласно с изменениями. 

_Протарх_. Так и есть. 

_Сократ_. Ну, а если он оказывается посреди подобных [переживаний]?

_Протарх_. Как это посреди?

_Сократ_. Его состояние причиняет ему боль, но он помнить о приятном, которое, возникая, прекращает боль, хотя еще не наполняется. Что в таком случае? Скажем ли мы или нет, что он находится посреди двух состояний?

_Протарх_. Конечно, скажем. 

_Сократ_. Можно ли сказать, что он целиком страдает или радуется?

_Протарх_. Клянусь Зевсом, он испытывает двойное огорчение, одно телесное в силу своего состояния, другое душевное, в силу некоего томительного ожидания.

_Сократ_. Почему же, Протарх, ты называешь это двойным огорчением? Разве не бывает так, что кто-то из нас, опустошаясь, пребывает в твердой надежде на наполнение, а иногда, напротив, ни на что не надеется?

_Протарх_. Очень даже бывает.

_Сократ_. Разве ты не согласишься, что, надеясь на наполнение, [такой человек] радуется благодаря памяти и в то же время испытывает боль из-за опустошения?

_Протарх_. Необходимо. 

_Сократ_. В таких случаях и человек, и всякое живое существо огорчается и вместе с тем радуется. 

_Протарх_. Выходит, что так. 

_Сократ_. Ну, а как насчет тех случаев, когда, претерпевая опустошение, он не надеется испытать наполнение? Разве в этих случаях огорчение не было бы двойственным? Приняв это во внимание, ты и подумал, что оно вообще двойное.

_Протарх_. Верно, Сократ. 

_Сократ_. Воспользуемся же этим рассмотрением состояний вот как.

_Протарх_. Как же?

_Сократ_. Скажем ли мы, что эти огорчения и удовольствия истинны или ложны? Или некоторые истинны, а некоторые нет?

_Протарх_. Но как, Сократ, удовольствия или огорчения могли бы быть ложными?

_Сократ_. А как, Протрах, бывают истинными или ложными страхи, или ожидания истинными или нет, или мнения истинными или ложными?

_Протарх_. Что касается мнений, то тут я не стал бы спорить, но с остальным не согласен. 

_Сократ_. Как же так? Впрочем, похоже, мы тут подняли большую тему. 

_Протарх_. Ты прав. 

_Сократ_. Но если, сын славного человека, это относится к делу, о котором мы говорим, то надо ее рассмотреть. 

_Протарх_. Возможно, относится. 

_Сократ_. В таком случае, следует избегать всех прочих длинных рассуждений или вообще всего, что не относится к делу. 

_Протарх_. Верно. 

### 36e–38b Подлинные и ложные удовольствия и мнения

_Сократ_. Тогда скажи мне (потому что меня лично всегда  удивляло затруднение, связанное с тем, о чем мы только что сказали). Так ты говоришь, что с удовольствиями не так, что одни из них ложные, а другие истинные?

_Протарх_. Как же иначе?

_Сократ_. Значит, ни во сне, ни наяву, как ты утверждаешь, никто, даже если он безумен или не в себе , никогда не считает, что он радуется, в то время как он совсем не радуется, и, опять-таки, никто не думает, что он огорчается, не огорчаясь при этом? 

_Протарх_. Мы все, Сократ, полагаем, что это так. 

_Сократ_. Но правильно ли вы полагаете? Или следует рассмотреть, верно ли это говорится, или нет?

_Протарх_. Я бы сказал, что следует. 

_Сократ_. Тогда давай еще яснее определим то, что сейчас говорится об удовольствии и о мнении. Ведь мы можем, пожалуй, иметь о чем-то мнение?

_Протарх_. Да. 

_Сократ_. А также наслаждаться. 

_Протарх_. Да. 

_Сократ_. Кроме того, есть (=является чем-то) то, что мы мыслим.

_Протарх_. А как же. 

_Сократ_. И то, в силу чего наслаждается тот, кто получает удовольствие?

_Протарх_. И очень даже.

_Сократ_. Значит, то, что мнит, будь его мнение верным или нет, само это мнение никогда поистине не теряет. 

_Протарх_. Именно!

_Сократ_. Значит, и то, что наслаждается, вне зависимости от того, правильно или нет оно наслаждается, само это наслаждение, очевидно, никогда не утратит.

_Протарх_. Да, и это так. 

_Сократ_. Итак, следует рассмотреть, каким образом мнение у нас обычно бывает ложным и истинным, а удовольствие — только истинным, хотя подлинно иметь мнение и радоваться в равной степени свойственно обоим. 

_Протарх_. Следует.

_Сократ_. Возможно, потому что к мнению прибавляются ложь и истина, так что каждое мнение из-за них становится не просто мнением, но и приобретает некое качество. Это, по-твоему, следует рассмотреть?

_Протарх_. Да. 

_Сократ_. Кроме того, можем ли мы вообще говорить о том, что некоторые вещи у нас наделены некими качествами, а удовольствие и огорчение есть лишь то, что они есть и не приобретают никаких качеств. Не следует ли нам и об этом договориться? 

_Протарх_. Очевидно.

_Сократ_. Но это-то как раз нетрудно усмотреть, что они имеют некие качества. Мы ведь давно сказали, что и те, и другие бывают великие и малые, причем в наивысшей степени — я имею в виду огорчения и удовольствия. 

_Протарх_. Именно так. 

_Сократ_. Ну а если к чему-то из них, Протарх, прибавится испорченность, то мы скажем, что и мнение, и удовольствие стали испорченными?

_Протарх_. Разумеется. 

_Сократ_. Так что же? Если к чему-то из них прибавится правильность или нечто ей противоположное, разве мы не назовем правильным мнение, если оно будет обладать правильностью, и разве не скажем то же самое про удовольствие?

_Протарх_. Неизбежно.

_Сократ_. А если содержание мнения окажется ошибочным, разве не следует признать в таком случае мнение, коль скоро оно ошибается, неправильным и неправильно мнящим?

_Протарх_. Как же иначе?

_Сократ_. Далее. Если мы, опять-таки, заметим, что огорчение или некое удовольствие заблуждается  по поводу того, что вызывает огорчение или наоборот, — применим ли мы к нему название правильного, достойного или какое-то другое прекрасное имя?

_Протарх_. Но это невозможно, коль скоро удовольствие заблуждается. 

_Сократ_. Но, похоже, и в самом деле удовольствие возникает у нас часто в связи не с правильным, а с ложным мнением.

_Протарх_. Не спорю, но это мнение, Сократ, мы в таких случаях называем ложным, а само удовольствие никто никогда бы так не назвал. 

_Сократ_. Как отважно ты сейчас защищаешь удовольствие, Протарх, своим рассуждением!

_Протарх_. Ничего подобного, я говорю то, что слышал.

_Сократ_. Значит, друг, удовольствие с правильным мнением и знанием у нас ничуть не отличается от того удовольствия, которое часто возникает у каждого из нас вместе с ложью и незнанием?

_Протарх_. Очевидно, отличие тут немалое. 

_Сократ_. Тогда давай перейдем к рассмотрению их отличий. 

_Протарх_. Веди, куда считаешь нужным. 

_Сократ_. Вот куда я тебя поведу. 

_Протарх_. Куда же? 

### 38b–39с Внутренний секретарь и внутренний художник

_Сократ_. Мы утверждаем, что мнение у нас бывает ложное, а бывает истинное?

_Протарх_. Так.

_Сократ_. И за ними часто следуют, как мы сейчас говорили, удовольствие и огорчение, — я имею в виду за истинным и ложным мнением. 

_Протарх_. Да. 

_Сократ_. А разве мнение и сама способность всякий раз приходить к нему возникают у нас не благодаря памяти и чувственному восприятию?

_Протарх_. Именно так. 

_Сократ_. Не согласны ли мы в том, что в этом отношении мы находимся вот в каком состоянии?

_Протарх_.  В каком же?

_Сократ_. Не сказал бы ты, что часто тот, кому случается смутно видеть что-то издалека, хочет составить некое мнение о том, что он видит?

_Протарх_. Сказал бы. 

_Сократ_. Значит, вслед за этим  смотрящий спросил бы сам себя…

_Протарх_. О чем же?

_Сократ_. «Что это там такое виднеется у скалы под деревом?» Как, по-твоему, сказал бы он это сам себе, если бы ему что-то такое когда-нибудь показалось?

_Протарх_. Ну а как же. 

_Сократ_. А разве после этого, как бы отвечая себе самому, он не мог бы случайно догадаться, что это человек?

_Протарх_. Мог бы.

_Сократ_. Но он мог бы, возможно, вдобавок  ошибочно сказать, что то, что он видит, — это изваяние, дело рук каких-то пастухов?

_Протарх_. Весьма возможно.

_Сократ_. И если бы рядом с ним кто-то оказался, то он, переложив сказанное самому себе в слова и обращаясь к этому человеку, сказал бы то же самое. И таким образом то, что мы прежде называли мнением, становится речью?

_Протарх_. Да. 

_Сократ_. А если бы он случилось ему быть одному, то он иной раз, обдумывая то же самое про себя, даже довольно долго продолжает свой путь с этой мыслью.

_Протарх_. Да. 

_Сократ_. Так что же? Не кажется ли тебе происходящее с этим человеком  тем же, чем и мне?

_Протарх_. Чем именно?

_Сократ_. По-моему, в такие моменты душа похожа на некую книгу. 

_Протарх_. Как это?

_Сократ_. Когда память направлена на то же, что и чувства, то переживания, которые с этим [т.е. чувствами] связаны, как мне кажется, как бы записывают в наших душах некие речи. И всякий раз, когда переживание записано верно , то и мнение, и происходящие от этого [переживания] речи тоже оказываются истинны. Ну, а если этот наш секретарь запишет нечто ложное, то выходит противоположное истине. 

_Протарх_. Да, я того же мнения, и согласен с тем, как это сказано.

_Сократ_. Согласись же и с тем, что в наших душах в то же время действует и еще один мастер.

_Протарх_. Кто он?

_Сократ_. Художник, который вслед за секретарем пишет в душе образы того, о чем говорится. 

_Протарх_. Но как и когда, скажем мы, он, в свою очередь, это делает?

_Сократ_. Всякий раз, когда некто, отделив от зрения или какого-то иного ощущения то, что мнится или говорится, словно созерцает в душе образы мнимого или сказанного. Разве с нами так не бывает?

_Протарх_. Еще как бывает.

_Сократ_. Значит, образы подлинных мнений и речей подлинны, а образы ложных — ложны?

_Протарх_. Именно так. 

### 39с–40c Ложные удовольствия несправедливого человека

_Сократ_. Если же об этом мы сказали верно, то вдобавок давай рассмотрим еще вот что.

_Протарх_. Что же?

_Сократ_. Должны ли мы испытывать это лишь в отношении того, что есть или было, но не в отношении предстоящего?

_Протарх_. Это обстоит одинаково в отношении любого времени.

_Сократ_. Значит, во всяком случае удовольствия и печали самой души, как было сказано ранее, возникают, пожалуй, до телесных удовольствий и печалей, так что и предварительная радость, и предварительная печаль возникают по поводу будущих событий. 

_Протарх_. Совершенно верно. 

_Сократ_. Ну а про записи и картины, о которых мы чуть ранее договорились, что они возникают в нашей душе, — они относятся лишь к прошлому и настоящему, а к будущему не относятся?

_Протарх_. Очень даже относятся!

_Сократ_. Ты говоришь «очень», потому что все это — надежды, устремленные к будущему, а мы всю жизнь полны надежд?

_Протарх_. И правда, полны.

_Сократ_. Что ж, вдобавок к сказанному ответь и вот на какой вопрос.

_Протарх_. На какой же?

_Сократ_. Разве человек справедливый, благочестивый и доблестный во всех отношениях не будет угоден богам?

_Протарх_. А как же. 

_Сократ_. Далее. Человек несправедливый и вообще дурной разве не противоположность первому?

_Протарх_. Разумеется. 

_Сократ_. При этом, как мы только что сказали, всякий человек полон надежд?

_Протарх_. Конечно. 

_Сократ_. А речи, которые мы называем надеждами, есть в каждом из нас?

_Протарх_. Да. 

_Сократ_. И, кроме того, некие живописные образы. Кое-кто часто видит, как становится обладателем несметных богатств и вместе с тем удовольствий. Более того, он непомерно радуется, созерцая себя на этом изображении.

_Протарх_. Пожалуй.

_Сократ_. Скажем ли мы, что из этих людей у достойных картины по большей части изображают истинное, поскольку они угодны богам, а у дурных людей, напротив, по большей части наоборот. Можем мы это утверждать?

_Протарх_. Даже должны. 

_Сократ_. Значит, и дурные ничуть не менее созерцают картины удовольствий γε, но они в каком-то смысле ложные. 

_Протарх_. Да.

_Сократ_. Стало быть, дурные люди по большей части радуются ложным удовольствиям, а достойные люди — подлинным?

_Протарх_. То, что ты говоришь, необходимо.

_Сократ_. Следовательно, согласно нынешним рассуждениям, в душах людей существуют и ложные удовольствия, нелепые μεντοι подобия подлинных, и точно также дело обстоит с огорчениями. 

_Протарх_. Да, существуют.

### 40c–41a Дурные и ложные удовольствия

_Сократ_. Но, как мы видели (37а), если у человека есть вообще какое бы то ни было мнение, то он подлинно обладает этим мнением, хотя иногда это мнение не о том, что есть, было или будет. 

_Протарх_. Да. 

_Сократ_. А именно это, кажется, мы недавно назвали причиной ложного мнения и того, чтобы ложно мнить. Не так ли?

_Протарх_. Да.

_Сократ_. Так что же? Не следует ли признать за огорчениями и удовольствиями похожее свойство?

_Протарх_. Как?

_Сократ_. Если кто-то вообще чему-то хоть как-то радуется, хотя бы неразумно, он всегда радуется подлинно, даже если он радуется не тому, что есть или когда-либо было или — что случается часто и, пожалуй, даже чаще всего — тому, что никогда не случится.

_Протарх_. И это, Сократ, следует признать необходимым. 

_Сократ_. Следовательно, и о страхе, гневе и тому подобном, можно было бы сказать то же самое: все это порой бывает ложным?

_Протарх_. Весьма. 

_Сократ_. Далее. Есть ли у нас иной способ отличить дурные мнения от достойных, кроме как указав на их ложность?

_Протарх_. Нет.

_Сократ_. Но и удовольствия, я так думаю, мы считаем дурными лишь постольку, поскольку они ложные. 

_Протарх_. Совсем напротив, Сократ. Полагаю, что никто не стал бы считать огорчения и удовольствия порочными в силу их ложности, а скорее потому, что им сопутствует в ином смысле большая и разнообразная порочность. 

### 41a–42c Контраст удовольствия и боли

_Сократ_. Об порочных удовольствиях, ставших таковыми в силу порочности, мы поговорим чуть позже, если сочтем это уместным. А теперь следует разобрать удовольствия, в другом смысле ложные и многочисленные, которые часто в нас возникают и присутствуют. Это нам, пожалуй, пригодится для вынесения суждения. 
_Протарх_. Почему бы и нет? Если только такие бывают.

_Сократ_. А как же, Протарх, бывают — по крайней мере, я так думаю. Но пока это мнение нами не принято, невозможно оставить его без рассмотрения.

_Протарх_. Прекрасно. 

_Сократ_. Так подступимся же к этому рассуждению словно атлеты. 

_Протарх_. Вперед!

_Сократ_. Если мы не забыли, то немногим ранее мы сказали, что всякий раз, когда в нас возникают так называемые вожделения, то в таких случаях тело отдельно от души бывает охвачено переживаниями.

_Протарх_. Да, мы помним, что это было сказано.

_Сократ_. Значит, тем, что вожделеет, у нас была душа: она стремится к состоянию противоположному тому, в котором пребывает тело. А тем, что является источником боли или какого-либо удовольствия, связанного с переживанием, было тело. 

_Протарх_. Именно так.

_Сократ_. Так смотри, какой вывод из этого следует.

_Протарх_. Скажи. 

_Сократ_. Оказывается, что во всех таких случаях, удовольствия и огорчения находятся рядом, и возникают одновременные ощущения этих противоположностей, как стало только что очевидно. 

_Протарх_. Похоже на то. 

_Сократ_. Из того, о чем мы сказали и согласились раньше, нам понадобится вот еще что.  

_Протарх_. Что же?

_Сократ_. Что и удовольствия, и огорчения допускают «более и менее», и что они относятся к роду беспредельного.

_Протарх_. Допустим. Что из того?

_Сократ_. Существует ли способ, позволяющий об этом правильно судить?

_Протарх_. В каком смысле и как?

_Сократ_. Если мы намерены судить о них в подобных случаях, желая всякий раз распознать, что из этого больше или меньше по отношению к другому, и что сильнее и интенсивнее, — я имею в виду огорчение по отношению к удовольствию, а удовольствие по отношению к огорчению. 

_Протарх_. Да, такие случаи бывают, как и желание составить подобное суждение.

_Сократ_. Так что же? Что касается зрения, то, когда мы смотрим на предметы, находящиеся далеко или близко, то не можем правдиво судить об их размерах и приходим к ложным мнениям. Разве не то же самое происходит с огорчениями и удовольствиями?

_Протарх_. И даже в еще большей степени, Сократ! 

_Сократ_. А чуть ранее у нас получилось наоборот. 

_Протарх_. О чем ты говоришь?

_Сократ_. Тогда мы решили, что это мнения, становясь истинными или ложными, передают удовольствиям свои свойства. 

_Протарх_. Именно так. 

_Сократ_. А теперь получается, что удовольствия и огорчения меняются всякий раз в зависимости от созерцания издали или вблизи. Кроме того, когда они находятся рядом, удовольствия по сравнению с огорчением кажутся больше и интенсивнее, а с огорчениями, в свою очередь, происходит обратное.

_Протарх_. Неизбежно, что все это происходит по указанным причинам. 

_Сократ_. Отделим от того и другого ту мнимую составляющую, которая заставляет удовольствия и огорчения казаться больше по сравнению с реальными. Ведь ты не скажешь, что она правильно нам представлялась, и не осмелишься назвать правильным и истинным ту часть удовольствия и огорчения, которая возникает вместе с ней.

_Протарх_. Конечно, нет. 

### 42с–43d Возможность нейтральной жизни

_Сократ_. Вслед за этим рассмотрим, не сможем ли мы таким же образом обнаружить удовольствия и огорчения еще более ложные, чем только что упомянутые, в которых для живых существ видимость сочетается с реальностью.

_Протарх_. Какие это удовольствия и что ты имеешь в виду?

_Сократ_. Пожалуй, можно часто услышать, что огорчения, страдания, скорби и все то многое, что носит похожие имена, возникает при разрушении природы каждого [из живых существ] в силу соединения и распада или наполнения и опустошения или в силу неких приращений и убываний. 

_Протарх_. Да, об этом часто говорится. 

_Сократ_. Когда же собственная природа [живых существ] восстанавливается, то это восстановление, как мы сами договорились ранее (31a–32b), называется удовольствием.

_Протарх_. Верно.

_Сократ_. Ну а как насчет тех случаев, когда с нашим телом не происходит ни того, ни другого?

_Протарх_. Но когда, Сократ, это было бы возможно?

_Сократ_. Протарх, твой вопрос совсем не к месту. 

_Протарх_. Отчего же?

_Сократ_. Потому что это не мешает мне вновь задать тебе свой вопрос. 

_Протарх_. Какой?

_Сократ_. Если, говорю, ничего подобного не происходило бы, Протарх, то что из этого с неизбежностью должно для нас следовать?

_Протарх_. Ты имеешь в виду, если бы тело не изменялось в ту или другую сторону?

_Сократ_. Да. 

_Протарх_. Очевидно, Сократ, что тогда ни удовольствие, ни какое-либо огорчение не могли бы возникнуть в таком [живом существе].

_Сократ_. Прекрасный ответ. Но, полагаю, ты хочешь сказать, что что-то из этого всегда с необходимостью в нас происходит, как утверждают мудрецы. Ведь все всегда течет туда-сюда. 

_Протарх_. Так говорят и, по-моему, неплохо.

_Сократ_. Как же иначе, ведь и сами они люди неплохие. Как бы то ни было, я бы хотел уклониться от этого угрожающего нам рассуждения. Вот как я думаю убежать от него, и ты беги со мной. 

_Протарх_. Говори куда. 

_Сократ_. Будь по-вашему, скажем мы этим людям. А ты мне ответь, всегда ли все одушевленные существа, претерпевая что-либо, ощущают то, что они претерпевают? Можно ли сказать, что ничто из этих приращений и тому подобному не ускользает от нашего внимания, когда мы это испытываем, или совсем наоборот?

_Протарх_. Конечно, наоборот! Чуть ли не все из этого для нас незаметно. 

_Сократ_. Значит, нехорошо мы только что сказали, что происходящие в обе стороны изменения производят огорчения и удовольствия. 

_Протарх_. Да, и что с того?

_Сократ_. То, что сказанное будет лучше и точнее.

_Протарх_. Каким же образом?

_Сократ_. Если мы скажем, что большие изменения производят в нас удовольствия и огорчения, а умеренные и небольшие совсем ничего не производят.

_Протарх_. Да, это более правильно, Сократ.

_Сократ_. Если же это так, то вновь возникает упомянутая недавно жизнь.

_Протарх_. Какая же?

_Сократ_. Которая, как мы сказали, лишена и огорчений, и радостей.

_Протарх_. Ты совершенно прав. 

_Сократ_. На этом основании допустим три вида жизни, из которых одна приятна, другая огорчительна и еще одна — ни то, ни другое. Ты бы что сказал об этом?

_Протарх_. Все то же самое, что жизней всего три. 

### 43d–44d Ошибка аскета

_Сократ_. Значит, не огорчаться — это, пожалуй, не то же самое, что радоваться.

_Протарх_. Как же иначе?

_Сократ_. И если бы ты когда-нибудь услышал, что приятнее всего прожить всю жизнь без огорчений, то как бы ты понял того, кто это утверждает?

_Протарх_. Как мне кажется, он говорит, что не огорчаться приятно. 

_Сократ_. Представь, что у нас есть три вещи, какие тебе угодно. Назовем их как-нибудь красиво: скажем, золото и серебро, а третье пусть у нас будет ни тем, ни другим.

_Протарх_. Представил.

_Сократ_. Возможно ли, чтобы это третье стало у нас одним из двух, то есть золотом или серебром?

_Протарх_. Как же это могло бы случиться?!

_Сократ_. Значит, тот, кто называл бы среднюю жизнь приятной или тягостной, не имел бы об этом правильного мнения, если бы он придерживался некоего мнения, и рассуждение его, если бы он об этом говорил, тоже было бы неправильным — во всяком случае, если рассуждать правильно. 

_Протарх_. Не иначе. 

_Сократ_. Но, дружище, мы ведь замечаем тех, кто так говорит и так думает.

_Протарх_. Да, постоянно.

_Сократ_. Думают ли они, что радуются, когда не огорчаются?

_Протарх_. По крайней мере, так они говорят.

_Сократ_. Значит, они полагают, что в это время радуются. Иначе бы они так не говорили. 

_Протарх_. Выходит, что так. 

_Сократ_. Но их мнение о радости, конечно же, ложное, если только природа радости и отсутствия огорчений различна. 

_Протарх_. Конечно, мы решили, что она различна.

_Сократ_. Так что же мы выберем, Протарх? Либо, как мы только что сказали, есть три состояния, либо только два, причем из этих двух огорчение является злом для человека, а избавление от огорчений, будучи благом, называется приятным?

_Протарх_. Я решительно не понимаю, Сократ, как мы можем сейчас себя об этом спрашивать. 

_Сократ_. Значит, Протарх, ты не понимаешь противников вот этого Филеба.

_Протарх_. Это ты кого имеешь в виду?

_Сократ_. Тех, кто очень ловко рассуждает о природе и утверждает, что удовольствий вовсе не существует. 

_Протарх_. Как это?

_Сократ_. Все то, что друзья Филеба называют удовольствиями, они считают избавлениями от огорчений.

_Протарх_. Ну и как по-твоему, Сократ, следует им верить или нет?

_Сократ_. Нет, но стоит внять им, словно неким прорицателям, которые вещают не в силу искусства, а в силу некой брезгливости, которая свойственна не лишенной благородства натуре. Такие люди слишком возненавидели силу удовольствия и решили, что в нем нет ничего здравого, так что сама его привлекательность, по их мнению, — это иллюзия, а не удовольствие. Воспользуйся их мнением так, как я говорю, рассмотрев и другие проявления их брезгливости. После этого уясни, какие удовольствия мне предтавляются истинными, чтобы мы, прежде чем сравнить и вынести решение, изучили значения «удовольствия» в этих двух рассуждениях.

_Протарх_. Ты говоришь правильно. 

### 44d–45d Наиболее сильные удовольствия

_Сократ_. В таком случае пойдем за ними как за нашими союзниками, ступая по следу  за их брезгливостью. Я думаю, что они говорят примерно следующее, исходя из такого основного принципа. Если бы мы хотели увидеть природу любого вида, например твердого, то в каком случае нам бы это лучше удалось: если бы рассматривали [очень] твердое или чуть твердое? Тебе, Протарх, следует, как и мне, ответить на это затруднение. 

_Протарх_. Конечно, и я им отвечаю, что смотреть следует на первое по величине. 

_Сократ_. Значит, если бы мы захотели род удовольствия, какова его природа, то нам следовало бы смотреть не на умеренные удовольствия, а на наивысшие и те, о которых говорят, что они наиболее интенсивные. 

_Протарх_. Всякий бы сейчас с тобой согласился. 

_Сократ_. Но разве наиболее доступные и наиболее сильные из удовольствий, как мы часто говорим, — это не телесные удовольствия?

_Протарх_. Как же иначе!

_Сократ_. А у кого они сильнее и усиливаются — у тех, кто страдает от болезней, или у тех, кто здоров? Будем осторожны, чтобы в поспешном ответе не допустить какой-нибудь ошибки. Возможно, нам следует сказать, что у здоровых?

_Протарх_. Вероятно.

_Сократ_. Что же? Разве не те удовольствия будут сильнее, которым предшествуют наиболее сильные вожделения?

_Протарх_. Это правда. 

_Сократ_. А разве не те, кто страдает от жара или похожего недуга испытывают большую жажду и озноб и все то, что обычно бывает с телом? Им лучше знакома нехватка, и они получают большее удовольствие, когда от нее избавляются. Скажем ли мы, что это не так?

_Протарх_. Именно так, как ты сказал. 

_Сократ_. Итак, похоже, что мы не ошибемся, сказав, что если кто-то хочет увидеть величайшие удовольствия, то ему следует исследовать тех, кто устремляется не к здоровью, а к болезни? Но не подумай, что я спрашиваю тебя о том, можно ли сказать об очень больных людях, что они радуются больше, чем здоровые. Я говорю об интенсивности удовольствия и о том, в каких вообще случаях она наиболее велика. Ведь мы хотим понять, какова природа удовольствия, в том числе с точки зрения утверждающих, что удовольствий вовсе не существует. 

_Протарх_. Я почти поспеваю за твоим рассуждением. 

_Сократ_. Сейчас, Протарх, мы это поймем . Вот тебе вопрос: в какой жизни удовольствия сильнее (я говорю именно об интенсивности и силе удовольствий, а не их количестве) —в разнузданной жизни или в благоразумной? Отвечай же внимательно. 

_Протарх_. Я понял, о чем ты говоришь, разница действительно велика. Ведь людей благоразумных, пожалуй, удерживает всякий раз поговорка , повелевая: «ничего слишком!». И они повинуются этому повелению. Напротив, безумных и распущенных сильные удовольствия доводят чуть ли не до неистовства, так что те кричат, как не в себе.

_Сократ_. Хорошо. Ну а если так, то очевидно, что величайшие удовольствия, как и величайшие огорчения, возникают в некоей порочности души и тела, а не в добродетели.

_Протарх_. Именно так. 

_Сократ_. Теперь, взяв некоторые из них, следует рассмотреть, в силу каких их свойств мы их назвали величайшими. 

_Протарх_. Необходимо так и поступить. 

### 46a–47b Переоценка сильных удовольствий

_Сократ_. Рассмотри же свойства удовольствий, связанных вот с каким болезнями. 
_Протарх_. С какими же?

_Сократ_. С постыдными  — именно такие удовольствия больше всего ненавидят те, которых мы назвали брезгливыми.

_Протарх_. О чем ты говоришь?

_Сократ_. Я говорю о тех случаях, когда лечат чесотку трением, — и обо всем в этом роде, что не требует другого лечения. И вот это-то состояние, силы небесные, чем для нас становится? Удовольствие это или страдание?

_Протарх_. Похоже, Сократ, оно становится каким-то смешанным злом.

_Сократ_. Я, конечно, не с намеком на Филеба об этом говорю, а потому, Протарх, что без таких и им подобных удовольствий, если мы их не рассмотрим, мы, пожалуй, не сможем разрешить наш вопрос.

_Протарх_. Тогда вперед, к тому, что этому сродно. 

_Сократ_. Ты имеешь в виду удовольствия, которые участвуют в смешении? 

_Протарх_. Конечно.

_Сократ_. Итак, бывают смешения телесные, в самих телах, и смешения душевные, в самой душе. Кроме того, мы обнаружим, что смешения огорчений и удовольствий затрагивают и душу, и тело, и это целое иногда называется удовольствием, а иногда — огорчением.

_Протарх_. Что ты имеешь в виду?

_Сократ_. Я имею в виду все те случаи, когда [живое существо], восстанавливаясь или разрушаясь, подвергается одновременно противоположным воздействиям, иной раз согреваясь во время озноба, иной раз охлаждаясь во время перегрева. При этом, я так думаю, оно стремится одного достичь, а от другого удалиться. И вот эта-то, как говорится, смешанная с горечью сладость , от которой непросто избавиться , вызывает раздражение  и вслед за тем сильнейшее напряжение.

_Протарх_. Совершенная истина то, что ты сейчас говоришь.

_Сократ_. Значит одни из этих смешений возникают из равных огорчений и удовольствий, а в других чего-то больше?

_Протарх_. Не иначе.

_Сократ_. Скажи мне тогда о тех [смешениях], в которых огорчений оказывается больше, чем удовольствий, как в случае чесотки, о которой мы только что сказали, или зуда. Всякий раз, когда жжение и воспаление возникают внутри, ни трением, ни чесанием  до них не добраться (можно лишь достичь поверхностного расслабления ). Тогда  [больные], за неимением другого средства  приближая эти [части] к огню и, наоборот, [к холоду], поочередно испытывают то невыносимые  наслаждения, то (смотря что преобладает) причиняют внутренним [органам] нечто противоположное — боль, смешанную с удовольствием, которое испытывают внешние части. Это происходит за счет того, что сжатое насильно расслабляется, а расслабленное — соединяется, так что удовольствия соседствуют с одновременной болью.

_Протарх_. Сущая правда.

_Сократ_. Значит, всякий раз, когда в подобных случаях преобладает удовольствие, то, хотя примесь огорчения вызывает зуд  и легкое раздражение, но избыток удовольствия вызывает напряжение и заставляет метаться , так что [у человека] меняется цвет лица и сам облик, сбивается дыхание, и весь он приходит  в смятенное состояние и кричит как безумный.

_Протарх_. Именно так. 

_Сократ_. При этом, мой друг,  и сам он, и другие говорят о том, что наслаждение такими удовольствиями похоже на смерть. Именно за ними он постоянно гоняется изо всех сил, — и тем больше, чем меньше у него выдержки и ума. Именно эти удовольствия он называет великими и считает тех, кто проводит в них всю жизнь, счастливейшими из людей. 

_Протарх_. Ты, Сократ, исчерпывающе изложил то, что касается мнения людей об этом.

### 47c–50e Смешанные удовольствия души

_Сократ_. Да, Протарх, если говорить о тех удовольствиях, которые связаны с одновременными переживаниями самого тела, когда смешиваются [ощущения] внутренних и внешних частей. А те случаи, когда переживания души противоположны переживаниям тела (страдание удовольствию или удовольствие страданию), так что они сливаются воедино, — их мы обсудили ранее , сказав, что, когда  [тело] опустошается, оно желает наполнения и радуется, надеясь на него, в то же время испытывает боль от опустошения. И хотя мы ранее на это не указали, но теперь утверждаем, что во всех таких бесчисленных случаях, когда с душой происходит одно, а с телом другое, возникает единая смесь боли и удовольствия. 

_Протарх_. Похоже, ты прав. 

_Сократ_. Осталось нам рассмотреть последнюю смесь боли и удовольствия.

_Протарх_. Какую же?

_Сократ_. О которой мы сказали , что она часто возникает в самой душе. 

_Протарх_. И как именно это происходит?

_Сократ_. Согласишься ли ты, что гнев, страх, тоска, жалость, любовь, злорадство, зависть и тому подобное, — что все это некие страдания самой души?

_Протарх_. Согласен. 

_Сократ_.  Значит, мы и во всем этом обнаружим величайшие наслаждения. Надо ли напоминать о возмущении и гневе, «который и мудрых в неистовство вводит» и «в зарождении сладостней тихо струящегося меда», или о тех удовольствиях, которые примешаны к огорчениям сетования и тоски?

_Протарх_. Не надо. Все это возникает, вероятно, именно так и никак иначе.

_Сократ_. Ты, конечно, помнишь  и о  трагических представлениях, когда зрители одновременно радуются и плачут?

_Протарх_. Конечно. 

_Сократ_. А то состояние, в которое приводит наши души комедия, — знаешь ли ты, что и оно является смесью огорчения и удовольствия?

_Протарх_. Это я не совсем понимаю.

_Сократ_. В этом случае совсем не просто, Протарх, понять, что всякий раз происходит [с душой].

_Протарх_. Да, мне тоже так кажется. 

_Сократ_. Рассмотрим же его тем охотнее, чем он темнее, и тогда во всех остальных случаях станет проще уяснить, что представляет собой смесь огорчения и удовольствия.

_Протарх_. Продолжай.

_Сократ_. Мы только что упомянули злорадство; как по-твоему, можно его назвать неким душевным огорчением?

_Протарх_. Можно. 

_Сократ_. Но злорадный человек очевидно будет радоваться злополучию ближних?

_Протарх_. Еще как!

_Сократ_. А невежество  и то, что мы называем туповатостью , — поистине зло? 

_Протарх_. Не иначе. 

_Сократ_. Смотри, что из этого следует относительно природы смешного.

_Протарх_. Говори. 

_Сократ_. Одним словом, это  некая порочность, названная именем  одного [душевного] расположения; из всей порочности это такое состояние, которое противоположно  упомянутому в дельфийской надписи.

_Протарх_. Ты имеешь в виду «познай себя», Сократ?

_Сократ_. Именно так. Очевидно, что надпись «не познавай самого себя» была бы противоположна этой. 

_Протарх_. Конечно.

_Сократ_. Попытайся, Протарх, разделить это на три части. 

_Протарх_. Что ты имеешь в виду? Я совершенно не способен на это.

_Сократ_. Ты предлагаешь мне самому произвести такое деление?

_Протарх_. Да, но не только предлагаю, но и прошу.

_Сократ_. Не скажем ли мы, что те, незнание тех, кто не знает самих себя, неизбежно относится к одному из трех?

_Протарх_. О чем ты?

_Сократ_. Во-первых, к имуществу: люди считают себя богаче, преувеличивая свое состояние. 

_Протарх_. Да, многие подвержены такому заблуждению.

_Сократ_. Но еще больше тех, кто считают себя более статным и красивым, чем они есть на самом деле, и во всем, что касается тела, приписывают себе качества, далекие от истины. 

_Протарх_.  Согласен.

_Сократ_.  Ну а больше всего, я думаю, тех, кто ошибается насчет третьего рода, то есть того, что связано с душой: такие напрасно преувеличивают собственную добродетель.

_Протарх_. Весьма преувеличивают.

_Сократ_. Ну а среди добродетелей разве не мудрость, к которой так стремятся, заставляет многих вступать в споры и напускать на себя вид мнимой мудрости?

_Протарх_. Именно она. 

_Сократ_. И если бы кто-то назвал любое подобное состояние злом, он бы выразился верно?

_Протарх_. Очень.

_Сократ_. В таком случае надо провести еще одно деление, Протарх, надвое, если мы хотим, чтобы рассмотрение связанного с забавами злорадства выявило странную смесь удовольствия и огорчения. 

_Протарх_. И как же, по-твоему, мы делим надвое? 

_Сократ_. Все те многие, которые придерживаются о себе такого неразумного мнения, — у них, как и у всех вообще людей, неизбежно кому-то  сопутствует сила и могущество, а кому-то нет.

_Протарх_. Неизбежно.

_Сократ_. Так и раздели. Ты не ошибешься, назвав нелепыми тех из них, кто слаб и не может за себя постоять, когда над ним смеются. Ну а там, кто силен и способен отомстить, ты дашь в высшей степени верное определение, назвав их опасными и враждебными. Потому что невежество сильных враждебно и безобразно — и оно само, и все его подобия  вредны для близких, — а вместе со слабостью оно оказывается в ряду вещей по природе смешных.

_Протарх_. Ты говоришь правильно. Но мне не очевидно, где в этом смешение удовольствий и огорчений.

_Сократ_. Тогда рассмотри сначала действие злорадства. 

_Протарх_. Продолжай.

_Сократ_.  Это, пожалуй, некое несправедливое огорчение или удовольствие.

_Протарх_. Неизбежно.

_Сократ_. Значит, нет ничего несправедливого или злорадного в том, чтобы радоваться бедам врагов? 

_Протарх_. Конечно.

_Сократ_. А радоваться, а не огорчаться, видя порой друзей в беде, — разве это справедливо?

_Протарх_. Вовсе нет.

_Сократ_. Итак, мы сказали, что невежество — это для всех беда.

_Протарх_. Верно.

_Сократ_. Ну а мнимая мудрость и мнимая красота друзей и прочее, что мы только что перечислили, разделив на три вида и сказав, что все это смешно, когда соседствует со слабостью, и ненавистно в соединении с силой, — скажем ли мы, что наши друзья смешны, когда они находятся в таком состоянии и при этом не страшны для окружающих? 

_Протарх_. Да.

_Сократ_. Но при этом мы признаем это состояние злом, поскольку оно и есть невежество?

_Протарх_. Именно так.

_Сократ_. А мы радуемся или грустим, когда над этим смеемся?

_Протарх_. Очевидно, радуемся. 

_Сократ_.  А радость по поводу несчастий друзей, — разве мы не назвали то, что ее порождает, завистью?

_Протарх_. Не иначе.

_Сократ_. Значит, наше рассуждение указывает на то, что, когда мы смеемся над нелепостью друзей, смешивая удовольствие с завистью, то соединяем с удовольствием огорчение. Ведь мы недавно договорились, что зависть — это некое душевное огорчение, а смеяться приятно, а в такие моменты и то, и другое, возникает одновременно.

_Протарх_. Правда.

_Сократ_. Из этого с очевидностью следует, что в сетованиях, трагедиях <и комедиях>  (не только на сцене, но и вообще во всей трагедии и комедии жизни) огорчения смешаны с удовольствием, и во многих других случаях так же.

_Протарх_. С этим трудно не согласиться, Сократ, даже если бы кто-то из желания поспорить и взялся утверждать обратное.

_Сократ_. Перед этим мы перечислили гнев, тоску, сетование, страх, любовь, рвение и зависть и тому подобное и сказали, что здесь везде мы найдем смешение того, о чем теперь то и дело говорим, не так ли?

_Протарх_. Да. 

_Сократ_. Значит, мы понимаем, что все наши выводы относятся к сетованию, зависти и гневу?

_Протарх_. Ну а как же!

_Сократ_. Так что еще многое предстоит разобрать. 

_Протарх_. Да, немало.

_Сократ_. Почему, по-твоему, я прежде всего показал тебе смешение, связанное с комедией? Разве не для того, чтобы доказать , что в страхах, любовных влечениях и прочем продемонстрировать смешение гораздо проще?   Я надеюсь, что одного примера достаточно, чтобы ты позволил мне не распространяться обо всем этом и просто согласился, что и тело без души, и душа без тела, и вместе они в своих переживаниях преисполнены удовольствия, смешанного с огорчениями. Итак, скажи, позволяешь ты мне это или будем разговаривать до полуночи? Добавлю еще кое-что, благодаря чему, полагаю, ты меня отпустишь:  обо всем этом я готов завтра дать тебе отчет, а теперь хотелось бы вернуться к оставшемуся из того, что велит рассудить Филеб.

_Протарх_. Хорошо сказано, Сократ! В оставшемся направляй беседу на свое усмотрение.

### 50e–52b Чистые удовольствия души

_Сократ_. С естественной необходимостью мы могли бы от смешанных удовольствий перейти к несмешанным. 

_Протарх_. Это еще лучше сказано.

_Сократ_. Я же попробую, переменив тему,  указать их для нас. Дело в том, что я не очень доверяю тем, кто утверждает, что все удовольствия — это прекращение страданий. Но, как я сказал, я привлекаю их в качестве свидетелей того, что некоторые удовольствия мнимые, то есть вовсе не удовольствия, а другие, которые кажутся сильными и в то же время многочисленными, на самом деле смешаны с огорчениями и прекращением страданий, вызванных сильной нехваткой чего-то в теле или в душе.

_Протарх_. Ну а какие удовольствия можно было бы назвать истинными и при этом не ошибиться? 

_Сократ_. Те, что связаны с цветами, которые называют прекрасными, с очертаниями, с большинством запахов, со звуками — вообще со всем, в чем недостаток бывает неощутим и безболезнен, а наполнение ощутимо и приятно.

_Протарх_. Но в каком же смысле, Сократ, мы это утверждаем?

_Сократ_.  В самом деле, не сразу понятно, о чем я говорю, и надо постараться пояснить. Говоря о красоте очертаний, я имею в виду не то, о чем могли бы подумать многие; это не красота живых существ или их живописных изображений. Я говорю (и к этому ведет наше рассуждение) о прямой линии или окружности и о тех плоских фигурах и объемных телах, которые могут быть построены из них при помощи циркуля, линейки и угольника, если ты понимаешь, о чем я говорю. Все это прекрасно не по отношению к чему-то, как все прочее, но по природе вечнопрекрасно само по себе, и связанные с этим особые удовольствия не имеют ничего общего с удовольствиям от чесания. И некоторые цвета обладают этим свойством — мы ведь это теперь понимаем?

_Протарх_. Я пытаюсь понять, Сократ, но попытайся и ты говорить еще яснее. 

_Сократ_. Я говорю о нежных и ясных звуках голоса, которые складываются в единую чистую мелодию; они прекрасны не в отношении чего-то другого, а сами по себе, и им сопутствуют сродные им удовольствия. 

_Протарх_. Да, бывает и такое.

_Сократ_. Род удовольствий, связанный с запахами, менее божествен, чем те. Но поскольку к ним не примешаны неизбежные страдания, где бы и в чем бы мы их ни находили, я вижу в них полное сходство с предыдущими. А это, как ты понимаешь, уже два вида удовольствий, о которых мы говорим. 

_Протарх_. Понимаю.

_Сократ_. Итак, давай прибавим к этим еще и удовольствия от учения, если мы, конечно,  согласны в том, что им не сопутствует жажда знания  и изначально связанные с такой жаждой страдания.

_Протарх_. Мы согласны. 

_Сократ_. Так что же? Когда те, кто преисполнился познаний, позднее из-за забывчивости их утрачивают,  то замечаешь ли ты в этом какие-то страдания?

_Протарх_. Во всяком случае, их нельзя назвать естественными. Они скорее рождаются в размышлениях о том, что произошло — когда кто-то, лишившись необходимого знания, сожалеет о его утрате.  

_Сократ_. Но ведь мы, дорогой Протарх, сейчас разбираем лишь естественные переживания, помимо размышлений. 

_Протарх_. В таком случае ты прав: забвение знаний для нас всякий раз бывает беспечально.

_Сократ_. Значит, следует признать, что удовольствия от учения не смешаны с болью, причем свойственны они не большинству, а лишь очень немногим. 

_Протарх_. Как же не признать! 

### 52c–53с Чистота как признак истины

_Сократ_. Итак, поскольку мы уже в меру различили чистые удовольствия и те, которые вернее было бы назвать нечистыми, мысленно добавим к сильным удовольствиям чрезмерность, а к тем, что им противоположны — умеренность. И когда мы чему-то «очень» или «слишком» радуемся (неважно, случается это редко или часто), то такие удовольствия мы отнесем к роду беспредельного «более–менее», присущему как телу, так и душе. А другие отнесем к роду вещей, которым свойственна мера.

_Протарх_. Ты, Сократ, совершенно прав.

_Сократ_. Кроме того, после этого необходимо вдобавок рассмотреть вот еще какое их свойство. 

_Протарх_. Какое?

_Сократ_. Что из этого следует назвать более близким к истине? Чистое, беспримесное и достаточное или интенсивное, сильное и величайшее?   

_Протарх_. С какой, Сократ, целью ты об этом спрашиваешь?

_Сократ_. Я, Протарх, хочу ничего не упустить в нашем исследовании удовольствия и знания, есть ли что-то в каждом из них чистое и нечистое, чтобы они пришли на суд в чистой форме и чтобы и ты, и я, и все, здесь присутствующие, могли бы легче их рассудить. 

_Протарх_. Правильно. 

_Сократ_. Давай же обо всем, что мы относим к родам чистого, будем рассуждать вот как: выбрав что-то одно, рассмотрим сначала это.

_Протарх_. И что же нам выбрать?

_Сократ_. В первую очередь, если ты не против, рассмотрим род белого. 

_Протарх_. Хорошо.

_Сократ_. В чем заключается для нас чистота белого и как мы ее определяем? Будет ли чистым самое большое и обширное или самое беспримесное, в чем нет ни частицы никакого другого цвета?

_Протарх_. Очевидно, что чистым будет то, в чем меньше всего примесей.

_Сократ_. Правильно. И разве не это, Протарх, мы назовем самым подлинным и в то же время прекрасным из белого, не самое частое и большое?

_Протарх_. Совершенно верно!

_Сократ_. Стало быть, сказав, что небольшая, но чистая белизна белее, прекраснее и подлиннее большой, но смешанной, мы никак не ошибемся. 

_Протарх_. И это верно. 

_Сократ_. Так что же? Пожалуй, мы обойдемся без лишних примеров в том же роде в рассуждении об удовольствии. Сказанного достаточно, чтобы понять, что даже малое и редкое удовольствие, если оно свободно от огорчения, приятнее и подлиннее и прекраснее, чем большое и частое. 

_Протарх_. Все так, и этого примера достаточно.

### 53с–55a Удовольствие как становление

_Сократ_. Ну а как насчет такого довода? Разве мы не слышим об удовольствии, что это всегда становление , а бытия у него вовсе нет? Ведь некие остроумцы провозглашают именно это, и мы должны быть им за это признательны.

_Протарх_. Отчего же?

_Сократ_. Именно это я тебе объясню, Протарх, при помощи вопросов. 

_Протарх_. Тогда спрашивай!

_Сократ_. Среди вещей одни сами по себе, а другие всегда стремятся к другому.

_Протарх_. Что ты имеешь в виду? Что это за вещи? 

_Сократ_. Одно по природе своей всегда почтенно, а другому до него далеко.

_Протарх_. Нельзя ли яснее?

_Сократ_. Я полагаю, нам приходилось наблюдать прекрасных и достойных возлюбленных в компании их  мужественных поклонников.

_Протарх_. Еще бы!

_Сократ_. Смотри, не найдем ли мы пару, похожую на этих двух, в том, что, как мы утверждаем, существует.

_Протарх_. Повторить ли в третий раз? Яснее, Сократ, изъясняйся.

_Сократ_. Ничего тут мудреного, Протарх. Сказано это в шутку, а смысл такой, что одно всегда существует ради чего-то из сущего, а другое — то, ради чего всегда становится становящееся. 

_Протарх_. Насилу понял, Сократ, да и то не с первого раза. 

_Сократ_. Возможно, дитя, мы еще больше поймем по мере рассуждения. 

_Протарх_. Не исключено. 

_Сократ_. Так возьмем вот эту вторую пару. 

_Протарх_. Какую?

_Сократ_. Одним будет становление всего, а другим — бытие. 

_Протарх_. Согласен с тобой, пусть будет становление и бытие.

_Сократ_. Верно. И что же из этого ради чего? Скажем ли мы, что становление для бытия или что бытие для становления?

_Протарх_. Ты спрашиваешь, не будет ли упомянутое бытие тем, что оно есть, ради возникновения?

_Сократ_. Очевидно. 

_Протарх_. О боги, неужели ты задаешь такой вопрос: «Скажи мне, Протарх, возникает ли кораблестроение ради кораблей или корабли ради кораблестроения  — и все в таком духе?»

_Сократ_. Именно так. 

_Протарх_. Почему бы тебе самому себе не ответить, Сократ?

_Сократ_. Я-то отвечу, но ты тоже прими участие в рассуждении. 

_Протарх_. Ладно.

_Сократ_. Итак, я утверждаю, что средства, орудия и всякие материалы  даются всем ради становления, при этом каждое становление становится ради того или иного бытия, а становление в целом происходит ради бытия в целом.

_Протарх_. Очевидно.

_Сократ_. Стало быть, удовольствие, поскольку это становление, неизбежно возникает ради какого-то бытия.

_Протарх_. Да.

_Сократ_. А то, ради чего становится становящееся ради чего-то, это находится в области блага, так что становящееся ради чего-то надо поместить в другую область.

_Протарх_. Надо, ничего не поделаешь!

_Сократ_. Значит, мы поступим правильно, если поместим удовольствие, которое является становлением, в область, отличную от блага?

_Протарх_. Очень правильно.

_Сократ_. Итак, как я сказал в начале этого рассуждения, тому, кто провозглашает удовольствие становлением и отказывает ему во всяком бытии, надо сказать спасибо: ясно, что он смеется над теми, кто считает удовольствие благом.

_Протарх_.  Да еще как! 

_Сократ_. Кроме того, он же посмеется над всяким, кто довольствуется становлением.

_Протарх_. Что за людей ты имеешь в виду?

_Сократ_. Тех, кто утоляет голод, жажду или нечто подобное, что утоляется становлением, — такие люди радуются благодаря становлению, потому что это и есть удовольствие, и утверждают, что не захотели бы жить, не испытывая жажды,  голода и всего прочего, что, можно сказать, сопутствует подобным состояниям состояниями.

_Протарх_. Похоже, что так.

_Сократ_. Далее, мы можем утверждать, что становлению противоположно разрушение?

_Протарх_.  Конечно.

_Сократ_. Значит тот, кто это избирает такую жизнь, избирает разрушение вместе со становлением, а не тот третий образ жизни, в котором нет ни радости, ни печали, зато есть разумение в наиболее чистом виде.

_Протарх_. Похоже, Сократ, что назначение удовольствия благом влечет за собой множество нелепых последствий.

_Сократ_. Да, и среди них вот еще какое.

_Протарх_. Какое?

### 55b–c Вспомогательный довод против гедонизма

_Сократ_. Разве не нелепо полагать, что вовсе нет ни благого, ни прекрасного ни в телах, ни во многом другом, кроме как в душе? Да и в ней благое лишь удовольствие, а мужество, рассудительность, ум и другие свойственные душе блага ничуть не являются таковыми? Кроме того, мы будем вынуждены назвать того, кто не радуется, а скорбит, дурным, пока он скорбит, даже если он человек достойнейший, а того, кто радуется, мы наделим добродетелью соразмерно его радости.

_Протарх_. Это, Сократ, совершенная нелепица. 

### 55c–59c Классификация форм знания

_Сократ_. Но как бы не вышло так, что мы, всесторонне рассмотрев удовольствие, окажемся слишком снисходительны к уму и знанию. Давай добросовестно их обстучим: нет ли там изъяна? И, усмотрев самое чистое по природе, добавим наиболее подлинные части как знания, так и удовольствия в общую смесь.

_Протарх_. Правильно.

_Сократ_. Итак, из знания, связанного с учением, одно ремесленное, а другое будет относиться к образованию и воспитанию, не так ли?

_Протарх_. Так. 

_Сократ_. Давай рассмотрим, не обнаружится ли, что в ремесленных [знаниях] одна часть больше связана со знанием, а другая — меньше, так что одну следует считать более чистой, а другую — менее?

_Протарх_. Давай. 

_Сократ_. Возьмем же по отдельности главные из них.

_Протарх_. Какие же и как?

_Сократ_. Полагаю, что если бы кто-то отделил от всех искусств [искусство] счета, измерения длины или веса, то оставшаяся часть в каждом из них часть оказалась бы, как говорится, никудышной. 

_Протарх_. Да, это так. 

_Сократ_. И после этого, конечно, не оставалось бы ничего иного, кроме как догадываться, развивать с опытом и сноровкой свои чувства, полагаясь на ту способность угадывать, которую многие зовут искусством и которая усиливается благодаря упражнениям и труду.

_Протарх_. Это действительно неизбежно. 

_Сократ_. И, во-первых, больше всего этого в музыке, где для стройного звучания  требуется не измерение, а чутье, плод упражнений. Это касается и всей музыки, и в особенности игры на флейте, которая охотится за нотами, прицеливаясь к подвижной мишени, так что тут примешано много неясного, а ясного очень мало.

_Протарх_. Совершенно верно.

_Сократ_. И, несомненно, мы обнаружим, что так же обстоят дела в медицине, земледелии, навигации и военном искусстве.

_Протарх_. Несомненно. 

_Сократ_. Далее. Искусство плотника, поскольку оно чаще пользуется измерительными инструментами, точнее большинства знаний и тем самым в большей мере является искусством. 

_Протарх_. Как же это?

_Сократ_. Я имею в виду строительство кораблей, домов и другие виды плотницкого дела. Ведь оно, кажется, пользуется линейкой, циркулем, отвесом, шнурком и еще каким-то хитроумным угольником.

_Протарх_. Очень ты, Сократ, верно говоришь.

_Сократ_.  В таком случае разделим то, что называют науками, на две части: одни, менее точные, будут ближе к музыке, а другие, более точные, — к плотницкому делу. 

_Протарх_. Договорились.

_Сократ_. Из них самыми точными являются те науки, которые мы чуть раньше назвали главными. 

_Протарх_. Мне кажется, ты говоришь об искусстве счета и обо всем том, что ты только что упоминал вместе с ним. 

_Сократ_. Да. Но, Протарх, разве не следует и их тоже разделить на два вида? Как по-твоему?

_Протарх_.  О каких видах ты говоришь?

_Сократ_. Возьмем для начала арифметику. Не скажем ли мы, что один ее вид принадлежит всем, а другой — философам?

_Протарх_. И как же мы могли бы отличить одну арифметику от другой?

_Сократ_. Отличие немалое, Протарх!  Из тех, кто занимается числами, одни считают неравные единицы, например, два войска или два быка, — неважно, будут эти два чем-то очень малым или преогромным. А другие с ними никогда бы не согласились, разве что те признают, что ни одна единица ни в чем не отличается от любой другой из тысяч единиц. 

_Протарх_. Ты хорошо объяснил разницу между теми, кто усердно занимается числами, и следует признать, что есть два вида арифметики. 

_Сократ_. Так что же? Вычисления и измерения в плотницком деле и торговле  и  геометрия и вычисления в философии — скажем ли мы, что это нечто одно или же два разных вида?

_Протарх_. Если исходить из сказанного ранее, то я бы отдал свой голос за то, что их два.

_Сократ_. Верно. Ты догадываешься, ради чего мы вынесли это на обсуждение?

_Протарх_. Возможно. Но я бы хотел, чтобы ты ответил на этот вопрос.

_Сократ_. Мне кажется, что это рассуждение — и когда мы к нему приступали, и сейчас — ищет здесь [в области знания] ответ на тот же вопрос, который исследовался в связи с удовольствиями: являются ли одни знания, как и удовольствия, более чистыми, чем другие?

_Протарх_. Вполне очевидно, что именно ради этого мы и затеяли этот разговор.

_Сократ_. И что же? Разве из сказанного ранее не обнаруживается, что одни науки по отношению к другим являются более и менее ясными?

_Протарх_. Да, это так. 

_Сократ_. И разве [это рассуждение], обозначив некую науку одним именем и создав таким образом впечатление единства, не спрашивает вновь, как если бы их было две: в отношении ясности и чистоты какая наука точнее — философская или нефилософская?

_Протарх_. Да, вопрос именно в этом. 

_Сократ_. А какой ответ, Протарх, мы на него дадим?

_Протарх_. Что касается ясности, Сократ, то мы пришли к выводу об удивительном различии между знаниями. 

_Сократ_. Так что ответить будет достаточно легко?

_Протарх_. Конечно. Скажем, что эти науки сильно отличаются от других, но среди них те, которые сопряжены с усилием подлинных философов, поразительно превосходят все прочие в отношении точности и истины в числах и мерах.

_Сократ_. Пусть будет по-твоему.   Положившись на тебя, мы смело отвечаем этим мастерам словесных уверток…

_Протарх_. Что же? 

_Сократ_. Что есть две арифметики, два искусства измерения и что за ними следуют многие другие в том же роде: несмотря на присущую им двойственность, они делят единое имя.

_Протарх_. Что ж, дадим, положившись на удачу, этим, как ты их назвал, мастерам такой ответ, Сократ.

_Сократ_. И мы утверждаем, что эти знания самые точные?

_Протарх_. Да. 

_Сократ_. Но сила диалектики, Протарх, отвернулась бы от нас, предпочти мы ей кого-то еще.

_Протарх_. А какую [науку] следует называть диалектикой?

_Сократ_. Очевидно, всякому знакома та наука, о которой теперь идет речь. Я полагаю, что все, у кого есть хоть сколько-нибудь ума, считают, что знание подлинно сущего и вечно тождественного по природе будет во всех отношениях намного более истинным. А ты что скажешь, Протарх? Каково твое мнение?

_Протарх_. Я, Сократ, много раз  слышал от Горгия, что наука убеждения намного превосходит все прочие: заставляя  служить себе по доброй воле, а не насильно, так что нет ни одной науки лучше нее. И теперь мне не хотелось бы выступать ни против тебя, ни против него. 

_Сократ_.  Мне кажется, ты хотел сказать  «с оружием», но, устыдившись, промолчал.

_Протарх_.  Пусть будет так, как тебе угодно. 

_Сократ_. Не я ли сам ввел тебя в заблуждение?

_Протарх_. О каком заблуждении  ты говоришь?

_Сократ_. Так я ведь, дорогой Протарх, спрашивал не о том, какая наука из всех величайшая, наилучшая и самая полезная, а какая исследует ясное, точное и самое истинное, даже если сама она незначительна и не очень полезна, — вот о что мы сейчас ищем. Я прошу тебя подумать — и Горгий не станет сердиться, если ты признаешь за его искусством возможность приносить наибольшую пользу людям, а за тем родом исследования, о котором я сейчас говорил, — [свойство] белого [цвета], который, даже когда его мало, может быть чистым, превосходя в этом отношении, то есть истинности, большое белое, если оно не чистое. И вот теперь, хорошо поразмыслив и достаточно обсудив, приняв во внимание не на какую-то пользу от наук или на их славу, давай назовем, хорошенько поискав, некую способность любить истину и делать все ради нее, если только она свойственна нашей душе. Скажем ли мы, что именно она, по-видимому, в наибольшей степени достигает чистоты ума и разумения — или же нам надо искать другую, более важную науку?

_Протарх_. Я думаю об этом, Сократ, и, по-моему, трудно найти другое знание или науку, которые бы более стремились к истине. 

_Сократ_. Понимаешь ли ты, утверждая это, что большинство наук и все те, кто в них усердствует, в первую очередь руководствуются мнениями и напряженно исследуют то, что относится к мнению? И если кто-то думает, что он занят исследованием природы, то он, конечно, всю жизнь изучает этот мир: откуда он произошел, каким воздействиям подвергается и как сам действует. Так ли мы скажем?

_Протарх_. Так. 

_Сократ_. Значит, такой человек трудится не над тем, что вечно, а над тем, что возникает сейчас, возникнет в будущем или возникло в прошлом.

_Протарх_. Сущая правда. 

_Сократ_. А может ли точнейшая истина прояснить то, в чем нет, не было и никогда не будет ничего постоянного?

_Протарх_. Сомневаюсь.

_Сократ_. То есть то, в чем нет совсем никакого постоянства, не может стать хоть сколько-нибудь достоверным для нас?

_Протарх_. Думаю, это никак не возможно. 

_Сократ_. Значит, нет ни ума, ни знания, которые обладали бы истиной об этом.

_Протарх_. Не похоже. 

_Сократ_. Так что забудем и о тебе, и обо мне, и о Горгии с Филебом, и пусть рассуждение засвидетельствует следующее. 

_Протарх_. Что же?

_Сократ_. Надежность, чистота, истинность и неподдельность находятся для нас в области либо неизменного, тождественного и так называмое беспримесного, либо  того, что этому наиболее сродно. А все прочее следует назвать вторичным и незначительным. 

### 59c–61c Первый пересказ предшествующей беседы

_Протарх_. Ты совершенно прав. 

_Сократ_. И из существующих для этого имен разве мы не вправе выбрать прекраснейшие для прекраснейших вещей?

_Протарх_. Вероятно. 

_Сократ_. А  «ум» и  «разумение» — это наиболее почитаемые имена?

_Протарх_. Да.   

_Сократ_. Значит, именно они наиболее подходят для того, чтобы употребляться по отношению к мыслям о подлинно сущем.

_Протарх_. Согласен. 

_Сократ_. И это те самые имена, которые я недавно представил на суд.

_Протарх_.  А как же, Сократ.

_Сократ_. Ладно. Если бы кто-то сказал, имея в виду взаимное смешение разумения и удовольствия, что перед нами, словно перед творцами, находится нечто, из чего и в чем следует творить, это было бы хорошее сравнение?

_Протарх_. Замечательное.  

_Сократ_. Ну что ж, приступим теперь к смешению?

_Протарх_. Да. 

_Сократ_. Не правильнее ли в таком случае объявить и напомнить себе следующее? 
_Протарх_. Что же?

_Сократ_. То, что мы уже напоминали. По-моему, права пословица, утверждающая, что прекрасное и дважды, и трижды стоит повторить.

_Протарх_. Согласен.

_Сократ_. Что ж, приступим. Полагаю,  тогда мы сказали нечто в таком роде.

_Протарх_. В каком?

_Сократ_. Филеб утверждает, что удовольствие — это верная цель для всех живых существ, к которой все должны стремиться, причем оно же является и благом для всех, так что два имени —  «благо» и «удовольствие» — верно относятся к чему-то единому и одному по природе.  Сократ же утверждает, что это не одно, а два, как и два имени, при этом природа блага отличается от природы удовольствия, а к уделу блага более причастно разумение, чем удовольствие. Не это ли мы утверждали и утверждаем, Протарх?

_Протарх_. Именно это. 

_Сократ_. Стало быть, мы и  тогда, и теперь согласились бы вот в чем.

_Протарх_. В чем же?

_Сократ_. Что природа блага отличается от всего прочего вот чем.

_Протарх_. Чем?

_Сократ_. То из живых существ, кому оно постоянно, во всех отношениях и полностью присуще, не нуждается больше ни в чем, но совершенно самодостаточно. 
_Протарх_. Да. 

_Сократ_. Итак мы в качестве эксперимента по отдельности поместили  в жизнь каждого и то, и другое: удовольствие, не смешанное с разумением, и разумение, точно так же свободное ото всякой приятности. 

_Протарх_. Так и было. 

_Сократ_. И разве нечто из этого показалось нам для кого-либо достаточным?

_Протарх_. Конечно, нет.

_Сократ_. И если мы тогда в чем-то отклонились от истины, пусть кто-нибудь нас исправит и скажет лучше. Рассматривая и исследуя как одну идею память, разумение, знание и подлинное мнение, пусть он скажет, захочет ли кто-нибудь без всего этого вообще чем-то владеть или что-то приобретать, — не говоря уже об удовольствии, сколь угодно большом и сильном.  Ведь такой человек не сможет ни составить истинное мнение о том, чему он радуется, ни вообще распознать, что за чувство он испытал, ни, наконец, хоть ненадолго удержать в памяти это чувство. То же самое пусть он скажет и о разумении: согласится ли кто-то обладать разумением вообще безо всякого удовольствия, хотя бы самого мимолетного,  или с некоторыми удовольствиями — и примет ли кто-нибудь все удовольствия без разумения или же с каким-то разумением. 

_Протарх_. Такого человека нет, нет необходимости постоянно об этом спрашивать.

_Сократ_. Значит, совершенное и для всех предпочтительное и всеблагое не является ничем из этого?

_Протарх_. Конечно, нет. 

_Сократ_. Тогда попробуем отчетливо уловить благо или же его смутные очертания — так мы узнаем, кому же отдать вторую награду.

_Протарх_.  Ты прав. 

_Сократ_. Значит, мы вышли на некий путь к благу?

_Протарх_. На какой же?

_Сократ_. Если, разыскивая человека, некто в первую очередь осведомится о доме, где тот живет, это будет, пожалуй, для него немалым продвижением в поиске. 

_Протарх_. А как же. 

_Сократ_. Точно так же и сейчас рассуждение, как и прежде, нам возвещает искать блага не в несмешанной жизни, а в смешанной. 

_Протарх_. Да. 

_Сократ_. И мы скорее в прекрасной, а не в дурной, смеси с большей ясностью увидим искомое?

_Протарх_. С гораздо большей. 

_Сократ_. В таком случае, Протарх, приступим к смешению, вознося молитву богам — будь то Дионис, Гефест или кто другой из богов, кому досталась в удел такая обязанность. 

_Протарх_. Приступим. 

_Сократ_. Перед нами, словно перед виночерпиями, — несколько источников. Один из них, источник удовольствия, можно уподобить меду, а отрезвляющий, без примеси вина,  источник разумения подобен некой пресной и целебной воде. Их-то и следует нам как можно лучше смешать. 
_Протарх_. А как же. 

### 61d–64a Какие знания и удовольствия могут быть допущены в благую жизнь? 

_Сократ_. Начнем же вот с чего: смешивая всякое удовольствие со всяким разумением, сможем ли мы достичь наилучшего результата?

_Протарх_. Возможно. 

_Сократ_. Но это ненадежный способ. Думаю, я мог бы предложить другой, более безопасный. 

_Протарх_. Скажи, какой. 

_Сократ_. Одно удовольствие у нас, как мы полагали, обладает более подлинным бытием, чем другое, а одна наука точнее другой. 

_Протарх_. Не иначе. 

_Сократ_. Да и знание знанию рознь: одно обращено на возникновение и гибель, другое — на то, что не возникает и не гибнет, а всегда тождественно и неизменно. И это последнее, рассматривая его с точки зрения истины, мы признали более истинным, чем первое. 

_Протарх_. Совершенно верно.

_Сократ_. Если бы мы сначала смешали наиболее подлинные части и удовольствия, и знания, то было бы этих частей достаточно для того, чтобы, породив наиболее желанную жизнь,  нам ее доставить? Или же чего-то, хотя бы и не такого подлинного, будет нехватать?

_Протарх_. По-моему, надо сначала смешать. 

_Сократ_.  Допустим, у нас есть человек, размышляющий о справедливости как таковой, что это такое, причем его рассуждения следуют за мыслью, да и обо всем прочем из сущего он точно так же думает. 

_Протарх_. Допустим. 

_Сократ_. Достаточным ли будет его знание, если он будет иметь представление о божественных круге и шаре как таковых, а наш человеческий шар и наши круги будут ему неведомы, при этом в строительстве и в прочих делах он будет с тем же непониманием пользоваться и линейкой, и циркулем?

_Протарх_. Наше положение, Сократ, можно назвать нелепым, если бы мы не смыслили ни в чем, кроме божественных наук. 

_Сократ_. Так как же? Неужели мы должны добавить в нашу смесь ненадежную и нечистую науку о ложных линейках и циркулях?

_Протарх_. Это необходимо, если мы намерены иной раз отыскать дорогу домой.

_Сократ_. Что же, и музыку добавим тоже, хотя мы недавно сказали, что в ней немало догадок и подражания, а чистоты недостает?

_Протарх_. И это, по-моему, необходимо, чтобы наша жизнь была хоть сколько-нибудь жизнью. 

_Сократ_. Значит ты хочешь, чтобы я, как теснимый  толпой привратник,  поддавшись ее напору, распахнул двери и позволил вливаться и смешиваться всем знаниям, как чистым, так и менее совершенным?

_Протарх_. Не вижу, Сократ, никакого вреда в том, чтобы принять все прочие знания, при условии, что владеешь главными.

_Сократ_. Пусть все они устремятся в то место, которое  Гомер поэтично назвал «долиной, в которой сливаются воды»?

_Протарх_. Пусть.

_Сократ_. Готово. Вернемся теперь к источнику удовольствий. У нас не получилось смешивать так, как мы планировали, добавляя сначала части подлинных. Из-за любви ко всякому знанию мы его впустили все целиком, причем еще до удовольствий. 

_Протарх_. Верно говоришь. 

_Сократ_. Самое время решить и насчет удовольствий: впустим ли мы их все без разбора или же сначала только подлинные?

_Протарх_. Гораздо более безопасно впустить сначала подлинные.

_Сократ_. Тогда пусть входят. Что потом? Если есть некие необходимые удовольствия, то их, как и необходимые знания, мы добавим в смесь?

_Протарх_.  Отчего же не добавить? Само собой, раз уж они необходимы.

_Сократ_. Ну а если мы скажем об удовольствиях то же, что о науках, то есть что это безвредно и даже полезно знать их все на протяжении жизни? Если только радоваться всю жизнь всем удовольствиям для всех нас  полезно и для  всех безвредно, то надо примешать их все.

_Протарх_. Что же нам о них сказать и как поступить?

_Сократ_. Не нас, Протарх, надо расспрашивать об этом, а сами удовольствия и разумные способности. И вот что стоит разузнать насчет их взаимоотношений.

_Протарх_.  Что же?

_Сократ_.  «Дорогие — не знаю, назвать ли вас удовольствиями или другим каким-то именем — вы бы предпочли жить со всеми разумными способностями или вовсе без разумения?» Думаю, на это они скажут следующее. 

_Протарх_. Что?

_Сократ_. То, о чем мы говорили ранее: «Всякому роду жить одиноко и обособленно, не смешиваясь с другими, и невозможно, и не полезно. И из всех родов мы бы больше всего предпочли соседствовать с родом знания — как знания всего прочего, так и совершенного, насколько это возможно, знания каждого из нас».

_Протарх_. Мы им ответим: «Как это вы хорошо сказали!»

_Сократ_. Верно. Значит, после этого следует вновь обратиться с вопросом, на этот раз к разумению и уму: «А вам в смеси нужны какие-то из удовольствий?» — вот так мы бы, пожалуй, их спросили. А они бы ответили: «Смотря какие».

_Протарх_. Вероятно. 

_Сократ_. А мы на это будем рассуждать вот как. «Нужны ли вам в качестве соседей, — скажем мы, — не только подлинные удовольствия, но и величайшие и сильнейшие?» «Что ты такое предлагаешь, Сократ? — скажут они, пожалуй. — Ведь такие удовольствия создают нам множество помех, доводя до одержимости души, в которых мы обитаем; нам самим они вовсе не дают появиться, а наших детей по большей части совершенно губят: из-за них те оказываются в пренебрежении, а там и вовсе предаются забвению. Но те удовольствия, которые ты называл подлинными и чистыми, нам почти родные. А к ним примешай еще и те, что сопутствуют здоровью и благоразумию, да и все те, что стали спутниками любой добродетели и повсюду за ней следуют, как за богом. А смешивать с умом те удовольствия, которые всегда в компании с неразумием и прочим пороком, было бы, пожалуй, опрометчиво для того, кто желает, взглянув на прекраснейшую смесь и дружное соседство, найти ответ на вопрос, чем же и в человеке, и в космосе по природе своей является благо и какой вид следует в нем угадать». Разве мы не скажем, что такой ответ ума о себе самом, о памяти и правильном мнении будет и разумным, и рассудительным?  

_Протарх_. Безусловно. 

### 64a–66a Красота, соразмерность и истина как проявления блага

_Сократ_. Однако необходимо вот еще что — иначе ничто возникнуть не сможет. 

_Протарх_. Что же? 

_Сократ_. К чему мы не примешаем истину, то не могло бы поистине ни возникать, ни быть возникшим. 

_Протарх_. Как же ему возникнуть? 

_Сократ_. Никак! Но если еще чего-то не хватает нашей смеси, вы с Филебом скажите. Мне же кажется, что наше рассуждение выполнено словно некий бесплотный космос, которому предстоит властвовать над одушевленным телом. 

_Протарх_. Считай, что и я, Сократ, того же мнения. 

_Сократ_. Так мы не ошибемся, сказав, что теперь уже стоим на пороге обители блага?

_Протарх_. Мне так кажется. 

_Сократ_. В чем же, скажем мы, главная ценность и причина того, что подобное расположение для всех желанно? Ответив на этот вопрос, мы исследуем, что к этому более близко и подобно во вселенной — удовольствие или ум.  

_Протарх_. Правильно. Это бы нам очень помогло вынести решение. 

_Сократ_. И в самом деле, нетрудно указать причину, по которой любая смесь становится либо в высшей степени ценной, либо ни на что не годной. 

_Протарх_. О чем ты?

_Сократ_. Это всем известно.

_Протарх_. Что же?

_Сократ_. Что всякое смешение, ни в малейшей степени не обладающее мерой и природой соразмерного, неизбежно губит и свои ингредиенты, и в первую очередь само себя. В самом деле, это уже не смесь, а в чистом виде мешанина и просто беда для того, кому она досталась. 

_Протарх_. Верно. 

_Сократ_. Значит, теперь сила блага у нас укрылась в природе прекрасного, ведь умеренность и соразмерность повсюду становятся красотой и добродетелью.

_Протарх_. Так и есть.

_Сократ_. И к ним, как мы уже сказали, примешана истина. 

_Протарх_. Да. 

_Сократ_. Итак, если мы не можем уловить благо одной идеей, то ухватим тремя: красотой, соразмерностью и истиной. И из всего, что есть в смеси, именно это, как некое единство, мы бы с наибольшим основанием назвали причиной, и поскольку оно благо, то и сама смесь становится благой. 

_Протарх_. Совершенно верно. 

_Сократ_. Что ж, Протарх, теперь у нас всякий смог бы рассудить удовольствие и разумение, сказав, что из этого наиболее сродно благу и наиболее ценно среди людей и богов. 

_Протарх_. Само собой, и все-таки лучше проследовать за рассуждением до конца.

_Сократ_. В таком случае сопоставим все три с удовольствием и умом, ведь нам надо понять, к чему как к наиболее сродному мы должны каждое из них отнести. 

_Протарх_. Ты имеешь в виду красоту, истину и умеренность?

_Сократ_. Да. Прежде всего возьми истину, Протарх, а взяв и взглянув на всех троих — ум, истину и удовольствие, — ответь себе, выждав достаточное время, что ближе истине: удовольствие или ум. 

_Протарх_. Зачем ждать? Они, по-моему, сильно различаются. Удовольствие, как говорят, — величайший проходимец, а в любовных удовольствиях, которые кажутся самыми сильными, боги прощают даже клятвопреступление, как будто удовольствия, словно дети, вовсе лишены ума. А ум — это либо то же, что истина, либо нечто в высшей степени ей подобное и истинное. 

_Сократ_. После этого точно так же рассмотри умеренность, у кого ее больше — у удовольствия или у разумения? 

_Протарх_. И этот вопрос не труден. Полагаю, что никто не  найдет ничего из сущего, чему так свойственна неумеренность, как удовольствию и чрезмерной радости, а ум и знание — пожалуй, самые умеренные. 

_Сократ_. Прекрасно сказано. Но скажи еще о третьем. Ум у нас больше причастен красоте, чем род удовольствия, так что ум прекраснее удовольствия, не так ли?

_Протарх_. Так ведь никто и никогда, Сократ, ни во сне ни наяву не мог ни увидеть, ни помыслить того, чтобы разумение и ум хотя бы в малейшей степени  были безобразны в прошлом, настоящем или будущем.

_Сократ_. Верно.

_Протарх_. А когда мы видим, как нелепо или безобразно бывает, если кто-то предается удовольствиям, в особенности величайшим, то сами стыдимся так поступать и наслаждаемся тайком, как можно более незаметно, поручая все подобное ночи, потому что свет на это взирать не должен. 

### 66a–67b Классификация благ, в которой удовольствиям отводится низшее место

_Сократ_. Итак, Протарх, ты всеми способами — и лично, и через глашатаев — объявишь, что удовольствие не относится ни к числу первых, ни к числу вторых приобретений. Но первой мы избрали вечную [природу] в области меры, то есть умеренного, надлежащего и всего того, что следует считать таковым.

_Протарх_. Видно, такой вывод следует из сказанного.  

_Сократ_. А второе место отведено тому, что находится в области соразмерного, прекрасного, совершенного, самодостаточного и всего в том же роде.

_Протарх_. Похоже, что так.

_Сократ_. Далее, отдав третье место, как я предвижу, уму и разумению, ты бы не сильно уклонился от истины. 

_Протарх_. Вероятно.

_Сократ_. И не ошибся бы, поместив вслед за этими тремя на четвертом месте все то, что мы отнесли к самой душе: знания, науки, а также то, что мы назвали правильными мнениями. Они ведь более сродны благу, чем удовольствия. 

_Протарх_. Возможно. 

_Сократ_. Пятыми же пусть будут те удовольствия, которые мы определили как беспечальные, назвав их чистыми и принадлежащими самой душе; из них одни сопровождают знания, а другие чувственные восприятия. 

_Протарх_. Допустим.

_Сократ_. «На шестом же колене, — велит Орфей, — прервите строение песни». Так и наше рассуждение, похоже, прерывается на шестом приговоре. И после этого нам ничего не остается, кроме как подвести итог сказанному. 

_Протарх_. Да, не помешает.

_Сократ_. Что ж, давай в третий раз для [Зевса] Спасителя засвидетельствуем то же рассуждение.

_Протарх_. О чем ты?

_Сократ_. Филеб утверждал, что для нас благом во всех отношениях является всякое удовольствие. 

_Протарх_. Похоже, Сократ, ты собираешься в третий раз с самого начала повторить все рассуждение.

_Сократ_. Все так; но давай дослушаем. Принимая во внимание то, что только что было изложено, и отвергая рассуждение Филеба и многих других людей, я сказал, что в человеческой жизни ум намного лучше и достойнее удовольствия.

_Протарх_. Так и было.

_Сократ_. Но, догадываясь о том, что этим дело не ограничивается, я сказал, что, если что-то окажется лучше и того, и другого, то я бы состязался на стороне ума за второе место, а удовольствию не досталось бы даже и того.

_Протарх_. Да, ты так сказал. 

_Сократ_. После чего нам стало достато очевидно, что ничего из этого не достаточно. 

_Протарх_. Верно. 

_Сократ_. Итак, наше рассуждение совершенно запретило и уму, и удовольствию именоваться благом, потому что и то, и другое лишено самодостаточности, то есть силы, присущей самодовлеющему и совершенному. 

_Протарх_. Правильно. 

_Сократ_. А после того, как нечто третье одолело и ум, и удовольствие, ум оказался во много раз более близким и свойственным облику победителя, чем удовольствие.

_Протарх_. Именно так. 

_Сократ_. Таким образом, согласно приговору, только что изреченному нашим рассуждением, сила удовольствия занимает пятое место. 

_Протарх_. Похоже, что так.

_Сократ_. А первого места она не заслуживает, хотя бы все быки, лошади и все вообще животные утверждали это самим своим стремлением к наслаждению. Многие, поверив им, словно прорицатели птицам, заключили, что удовольствия более всего способствуют благой жизни; для таких людей свидетельства животных влечений значат больше, чем влечение к речам, прорицаемым под воздействием философской музы.

_Протарх_. Теперь, Сократ, мы все утверждаем, что ты совершенно прав. 

_Сократ_. Значит, вы меня отпускаете?

_Протарх_. Еще совсем немногое осталось обсудить, Сократ: ты ведь, конечно, не сдашься прежде, чем мы. А я тебе напомню, что нам остается... 


