---
suppress-bibliography: true
---

### Хронология

Исследователи почти единодушно относят «Филеб» к группе поздних диалогов, причем на основании как стилистических, так и содержательных критериев. С точки зрения стиля с группой поздних диалогов его роднит использование τί μήν; отсутствие формул τῷ ὄντι и ὡς ἀληθῶς, на смену которым приходят ὄντως и ἀληθῶς; предпочтение, отдаваемое καθάπερ перед ὥσπερ; снижение количества зияний (3,7 на страницу по сравнению, например, с 38,8 в «Апологии»); частотность определенного типа клаузул, характерных для «Законов»; анастрофическое πέρι (34% всех употреблений предлога, что сравнимо с 31% в «Законах»); преобладание ὀρθότατα / ἀλεθέστατα (λέγεις) над ἀληθῆ / ὀρθῶς (λέγεις) и другие признаки [@brandwood1992]. В отличие от других сократических диалогов, "Филеб" написан в прямой драматической форме, переход к которой объявлен в «Теэтете» (143c), и по этому формальному критерию тоже считается скорее поздним.

Около 150 лет назад Эдуард Целлер (известный противник набиравшей тогла популярность стилометрии) защищал более раннюю датировку «Филеба», помещая его перед "Государством" [@zeller1888, 138]. Сомнения насчет "стандартной хронологии" звучат и сегодня [@waterfield1980; @howland1991]. Вопреки распространенному убеждению, возможности стилометрии для датировки диалогов сильно ограничены [@alieva2024]. Кроме того, последние стилометрические эксперименты показывают, что надежных оснований для выделения "ранней" и "средней" группы нет, что ставит под сомнение и "позднюю" группу [@alieva2025].

Содержательно «Филеб» также считается "поздним". Сократ говорит о своей любви к методу диэрезы (16b), впервые анонсированному в «Федре» и опробованному в «Софисте» и «Политике». Некоторые «загадки» (15a–16e), упомянутые в «Софисте» и «Пармениде» (128a–d), отвергаются как общеизвестные и ребяческие. В некоторых местах, возможно, предполагается знакомство с космогонией «Тимея» (30а), с которым «Филеб» сближают и другие возможные параллели [@hackforth1945, 3]. Но с уверенностью судить об относительной хронологии в группе «Софист», «Политик», «Тимей» и «Филеб» невозможно. Важнейшее внешнее основание для датировки "Филеба" связано с тем, что диалог явно принимает во внимание доктрину Евдокса Книдского, появившегося в Академии в конце 360-х гг. [@thesleff1982, 199].

Хакфорт предлагает в качестве возможной даты 360–354, то есть после второй поездки на Сицилию и до смерти Диона, поскольку именно в этот период Платон должен был испытывать «временное отвращение к политике». После убийства Диона его ум переключился на планы политического спасения Сицилии, как следует из 7-го и 8-го письма. На этом основании Хакфорт считает, что «Тимей» создан позже, после 354 г. [@hackforth1945, 3-4]. Однако это предположение основано лишь на том, что «Филеб» рассматривает благо в масштабе частной жизни и не имеет никакого политического звучания. Это очевидная натяжка: все те же этические вопросы Платон поднимает в поздних «Законах».

Укоренившаяся «стандартная хронология» долгое время определяла характер исследовательских нарративов. Ярким примером здесь может служить авторитетный труд Гослинга и Тейлора *The Greeks on Pleasure* [@gosling1982, 138–139]. Авторы утверждают, что в период между написанием «Государства» и «Филеба» Платон «разочаровался в тех концепция, в которых ему и следовало разочароваться»; среди прочего, он признал, что модель «восполнения» (replenishment model) имеет ограниченное применение в случае интеллектуальных удовольствий. Кроме того, абсолютным новшеством «Филеба» признается «удовольствий предвосхищения» [@gosling1982, 142]. Согласно такому подходу, обращаться к более ранним текстам Платона для прояснения спорных пассажей «Филеба» не имеет никакого смысла.

Этот взгляд привел к серьезным искажениям при интерпретации "Филеба", который до недавних пор изучался практически в изоляции от остального корпуса. В этой работе принимается подход, который менее чувствителен к хронологии. Это позволяет реконструировать ключевые доктрины с опорой на "Государство" и "Теэтета".

### Подлинность

Стилистическая близость к «Законам», к которой апеллируют сторонники "стандартной хронологии", сама по себе является проблематичной в силу того, что сами «Законы» были опубликованы не Платоном, а Филиппом Опунтским – вероятно, после смерти Платона. Филипп также считается автором "Послезакония", которое стилистически примыкает к группе "поздних" текстов [@tarán1975, 138; о стилистике см. @alieva2025].

> «Возможно ли, что “поздний стиль” с его специфическим подбором слов, замысловатым синтаксисом, избеганием зияний (маньеризм в духе Исократа, едва ли привлекательный для старого Платона), ритмическими клаузулами, — что все это стиль секретарский?» [@thesleff1982, 186].

Если такая мысль допустима, то вся «поздняя» группа может представлять собой диалоги условно или полуаутентичные, то есть опубликованные с одобрения Платона или на основании его заметок или устных бесед [@thesleff1982, 198]. Подробнее о концепции "полуаутентичных" диалогов см.: [@alieva2024a].

### Действующие лица {#personae}

Хотя в поздних диалогах Платона Сократ нередко уступает роль протагониста другим персонажам (Парменид, Тимей и Критий в одноименных диалогах; Чужеземец из Элеи в "Софисте" и "Политике"; Афинянин в "Законах"), в "Филебе" он снова — главное действующее лицо, так что некоторые исследователи говорят о своего рода "сократическом ренессансе" [@frede1997, 93]. Этому предлагались различные объяснения, все до известной степени спекулятивные. Заметим лишь, что к последней четверти IV в. мода на Сократа и все сократическое в Академии окончательно возобладала [@donato2020]; возможно, здесь мы имеем дело с тем же явлением.

Собеседники Сократа в "Филебе" почти бесплотны. Можно не сомневаться, что Филеб, занимающий в диалоге гедонистическую позицию, — это фиктивное лицо. На это указывает не только его говорящее имя — буквально Mr. Loveboy (греч. ἥβη "юность" и φιλέω "любить") — но и тот факт, что это имя неизвестно в античной Греции [@neylz2019, 336]. Во II в. сатирик Лукиан, уловив эротические коннотации имени, назвал так одного из героев своего «Лукия» (36).

Что касается Протарха, то он упомянут как сын Каллия (19b), что позволяло связывать его с богачом Каллием из "Апологии", но есть убедительные основания считать, что это невозможно [@neylz2019, 295]. Высказывалась точка зрения, что за Протархом (Mr. First Principle, от греч. πρῶτος "первый" и ἀρχή "начало") скрывается Аристотель [@shichalin1991]. Основным препятствием для такого понимания является то, что Протарх в начале беседы стоит скорее на позициях Евдокса. Даже если формальная «передача тезиса» не требует от него разделять точку зрения гедониста, его собственная позиция по вопросу удовольствий почти никак не проявляется, в то время как Аристотелю очевидно было что сказать.

В диалоге отсутствуют всякие указания на место или время действия. Подобный схематизм может указывать на то, что все три фигуры — своего рода "прокси" для современников Платона. Несколько раз в тексте встречается указание на то, что разговор происходит в присутствии молодых слушателей (16a, 19d), которые готовы даже припугнуть Сократа, чтобы добиться от него ответа.

### Контекст

Насколько позволяет судить десятая книга "Никомаховой этики" Аристотеля, удовольствие было одной из обсуждаемых тем в Академии: об этом высказались, помимо самих Платона и Аристотеля, Евдокс и Спевсипп. К этому списку следует добавить также Гераклида Понтийского. Несмотря на местами отрывочный характер сведений, они позволяют наметить некоторые линии полемики, необходимые для понимания историко-философского контекста, в котором появился «Филеб».

Гераклид Понтийский должен был появиться в Академии достаточно рано, чтобы взять на себя обязанности по управлению школой в 361 г., когда Платон отбыл на Сицилию. Ему принадлежал диалог «О наслаждении» (или же «О наслаждении, или об умеренности»), с которым соотносят фр. 39–44 . Все эти фрагменты происходят из «Пирующих софистов» Афинея и представляют собой по большей части анекдоты наставительного характера. На множестве примеров Гераклид показывает, что чрезмерная роскошь и связанный с ней разгул приводят к страданиям и разрушают благополучие. Распущенность погубила самосцев и сибаритов (фр. 41); разорила Каллия (фр. 42) и уменьшила состояние Перикла (фр. 43), довела до кастрации торговца духами Диния (фр. 44).

::: {.callout-note icon="false" appearance="simple"}
*Раздел дорабатывается. Это предварительная версия.*
:::

### Композиция и литературная форма {#composition}

Уже Готфриду Штальбауму [@stallbaum1842, 10] пришлось оспаривать точку зрения, согласно которой текст «без начала и конца» либо дошел до нас в усеченном виде (*truncatus*), как полагал Франческо Патрици в XVI в., либо, как считал Фридрих Аст [@ast1816, 293], не был завершен автором. Со Штальбаумом соглашался Василий Николаевич Карпов. В предисловии к своему переводу он писал: «Никак нельзя согласиться с Астом, когда он, имея в виду начало диалога, а еще больше конец его, утверждает, что Филеб, в ряду Платоновых диалогов, есть только одна часть задуманного Платоном большого сочинения, которого другие части или не были написаны, или в последующие времена утратились…» [@karpov1879, 47].; см. [комментарий к 11а–12b](comments.qmd#commI).

Современные исследователи в основном сходятся на том, что необычный композиционный ход имеет философское значение: Филеб настолько преклоняется пред удовольствием, что не способен подвергнуть его критическому рассмотрению [@ionescu2019, 38]. Строго говоря, его даже нельзя назвать гедонистом, так как гедонизм предполагает интеллектуальное усилие для формулировки этической системы, а именно на это он не способен.

Тем не менее, композиционно диалог не очень гладкий. Марта Нуссбаум ссылается на неопубликованное мнение Гвилима Оуэна, согласно которому «Филеб» — это наскоро скроенный "пэчворк" [@nussbaum1986, 459n21]. Эту точку зрения повторяет и Дебра Нейлз [@neylz2019, 296]. Замечания о том, что отдельные части «Филеба» плохо связаны друг с другом, являются общим местом в литературе; см. подробнее: [@alieva2023, 113].

В последние годы предпринимаются попытки защитить единство композиционной структуры "Филеба". Одна из недавних таких попыток принадлежит Шону Келси и Габриел Р. Лир [@kelsey2019], которые приходят к выводу, что аномалии в аргументации не напрасны и призваны "изменить этико-интеллектуальные установки" Протарха. С этой точки зрения, отступления, которые на первый взгляд не приближают собеседников к решению основного вопроса о роли наслаждения и знания в благой жизни, оправданы настолько, насколько они преображают Протарха. Удовольствие должно лишиться своего очарования, а разум, напротив, стать более привлекательным, чтобы Протарх подчинился требованиям разума. Неровности текста тем самым не снимаются, а получают "диалектическое" объяснение. На важность "обращения" Протарха указывали и другие исследователи [@larivee2011].

### Переводы

Первый перевод "Филеба" на русский язык был выполнен в XIX в. В.Н. Карповым [@karpov1879].

В первой четверти XX в. платоновский «Филеб» был полностью переведен на русский язык доцентом Московского университета и преподавателем Московских высших женских курсов Н.В. Самсоновым (1878-1921), доцентом Московского университета и преподавателем Московских высших женских курсов. Перевод Самсонова вошел в пятнадцатитомник Платона под ред. С.А. Жебелева, Л.Э. Радлова и Л.П. Карсавина (1922–1929), причем четвертый том с «Филебом» был опубликован в 1929 г., уже после смерти переводчика в сентябре 1921 г.

Как указано на с. 186, все примечания к переводу 1929 г. составлены С.А. Жебелевым и А.А. Франковским; в частности, последнему принадлежит примечание 63 на с. 190, где читаем: «В своей передаче мы сообразовывались с различными комментариями…». Это почти наверняка означает, что редакторы исправляли текст Самсонова. Но в какой мере, сложно сказать: рукопись перевода не сохранилась.

Тот же перевод был позднее «заново сверен» И.И. Маханьковым и включен в четырехтомник под редакцией А.Ф. Лосева (1994 г.). В 2024 г. О.В. Алиева выполнила автоматическое сравнение двух версий перевода; результаты доступны по [ссылке](https://locusclassicus.github.io/samsonov_translation/). Это сравнение показало, что перевод «Филеба» в издании Лосева было бы правильнее называть не переводом Самсонова, а переводом Самсонова-Маханькова, потому что текст был решительно переработан — не только стилистически, но и по существу.

Ок. 1917 г. частичный перевод диалога выполнил также И.Б. Румер. Рукопись этого перевода сохранилась в архиве Г.Г. Шпета, который планировал включить отрывок из «Филеба» в хрестоматию по истории психологии. Румер перевел ту часть, которая интересовала Шпета в связи с «психологией» Платона: это страницы 32с–40c, где даются определения чувства, памяти, воспоминания, желания и удовольствия. В 2024 г. этот перевод был первые опубликован [@alieva2024b]. Эта публикация позволяет дополнить картину рецепции платоновских текстов в интеллектуальной культуре России первой трети XX в. В частности, мы видим, что оба переводчика, близкие к кругу Г.Г. Шпета, интересовались психологической проблематикой, и в целом «Филеб» читался скорее как диалог о психологии, чем о диалектике или метафизике.
